import { StyleSheet } from "react-native";
import { BORDER_DIM, GOLD, ON_GOLD, SURFACE, TEXT, TEXT_DIM } from "./_constants";

export const s = StyleSheet.create({
  slide: {
    flex: 1,
    alignItems: "center",
    paddingHorizontal: 28,
    justifyContent: "space-between",
  },
  upper: {
    alignItems: "center",
    width: "100%",
    flex: 1,
    justifyContent: "center",
  },
  lower: {
    width: "100%",
    alignItems: "center",
    gap: 0,
  },

  // Icon
  iconWrap: { alignItems: "center", justifyContent: "center", marginBottom: 22 },
  iconGlow: {
    position: "absolute",
    width: 130,
    height: 130,
    borderRadius: 65,
    backgroundColor: GOLD + "14",
  },
  iconRing: {
    width: 96,
    height: 96,
    borderRadius: 48,
    borderWidth: 1.5,
    borderColor: GOLD + "40",
    backgroundColor: GOLD + "0E",
    alignItems: "center",
    justifyContent: "center",
  },

  // Text
  nuurLogo: {
    fontSize: 40,
    fontFamily: "Inter_700Bold",
    color: GOLD,
    letterSpacing: 2,
    marginBottom: 10,
  },
  title: {
    fontSize: 26,
    fontFamily: "Inter_700Bold",
    color: TEXT,
    textAlign: "center",
    letterSpacing: -0.3,
  },
  subtitle: {
    fontSize: 15,
    fontFamily: "Inter_400Regular",
    color: TEXT_DIM,
    textAlign: "center",
    marginTop: 6,
  },
  divider: {
    width: 36,
    height: 1.5,
    backgroundColor: GOLD + "55",
    borderRadius: 1,
    marginVertical: 18,
  },
  body: {
    fontSize: 14,
    fontFamily: "Inter_400Regular",
    color: TEXT_DIM,
    textAlign: "center",
    lineHeight: 22,
  },

  // Buttons
  primary: {
    width: "100%",
    backgroundColor: GOLD,
    borderRadius: 14,
    paddingVertical: 15,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginBottom: 10,
  },
  primaryDone: { backgroundColor: "#2A7A4F" },
  primaryText: { color: ON_GOLD, fontSize: 16, fontFamily: "Inter_700Bold" },
  primaryDoneText: { color: "#fff" },
  ghost: { paddingVertical: 11, paddingHorizontal: 16 },
  ghostSmall: { paddingVertical: 6, paddingHorizontal: 16 },
  ghostText: { color: TEXT_DIM, fontSize: 14, fontFamily: "Inter_400Regular" },
  ghostLink: {
    color: GOLD,
    fontSize: 14,
    fontFamily: "Inter_600SemiBold",
    textDecorationLine: "underline",
    textDecorationColor: GOLD + "55",
  },

  // Permission-denied recovery card
  deniedCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    width: "100%",
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 12,
    backgroundColor: "rgba(232,184,106,0.08)",
    borderWidth: 1,
    borderColor: "rgba(232,184,106,0.30)",
    marginBottom: 12,
  },
  deniedIcon: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(232,184,106,0.14)",
    marginTop: 1,
  },
  deniedText: {
    flex: 1,
    color: "rgba(240,237,228,0.85)",
    fontSize: 13,
    lineHeight: 18,
    fontFamily: "Inter_400Regular",
  },

  // Back button
  backBtn: {
    position: "absolute",
    left: 12,
    zIndex: 10,
    padding: 10,
  },

  // Dots
  dots: {
    flexDirection: "row",
    gap: 6,
    alignItems: "center",
    marginTop: 20,
  },
  dot: { height: 8, borderRadius: 4 },

  // Madhab cards
  madhabRow: {
    flexDirection: "row",
    gap: 12,
    width: "100%",
    marginTop: 20,
  },
  madhabCard: {
    flex: 1,
    borderRadius: 16,
    borderWidth: 1.5,
    padding: 16,
    alignItems: "center",
    position: "relative",
    gap: 3,
  },
  madhabCheck: {
    position: "absolute",
    top: 10,
    right: 10,
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: GOLD,
    backgroundColor: GOLD + "18",
    alignItems: "center",
    justifyContent: "center",
  },
  madhabAutoBadge: {
    position: "absolute",
    top: 8,
    left: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    paddingLeft: 5,
    paddingRight: 6,
    paddingVertical: 2,
    borderRadius: 6,
    backgroundColor: GOLD + "1F",
    borderWidth: 1,
    borderColor: GOLD + "55",
  },
  madhabAutoBadgeText: {
    color: GOLD,
    fontSize: 9,
    fontFamily: "Inter_700Bold",
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  madhabDetectedPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    alignSelf: "flex-start",
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 8,
    backgroundColor: GOLD + "10",
    borderWidth: 1,
    borderColor: GOLD + "33",
    marginBottom: 10,
  },
  madhabDetectedText: {
    fontSize: 11,
    fontFamily: "Inter_400Regular",
    color: "rgba(240,237,228,0.85)",
    letterSpacing: 0.2,
  },
  madhabDetectedCity: {
    color: GOLD,
    fontFamily: "Inter_600SemiBold",
  },
  madhabHint: {
    marginTop: 12,
    fontSize: 12,
    fontFamily: "Inter_400Regular",
    color: TEXT_DIM,
    lineHeight: 17,
  },
  madhabAr: { fontSize: 22, fontFamily: "Inter_700Bold" },
  madhabEn: { fontSize: 14, fontFamily: "Inter_600SemiBold" },
  madhabDivider: { width: 24, height: 1, backgroundColor: GOLD + "30", marginVertical: 6 },
  madhabDesc: { fontSize: 11, fontFamily: "Inter_400Regular", textAlign: "center" },
  madhabTiming: { fontSize: 12, fontFamily: "Inter_600SemiBold", marginTop: 2 },

  // Section label above pickers
  sectionLabel: {
    alignSelf: "flex-start",
    fontSize: 11,
    fontFamily: "Inter_600SemiBold",
    color: TEXT_DIM,
    letterSpacing: 1.2,
    textTransform: "uppercase",
    marginBottom: 8,
  },

  // Calc method picker row (closed state)
  methodPickerRow: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 14,
    backgroundColor: SURFACE,
    borderWidth: 1,
    borderColor: BORDER_DIM,
  },
  methodPickerLabelRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  methodPickerName: { color: TEXT, fontSize: 15, fontFamily: "Inter_600SemiBold" },
  methodPickerRegion: { color: TEXT_DIM, fontSize: 12, fontFamily: "Inter_400Regular", marginTop: 2 },
  autoBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
    backgroundColor: GOLD + "1A",
    borderWidth: 1,
    borderColor: GOLD + "55",
  },
  autoBadgeText: {
    color: GOLD,
    fontSize: 9,
    fontFamily: "Inter_700Bold",
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },

  // Bottom sheet
  sheetBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.55)",
  },
  sheet: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "#121C16",
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    borderTopWidth: 1,
    borderColor: GOLD + "55",
    paddingHorizontal: 18,
    paddingTop: 10,
  },
  sheetHandle: {
    alignSelf: "center",
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: GOLD + "44",
    marginBottom: 10,
  },
  sheetHeader: { flexDirection: "row", alignItems: "center", paddingVertical: 6 },
  sheetTitle: { color: TEXT, fontSize: 17, fontFamily: "Inter_700Bold" },
  sheetSub: { color: GOLD, fontSize: 12, fontFamily: "Inter_400Regular", marginTop: 2 },
  sheetClose: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: GOLD + "55",
    alignItems: "center",
    justifyContent: "center",
  },
  sheetRule: { height: 1, backgroundColor: GOLD + "33", marginVertical: 10 },
  methodRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 14,
    paddingHorizontal: 6,
    borderBottomWidth: 1,
    borderBottomColor: GOLD + "1A",
  },
  methodName: { fontSize: 15, fontFamily: "Inter_600SemiBold" },
  methodRegion: { color: TEXT_DIM, fontSize: 12, fontFamily: "Inter_400Regular", marginTop: 2 },
  methodDetail: { color: TEXT_DIM, fontSize: 11, fontFamily: "Inter_400Regular", marginTop: 1 },
  methodCheck: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: GOLD,
    backgroundColor: GOLD + "1A",
    alignItems: "center",
    justifyContent: "center",
  },
  methodRadio: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: GOLD + "44",
  },
});
