export interface DuaItem {
  id: string;
  title: string;
  arabic: string;
  transliteration: string;
  translation: string;
  reference?: string;
  repeat?: string;
  virtue?: string;
}

export interface DuaCategoryData {
  id: string;
  name: string;
  icon: string;
  accentColor: string;
  duas: DuaItem[];
}

export const ALL_DUA_CATEGORIES: DuaCategoryData[] = [
  {
    id: "morning",
    name: "Morning Adhkar",
    icon: "sunrise",
    accentColor: "#F6C55A",
    duas: [
      {
        id: "m1",
        title: "Morning Remembrance",
        arabic: "أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لاَ إِلَهَ إِلاَّ اللهُ وَحْدَهُ لاَ شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ",
        transliteration: "Asbahna wa asbahal mulku lillah, walhamdu lillah, la ilaha illallahu wahdahu la shareeka lah, lahul mulku wa lahul hamdu wa huwa 'ala kulli shay'in qadeer",
        translation: "We have entered the morning and the kingdom belongs to Allah. All praise is for Allah. None has the right to be worshipped except Allah, alone, without partner. To Him belongs dominion and praise, and He is over all things capable.",
        reference: "Abu Dawud 4:317",
      },
      {
        id: "m2",
        title: "Entering the Morning",
        arabic: "اللَّهُمَّ بِكَ أَصْبَحْنَا، وَبِكَ أَمْسَيْنَا، وَبِكَ نَحْيَا، وَبِكَ نَمُوتُ وَإِلَيْكَ النُّشُورُ",
        transliteration: "Allahumma bika asbahna, wa bika amsayna, wa bika nahya, wa bika namootu wa ilaykan-nushoor",
        translation: "O Allah, by Your leave we have reached the morning and by Your leave we have reached the evening, by Your leave we live and die, and unto You is our resurrection.",
        reference: "At-Tirmidhi 3391",
      },
      {
        id: "m3",
        title: "Ayat al-Kursi",
        arabic: "اللَّهُ لَا إِلَهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَّهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ",
        transliteration: "Allahu la ilaha illa huwal-hayyul-qayyum, la ta'khudhuhu sinatun wa la nawm, lahu ma fis-samawati wa ma fil-ard",
        translation: "Allah! There is no deity except Him, the Ever-Living, the Sustainer of existence. Neither drowsiness overtakes Him nor sleep. To Him belongs whatever is in the heavens and whatever is on the earth.",
        reference: "Al-Baqarah 2:255 — recite once every morning",
        virtue: "Whoever recites it every morning is protected from jinn until evening.",
      },
      {
        id: "m4",
        title: "Protection from Harm (×3)",
        arabic: "بِسْمِ اللهِ الَّذِي لاَ يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الأَرْضِ وَلاَ فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ",
        transliteration: "Bismillahil-ladhi la yadurru ma'asmihi shay'un fil-ardi wa la fis-sama'i wa huwas-sami'ul-'aleem",
        translation: "In the name of Allah with whose name nothing is harmed on earth nor in the heavens, and He is the All-Hearing, the All-Knowing.",
        reference: "Abu Dawud 5088",
        repeat: "3×",
        virtue: "Nothing will harm the one who says this three times morning and evening.",
      },
      {
        id: "m5",
        title: "Sayyid al-Istighfar",
        arabic: "اللَّهُمَّ أَنْتَ رَبِّي لاَ إِلَهَ إِلاَّ أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لاَ يَغْفِرُ الذُّنُوبَ إِلاَّ أَنْتَ",
        transliteration: "Allahumma anta rabbi la ilaha illa anta, khalaqtani wa ana 'abduk, wa ana 'ala 'ahdika wa wa'dika mastata't, a'udhu bika min sharri ma sana't, abu'u laka bini'matika 'alayya wa abu'u bidhanbi faghfir li fa'innahu la yaghfirudh-dhunuba illa ant",
        translation: "O Allah, You are my Lord. There is no deity except You. You created me and I am Your servant, and I adhere to Your covenant and Your promise as best as I can. I seek refuge in You from the evil that I have done. I acknowledge Your favor upon me, and I acknowledge my sin, so forgive me, for none forgives sins but You.",
        reference: "Al-Bukhari 6306",
        virtue: "The Master of Seeking Forgiveness. Whoever says it with certainty in the morning and dies that day enters Paradise.",
      },
      {
        id: "m6",
        title: "Three Quls (×3)",
        arabic: "قُلْ هُوَ اللَّهُ أَحَدٌ ❋ قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ ❋ قُلْ أَعُوذُ بِرَبِّ النَّاسِ",
        transliteration: "Qul huwallahu ahad... Qul a'udhu birabbil-falaq... Qul a'udhu birabbin-nas...",
        translation: "Recite Surah Al-Ikhlas, Al-Falaq, and An-Nas — each three times in the morning and evening.",
        reference: "Abu Dawud 5082",
        repeat: "3× each",
        virtue: "Sufficient for everything.",
      },
      {
        id: "m7",
        title: "Morning Tasbih (×100)",
        arabic: "سُبْحَانَ اللهِ وَبِحَمْدِهِ",
        transliteration: "SubhanAllahi wa bihamdih",
        translation: "Glory be to Allah and His is the praise.",
        reference: "Muslim 2691",
        repeat: "100×",
        virtue: "Sins are forgiven even if they are like the foam of the sea.",
      },
      {
        id: "m8",
        title: "Well-being in Both Worlds",
        arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ الْعَافِيَةَ فِي الدُّنْيَا وَالآخِرَةِ",
        transliteration: "Allahumma inni as'alukal-'afiyata fid-dunya wal-akhirah",
        translation: "O Allah, I ask You for well-being in this world and in the Hereafter.",
        reference: "Ibn Majah 3871",
      },
      {
        id: "m9",
        title: "Dua for Good Character",
        arabic: "اللَّهُمَّ أَحْسَنْتَ خَلْقِي فَأَحْسِنْ خُلُقِي",
        transliteration: "Allahumma ahsanta khalqi fa-ahsin khuluqi",
        translation: "O Allah, just as You made my physical form beautiful, make my character beautiful too.",
        reference: "Ahmad 3748 — upon seeing oneself in the mirror",
      },
      {
        id: "m10",
        title: "Seeking Increase in Knowledge",
        arabic: "رَّبِّ زِدْنِي عِلْمًا",
        transliteration: "Rabbi zidni 'ilma",
        translation: "My Lord, increase me in knowledge.",
        reference: "Quran 20:114",
      },
      {
        id: "m11",
        title: "Morning Salawat",
        arabic: "اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ",
        transliteration: "Allahumma salli 'ala Muhammadin wa 'ala ali Muhammad",
        translation: "O Allah, send blessings upon Muhammad and upon the family of Muhammad.",
        reference: "Al-Bukhari 3190",
        repeat: "10×",
        virtue: "Whoever sends 10 blessings upon the Prophet ﷺ in the morning, Allah sends 100 mercies upon him.",
      },
      {
        id: "m12",
        title: "Protection for the Day",
        arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ عِلْمًا نَافِعًا، وَرِزْقًا طَيِّبًا، وَعَمَلاً مُتَقَبَّلاً",
        transliteration: "Allahumma inni as'aluka 'ilman nafi'an, wa rizqan tayyiban, wa 'amalan mutaqabbala",
        translation: "O Allah, I ask You for beneficial knowledge, good provision, and accepted deeds.",
        reference: "Ibn Majah 925",
      },
    ],
  },

  {
    id: "evening",
    name: "Evening Adhkar",
    icon: "moon",
    accentColor: "#7986CB",
    duas: [
      {
        id: "e1",
        title: "Evening Remembrance",
        arabic: "أَمْسَيْنَا وَأَمْسَى الْمُلْكُ للهِ، وَالْحَمْدُ للهِ، لَا إِلَهَ إِلَّا اللهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ",
        transliteration: "Amsayna wa amsal mulku lillah, walhamdu lillah, la ilaha illallahu wahdahu la shareeka lah, lahul mulku wa lahul hamdu wa huwa 'ala kulli shay'in qadeer",
        translation: "We have entered the evening and the kingdom belongs to Allah. All praise is for Allah. None has the right to be worshipped except Allah, alone, without partner. To Him belongs dominion and praise, and He is over all things capable.",
        reference: "Abu Dawud 4:317",
      },
      {
        id: "e2",
        title: "Sayyid al-Istighfar (Evening)",
        arabic: "اللَّهُمَّ أَنْتَ رَبِّي لاَ إِلَهَ إِلاَّ أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ",
        transliteration: "Allahumma anta rabbi la ilaha illa anta, khalaqtani wa ana 'abduk, wa ana 'ala 'ahdika wa wa'dika mastata't",
        translation: "O Allah, You are my Lord, none has the right to be worshipped except You. You created me and I am Your servant, and I am upon Your covenant and promise to the best of my ability.",
        reference: "Al-Bukhari 8:318",
        virtue: "Whoever says this at night with certainty and dies that night, enters Paradise.",
      },
      {
        id: "e3",
        title: "Protection at Evening (×3)",
        arabic: "أَعُوذُ بِكَلِمَاتِ اللهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ",
        transliteration: "A'udhu bikalimatillahit-tammati min sharri ma khalaq",
        translation: "I seek refuge in the perfect words of Allah from the evil of what He has created.",
        reference: "Muslim 2709",
        repeat: "3×",
        virtue: "No harm will befall the one who says this in the evening.",
      },
      {
        id: "e4",
        title: "Evening Protection (×3)",
        arabic: "بِسْمِ اللهِ الَّذِي لاَ يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الأَرْضِ وَلاَ فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ",
        transliteration: "Bismillahil-ladhi la yadurru ma'asmihi shay'un fil-ardi wa la fis-sama'i wa huwas-sami'ul-'aleem",
        translation: "In the name of Allah with whose name nothing is harmed on earth nor in the heavens, and He is the All-Hearing, the All-Knowing.",
        reference: "Abu Dawud 5088",
        repeat: "3×",
      },
      {
        id: "e5",
        title: "Before Sleep",
        arabic: "بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا",
        transliteration: "Bismika Allahumma amutu wa ahya",
        translation: "In Your name O Allah, I die and I live.",
        reference: "Al-Bukhari 11:113",
      },
      {
        id: "e6",
        title: "Three Quls (×3)",
        arabic: "قُلْ هُوَ اللَّهُ أَحَدٌ ❋ قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ ❋ قُلْ أَعُوذُ بِرَبِّ النَّاسِ",
        transliteration: "Qul huwallahu ahad... Qul a'udhu birabbil-falaq... Qul a'udhu birabbin-nas...",
        translation: "Recite Surah Al-Ikhlas, Al-Falaq, and An-Nas — each three times in the morning and evening.",
        reference: "Abu Dawud 5082",
        repeat: "3× each",
      },
      {
        id: "e7",
        title: "Before Sleep — Protection from Punishment",
        arabic: "اللَّهُمَّ قِنِي عَذَابَكَ يَوْمَ تَبْعَثُ عِبَادَكَ",
        transliteration: "Allahumma qini 'adhabaka yawma tab'athu 'ibadak",
        translation: "O Allah, protect me from Your punishment on the Day You resurrect Your servants.",
        reference: "Abu Dawud 5045",
        repeat: "3×",
      },
      {
        id: "e8",
        title: "Tasbih before Sleep",
        arabic: "سُبْحَانَ اللهِ ❋ الْحَمْدُ للهِ ❋ اللهُ أَكْبَرُ",
        transliteration: "SubhanAllah (33×) · Alhamdulillah (33×) · Allahu Akbar (34×)",
        translation: "Glory be to Allah (33×) · All praise is for Allah (33×) · Allah is the Greatest (34×) — recite before sleep.",
        reference: "Al-Bukhari 3113",
        virtue: "Better than a servant for household work.",
      },
      {
        id: "e9",
        title: "Ayat al-Kursi Before Sleep",
        arabic: "اللَّهُ لَا إِلَهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ",
        transliteration: "Allahu la ilaha illa huwal-hayyul-qayyum, la ta'khudhuhu sinatun wa la nawm",
        translation: "Allah! There is no deity except Him, the Ever-Living, the Sustainer of existence. Neither drowsiness overtakes Him nor sleep.",
        reference: "Al-Baqarah 2:255 — recite before sleep",
        virtue: "A guardian from Allah remains over you and Shaytan does not come near you until morning.",
      },
      {
        id: "e10",
        title: "Upon Waking at Night",
        arabic: "لاَ إِلَهَ إِلاَّ اللهُ وَحْدَهُ لاَ شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ، وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ، سُبْحَانَ اللهِ وَالْحَمْدُ لِلهِ، وَلاَ إِلَهَ إِلاَّ اللهُ وَاللهُ أَكْبَرُ",
        transliteration: "La ilaha illallahu wahdahu la shareeka lah, lahul mulku wa lahul hamdu, wa huwa 'ala kulli shay'in qadeer, SubhanAllahi walhamdulillahi wa la ilaha illallahu wallahu akbar",
        translation: "None has the right to be worshipped except Allah alone, with no partner. His is the dominion and His is all praise, and He is over all things capable. Glory be to Allah, all praise is for Allah, none has the right to be worshipped except Allah, and Allah is the Greatest.",
        reference: "Al-Bukhari 1154",
        virtue: "If one then makes dua, it will be answered, and if one performs wudu and prays, the prayer will be accepted.",
      },
      {
        id: "e11",
        title: "Evening Salawat (×10)",
        arabic: "اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَعَلَى آلِ مُحَمَّدٍ",
        transliteration: "Allahumma salli 'ala Muhammadin wa 'ala ali Muhammad",
        translation: "O Allah, send blessings upon Muhammad and upon the family of Muhammad.",
        reference: "At-Tirmidhi 484",
        repeat: "10×",
        virtue: "Whoever sends 10 blessings on the Prophet ﷺ in the evening, Allah sends 100 mercies upon him.",
      },
      {
        id: "e12",
        title: "Last Two Verses of Al-Baqarah",
        arabic: "آمَنَ الرَّسُولُ بِمَا أُنزِلَ إِلَيْهِ مِن رَّبِّهِ وَالْمُؤْمِنُونَ ۚ كُلٌّ آمَنَ بِاللَّهِ وَمَلَائِكَتِهِ وَكُتُبِهِ وَرُسُلِهِ",
        transliteration: "Amanar-rasulu bima unzila ilayhi mir-rabbihi wal-mu'minun, kullun amana billahi wa mala'ikatihi wa kutubihi wa rusulih",
        translation: "The Messenger has believed in what was revealed to him from his Lord, and so have the believers. All of them have believed in Allah and His angels and His books and His messengers...",
        reference: "Al-Baqarah 2:285-286 — recite before sleep",
        virtue: "These two verses are sufficient for the one who recites them at night.",
      },
    ],
  },

  {
    id: "prayer",
    name: "After Prayer",
    icon: "star",
    accentColor: "#4DB6AC",
    duas: [
      {
        id: "p1",
        title: "Post-Salah Tasbih",
        arabic: "سُبْحَانَ اللهِ ❋ الْحَمْدُ للهِ ❋ اللهُ أَكْبَرُ",
        transliteration: "SubhanAllah (33×) • Alhamdulillah (33×) • Allahu Akbar (34×)",
        translation: "Glory be to Allah (33 times) • All praise is for Allah (33 times) • Allah is the Greatest (34 times — completing 100)",
        reference: "Muslim 939",
        virtue: "Sins are forgiven even if they are like the foam of the sea.",
      },
      {
        id: "p2",
        title: "Ayat al-Kursi After Prayer",
        arabic: "اللَّهُ لَا إِلَهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ",
        transliteration: "Allahu la ilaha illa huwal-hayyul-qayyum, la ta'khudhuhu sinatun wa la nawm",
        translation: "Allah! There is no deity except Him, the Ever-Living, the Sustainer of existence. Neither drowsiness overtakes Him nor sleep.",
        reference: "Al-Baqarah 2:255",
        virtue: "Whoever recites it after every prayer, only death separates him from Paradise.",
      },
      {
        id: "p3",
        title: "Help for Remembrance & Gratitude",
        arabic: "اللَّهُمَّ أَعِنِّي عَلَى ذِكْرِكَ وَشُكْرِكَ وَحُسْنِ عِبَادَتِكَ",
        transliteration: "Allahumma a'inni 'ala dhikrika wa shukrika wa husni 'ibadatik",
        translation: "O Allah, help me to remember You, to give thanks to You, and to worship You in the best manner.",
        reference: "Abu Dawud 1522",
      },
      {
        id: "p4",
        title: "Seeking Refuge (After Fajr & Asr)",
        arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْجُبْنِ وَأَعُوذُ بِكَ مِنَ الْبُخْلِ وَأَعُوذُ بِكَ مِنْ أَرْذَلِ الْعُمُرِ وَأَعُوذُ بِكَ مِنْ فِتْنَةِ الدُّنْيَا وَعَذَابِ الْقَبْرِ",
        transliteration: "Allahumma inni a'udhu bika minal-jubni, wa a'udhu bika minal-bukhli, wa a'udhu bika min ardhilil-'umuri, wa a'udhu bika min fitnatid-dunya wa 'adhabil-qabr",
        translation: "O Allah, I seek refuge in You from cowardice, from miserliness, from the disgrace of old age, and from the trials of this world and the torment of the grave.",
        reference: "Al-Bukhari 6374",
      },
      {
        id: "p5",
        title: "Seeking Forgiveness After Prayer (×3)",
        arabic: "أَسْتَغْفِرُ اللهَ ❋ اللَّهُمَّ أَنْتَ السَّلاَمُ وَمِنْكَ السَّلاَمُ، تَبَارَكْتَ يَا ذَا الْجَلاَلِ وَالإِكْرَامِ",
        transliteration: "Astaghfirullah (3×) • Allahumma antas-salam wa minkas-salam, tabarakta ya dhal-jalali wal-ikram",
        translation: "I seek forgiveness from Allah (3 times) • O Allah, You are As-Salam and from You is peace. Blessed are You, O Possessor of majesty and honour.",
        reference: "Muslim 591",
        repeat: "3× Istighfar then the extended dua",
      },
      {
        id: "p6",
        title: "La ilaha illallah (×10 — Fajr & Maghrib)",
        arabic: "لاَ إِلَهَ إِلاَّ اللهُ وَحْدَهُ لاَ شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ",
        transliteration: "La ilaha illallahu wahdahu la shareeka lah, lahul mulku wa lahul hamdu wa huwa 'ala kulli shay'in qadeer",
        translation: "None has the right to be worshipped except Allah, alone, without partner. To Him belongs dominion and praise, and He is over all things capable.",
        reference: "Muslim 597",
        repeat: "10×",
        virtue: "Equivalent to freeing 10 slaves, earning 100 good deeds, and 100 bad deeds are erased.",
      },
      {
        id: "p7",
        title: "Al-Mu'awwidhatayn After Prayer",
        arabic: "قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ ❋ قُلْ أَعُوذُ بِرَبِّ النَّاسِ",
        transliteration: "Qul a'udhu birabbil-falaq... Qul a'udhu birabbin-nas...",
        translation: "Recite Surah Al-Falaq and Surah An-Nas after every prayer.",
        reference: "An-Nasa'i 1336",
      },
      {
        id: "p8",
        title: "Goodness in Both Worlds",
        arabic: "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ",
        transliteration: "Rabbana atina fid-dunya hasanatan wa fil-akhirati hasanatan wa qina 'adhaban-nar",
        translation: "Our Lord, give us good in this world and good in the Hereafter, and save us from the punishment of the Fire.",
        reference: "Quran 2:201",
        virtue: "The Prophet ﷺ would frequently make this dua.",
      },
      {
        id: "p9",
        title: "Between Adhan & Iqamah",
        arabic: "اللَّهُمَّ رَبَّ هَذِهِ الدَّعْوَةِ التَّامَّةِ وَالصَّلاَةِ الْقَائِمَةِ، آتِ مُحَمَّدًا الْوَسِيلَةَ وَالْفَضِيلَةَ",
        transliteration: "Allahumma rabba hadhihi-d-da'watit-tammah was-salatil-qa'imah, ati Muhammadan al-wasilata wal-fadilah",
        translation: "O Allah, Lord of this complete call and of the prayer to be established, grant Muhammad the intercession and the favoured position.",
        reference: "Al-Bukhari 614",
        virtue: "Intercession of the Prophet ﷺ is guaranteed for whoever says this.",
      },
      {
        id: "p10",
        title: "Dua After Fajr for Well-being",
        arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ عِلْمًا نَافِعًا، وَرِزْقًا طَيِّبًا، وَعَمَلاً مُتَقَبَّلاً",
        transliteration: "Allahumma inni as'aluka 'ilman nafi'an, wa rizqan tayyiban, wa 'amalan mutaqabbala",
        translation: "O Allah, I ask You for beneficial knowledge, goodly provision, and accepted deeds.",
        reference: "Ibn Majah 925",
      },
    ],
  },

  {
    id: "fasting",
    name: "Ramadan & Fasting",
    icon: "moon",
    accentColor: "#81C784",
    duas: [
      {
        id: "f1",
        title: "Dua for Breaking the Fast (Iftar)",
        arabic: "اللَّهُمَّ لَكَ صُمْتُ وَعَلَى رِزْقِكَ أَفْطَرْتُ",
        transliteration: "Allahumma laka sumtu wa 'ala rizqika aftartu",
        translation: "O Allah, for You I fasted and upon Your provision I break my fast.",
        reference: "Abu Dawud 2358",
      },
      {
        id: "f2",
        title: "Iftar Dua — Thirst Gone",
        arabic: "ذَهَبَ الظَّمَأُ وَابْتَلَّتِ الْعُرُوقُ وَثَبَتَ الْأَجْرُ إِنْ شَاءَ اللَّهُ",
        transliteration: "Dhahaba az-zama'u wabtallatil-'uruqu wa thabatal-ajru in sha'Allah",
        translation: "The thirst has gone, the veins are quenched, and the reward is confirmed, if Allah wills.",
        reference: "Abu Dawud 2357",
        virtue: "This is what the Prophet ﷺ would say when breaking his fast.",
      },
      {
        id: "f3",
        title: "Niyyah for Fasting (Suhoor intention)",
        arabic: "وَبِصَوْمِ غَدٍ نَّوَيْتُ مِنْ شَهْرِ رَمَضَانَ",
        transliteration: "Wa bisawmi ghadin nawaytu min shahri Ramadan",
        translation: "I intend to keep the fast tomorrow in the month of Ramadan.",
        reference: "Scholars' consensus",
        virtue: "Make this intention at suhoor time before Fajr.",
      },
      {
        id: "f4",
        title: "Dua for Laylatul Qadr",
        arabic: "اللَّهُمَّ إِنَّكَ عَفُوٌّ تُحِبُّ الْعَفْوَ فَاعْفُ عَنِّي",
        transliteration: "Allahumma innaka 'afuwwun tuhibbul-'afwa fa'fu 'anni",
        translation: "O Allah, You are the Pardoner. You love to pardon, so pardon me.",
        reference: "At-Tirmidhi 3513 — taught by the Prophet ﷺ to Aisha specifically for Laylatul Qadr",
        virtue: "The best dua for the Night of Power, as taught by the Prophet ﷺ himself.",
      },
      {
        id: "f5",
        title: "Seeing the Ramadan Moon",
        arabic: "اللهُ أَكْبَرُ، اللَّهُمَّ أَهِلَّهُ عَلَيْنَا بِالأَمْنِ وَالإِيمَانِ، وَالسَّلاَمَةِ وَالإِسْلاَمِ، رَبِّي وَرَبُّكَ اللهُ",
        transliteration: "Allahu Akbar, Allahumma ahillahu 'alayna bil-amni wal-iman, was-salamati wal-islam, rabbi wa rabbukallah",
        translation: "Allah is the Greatest. O Allah, let this moon appear over us with security, faith, safety, and Islam. My Lord and your Lord is Allah.",
        reference: "At-Tirmidhi 3451",
      },
      {
        id: "f6",
        title: "When Someone Invites You to Eat While Fasting",
        arabic: "إِنِّي صَائِمٌ",
        transliteration: "Inni sa'im",
        translation: "I am fasting.",
        reference: "Al-Bukhari 1904 — say this when invited to eat while fasting, not as a boast but as polite decline",
      },
      {
        id: "f7",
        title: "Dua for Forgiveness in Ramadan",
        arabic: "اللَّهُمَّ اغْفِرْ لِي وَارْحَمْنِي وَاهْدِنِي وَعَافِنِي وَارْزُقْنِي",
        transliteration: "Allahummaghfir li warhamni wahdinee wa 'afini warzuqni",
        translation: "O Allah, forgive me, have mercy on me, guide me, grant me well-being, and provide for me.",
        reference: "Muslim 2696",
      },
      {
        id: "f8",
        title: "Dua of the Fasting Person That Is Not Rejected",
        arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ بِرَحْمَتِكَ الَّتِي وَسِعَتْ كُلَّ شَيْءٍ أَنْ تَغْفِرَ لِي",
        transliteration: "Allahumma inni as'aluka birahmatika allati wasi'at kulla shay'in an taghfira li",
        translation: "O Allah, I ask You by Your mercy which encompasses all things, that You forgive me.",
        reference: "Ibn Majah 1797",
        virtue: "The fasting person's dua at iftar is not rejected.",
      },
      {
        id: "f9",
        title: "Dua After Eating Suhoor",
        arabic: "اللَّهُمَّ بَارِكْ لَنَا فِيهِ وَأَطْعِمْنَا خَيْرًا مِنْهُ",
        transliteration: "Allahumma barik lana fihi wa at'imna khayran minh",
        translation: "O Allah, bless it for us and feed us something better than it.",
        reference: "At-Tirmidhi 3455",
      },
      {
        id: "f10",
        title: "Dua for the Last 10 Nights",
        arabic: "اللَّهُمَّ إِنَّكَ عَفُوٌّ كَرِيمٌ تُحِبُّ الْعَفْوَ فَاعْفُ عَنَّا",
        transliteration: "Allahumma innaka 'afuwwun karimun tuhibbul-'afwa fa'fu 'anna",
        translation: "O Allah, You are Pardoning, Generous, and You love to pardon — so pardon us.",
        reference: "Ibn Majah 3850",
        virtue: "Increase this dua in the last 10 nights of Ramadan.",
      },
    ],
  },

  {
    id: "daily",
    name: "Daily Life",
    icon: "heart",
    accentColor: "#E8A87C",
    duas: [
      {
        id: "d1",
        title: "Before Eating",
        arabic: "بِسْمِ اللهِ",
        transliteration: "Bismillah",
        translation: "In the name of Allah.",
        reference: "Al-Bukhari 5376 — say at the beginning of eating",
      },
      {
        id: "d2",
        title: "When Forgetting Bismillah While Eating",
        arabic: "بِسْمِ اللهِ أَوَّلَهُ وَآخِرَهُ",
        transliteration: "Bismillahi awwalahu wa akhirah",
        translation: "In the name of Allah at its beginning and its end.",
        reference: "Abu Dawud 3767",
      },
      {
        id: "d3",
        title: "After Eating",
        arabic: "الْحَمْدُ لِلهِ الَّذِي أَطْعَمَنَا وَسَقَانَا وَجَعَلَنَا مُسْلِمِينَ",
        transliteration: "Alhamdu lillahil-ladhi at'amana wa saqana wa ja'alana muslimeen",
        translation: "All praise is for Allah who fed us and gave us drink and made us Muslims.",
        reference: "Abu Dawud 3850",
      },
      {
        id: "d4",
        title: "Entering the Home",
        arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ خَيْرَ الْمَوْلَجِ وَخَيْرَ الْمَخْرَجِ، بِسْمِ اللهِ وَلَجْنَا وَبِسْمِ اللهِ خَرَجْنَا وَعَلَى اللهِ رَبِّنَا تَوَكَّلْنَا",
        transliteration: "Allahumma inni as'aluka khayral mawlaji wa khayral makhraj, bismillahi walajna wa bismillahi kharajna wa 'alallahi rabbina tawakkalna",
        translation: "O Allah, I ask You for a good entry and a good exit. In the name of Allah we enter, in the name of Allah we leave, and upon Allah our Lord we rely.",
        reference: "Abu Dawud 5096",
      },
      {
        id: "d5",
        title: "Entering the Masjid",
        arabic: "اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ",
        transliteration: "Allahumma iftah li abwaba rahmatik",
        translation: "O Allah, open the gates of Your mercy for me.",
        reference: "Muslim 713",
      },
      {
        id: "d6",
        title: "Leaving the Masjid",
        arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنْ فَضْلِكَ",
        transliteration: "Allahumma inni as'aluka min fadlik",
        translation: "O Allah, I ask You for Your bounty.",
        reference: "Muslim 713",
      },
      {
        id: "d7",
        title: "When Leaving Home",
        arabic: "بِسْمِ اللهِ، تَوَكَّلْتُ عَلَى اللهِ، وَلاَ حَوْلَ وَلاَ قُوَّةَ إِلاَّ بِاللهِ",
        transliteration: "Bismillah, tawakkaltu 'alallah, wa la hawla wa la quwwata illa billah",
        translation: "In the name of Allah, I put my trust in Allah. There is no power and no strength except with Allah.",
        reference: "At-Tirmidhi 3426",
        virtue: "One who says this is guided, protected, and sufficed, and the Shaytan moves away from him.",
      },
      {
        id: "d8",
        title: "Before Wudu",
        arabic: "بِسْمِ اللهِ",
        transliteration: "Bismillah",
        translation: "In the name of Allah — say before beginning ablution.",
        reference: "Abu Dawud 101",
      },
      {
        id: "d9",
        title: "After Completing Wudu",
        arabic: "أَشْهَدُ أَنْ لاَ إِلَهَ إِلاَّ اللهُ وَحْدَهُ لاَ شَرِيكَ لَهُ وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ",
        transliteration: "Ash-hadu an la ilaha illallahu wahdahu la shareeka lahu wa ash-hadu anna Muhammadan 'abduhu wa rasuluh",
        translation: "I bear witness that none has the right to be worshipped except Allah alone, without partner, and I bear witness that Muhammad is His servant and messenger.",
        reference: "Muslim 234",
        virtue: "The eight gates of Paradise are opened for him — he may enter through any of them.",
      },
      {
        id: "d10",
        title: "Entering the Bathroom",
        arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْخُبُثِ وَالْخَبَائِثِ",
        transliteration: "Allahumma inni a'udhu bika minal-khubuthi wal-khaba'ith",
        translation: "O Allah, I seek refuge in You from male and female evil spirits.",
        reference: "Al-Bukhari 142",
        virtue: "Provides protection from jinn in the bathroom.",
      },
      {
        id: "d11",
        title: "Leaving the Bathroom",
        arabic: "غُفْرَانَكَ",
        transliteration: "Ghufranaka",
        translation: "I seek Your forgiveness.",
        reference: "Abu Dawud 30 — At-Tirmidhi 7",
      },
      {
        id: "d12",
        title: "When Sneezing",
        arabic: "الْحَمْدُ لِلهِ",
        transliteration: "Alhamdulillah",
        translation: "All praise is for Allah.",
        reference: "Al-Bukhari 6224 — respond with Yarhamukallah (May Allah have mercy on you)",
      },
      {
        id: "d13",
        title: "Entering the Marketplace",
        arabic: "لاَ إِلَهَ إِلاَّ اللهُ وَحْدَهُ لاَ شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ يُحْيِي وَيُمِيتُ وَهُوَ حَيٌّ لاَ يَمُوتُ، بِيَدِهِ الْخَيْرُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ",
        transliteration: "La ilaha illallahu wahdahu la shareeka lah, lahul mulku wa lahul hamdu yuhyi wa yumitu wa huwa hayyun la yamut, biyadihil khayr wa huwa 'ala kulli shay'in qadeer",
        translation: "None has the right to be worshipped except Allah, alone, without partner. His is the dominion, His is all praise. He gives life and causes death, He is Ever-Living and does not die. In His Hand is all good, and He is over all things capable.",
        reference: "At-Tirmidhi 3428",
        virtue: "Allah writes one million good deeds for him, erases one million bad deeds, and raises him one million ranks.",
      },
      {
        id: "d14",
        title: "When it Rains",
        arabic: "اللَّهُمَّ صَيِّبًا نَافِعًا",
        transliteration: "Allahumma sayyiban nafi'an",
        translation: "O Allah, (make it) a beneficial rain.",
        reference: "Al-Bukhari 1032",
      },
      {
        id: "d15",
        title: "Dua for Parents",
        arabic: "رَّبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا",
        transliteration: "Rabbi irhamhuma kama rabbayani sagheera",
        translation: "My Lord, have mercy upon them as they raised me when I was small.",
        reference: "Quran 17:24",
      },
      {
        id: "d16",
        title: "When Hearing Good News",
        arabic: "الْحَمْدُ لِلهِ الَّذِي بِنِعْمَتِهِ تَتِمُّ الصَّالِحَاتُ",
        transliteration: "Alhamdu lillahil-ladhi bini'matihi tatimmus-salihat",
        translation: "All praise is for Allah by whose grace good deeds are completed.",
        reference: "Ibn Majah 3803",
      },
    ],
  },

  {
    id: "forgiveness",
    name: "Forgiveness & Tawbah",
    icon: "refresh-cw",
    accentColor: "#64B5F6",
    duas: [
      {
        id: "fg1",
        title: "Sayyid al-Istighfar — Master Forgiveness",
        arabic: "اللَّهُمَّ أَنْتَ رَبِّي لاَ إِلَهَ إِلاَّ أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ وَأَبُوءُ بِذَنْبِي فَاغْفِرْ لِي فَإِنَّهُ لاَ يَغْفِرُ الذُّنُوبَ إِلاَّ أَنْتَ",
        transliteration: "Allahumma anta rabbi la ilaha illa anta, khalaqtani wa ana 'abduk, wa ana 'ala 'ahdika wa wa'dika mastata't, a'udhu bika min sharri ma sana't, abu'u laka bini'matika 'alayya wa abu'u bidhanbi faghfir li fa'innahu la yaghfirudh-dhunuba illa ant",
        translation: "O Allah, You are my Lord. There is no deity except You. You created me and I am Your servant. I adhere to Your covenant and Your promise as best I can. I seek refuge in You from the evil I have done. I acknowledge Your favour upon me, and I acknowledge my sin, so forgive me — for none forgives sins but You.",
        reference: "Al-Bukhari 6306",
        virtue: "The Master of Seeking Forgiveness. Whoever says it with certainty in the morning and dies that day enters Paradise. Likewise for the evening.",
      },
      {
        id: "fg2",
        title: "Short Istighfar",
        arabic: "أَسْتَغْفِرُ اللهَ الْعَظِيمَ الَّذِي لاَ إِلَهَ إِلاَّ هُوَ الْحَيُّ الْقَيُّومُ وَأَتُوبُ إِلَيْهِ",
        transliteration: "Astaghfirullaahal-'Adheema alladhi la ilaha illa huwal-hayyul-qayyumu wa atubu ilayh",
        translation: "I seek forgiveness from Allah the Magnificent, besides Whom none has the right to be worshipped, the Ever-Living, the Sustainer of all existence, and I repent to Him.",
        reference: "At-Tirmidhi 3577",
        virtue: "Sins are forgiven even if they are like the foam of the sea.",
      },
      {
        id: "fg3",
        title: "Prophet's Daily Istighfar (×100)",
        arabic: "رَبِّ اغْفِرْ لِي وَتُبْ عَلَيَّ إِنَّكَ أَنْتَ التَّوَّابُ الرَّحِيمُ",
        transliteration: "Rabbighfir li wa tub 'alayya innaka antat-tawwabur-rahim",
        translation: "My Lord, forgive me and accept my repentance. Indeed, You are the Acceptor of repentance, the Most Merciful.",
        reference: "Al-Bukhari 6307 — Abu Dawud 1516",
        repeat: "100×",
        virtue: "The Prophet ﷺ would seek forgiveness 100 times a day even though his past and future sins were forgiven.",
      },
      {
        id: "fg4",
        title: "Dua for Tawbah (Repentance)",
        arabic: "اللَّهُمَّ اغْفِرْ لِي ذَنْبِي كُلَّهُ، دِقَّهُ وَجِلَّهُ، وَأَوَّلَهُ وَآخِرَهُ، وَعَلاَنِيَتَهُ وَسِرَّهُ",
        transliteration: "Allahummaghfir li dhanbi kullahu, diqqahu wa jillahu, wa awwalahu wa akhirah, wa 'alaniyyatahu wa sirrah",
        translation: "O Allah, forgive me all my sin: the small and the great, the first and the last, the open and the secret.",
        reference: "Muslim 483",
      },
      {
        id: "fg5",
        title: "Kaffarat al-Majlis — End of Gathering",
        arabic: "سُبْحَانَكَ اللَّهُمَّ وَبِحَمْدِكَ، أَشْهَدُ أَنْ لاَ إِلَهَ إِلاَّ أَنْتَ، أَسْتَغْفِرُكَ وَأَتُوبُ إِلَيْكَ",
        transliteration: "Subhanakallahumma wa bihamdik, ash-hadu an la ilaha illa ant, astaghfiruka wa atubu ilayk",
        translation: "Glory be to You O Allah and all praise, I bear witness that there is no deity except You. I seek Your forgiveness and I repent to You.",
        reference: "At-Tirmidhi 3433",
        virtue: "Expiation for what occurred in the gathering. The Prophet ﷺ would conclude every gathering with it.",
      },
      {
        id: "fg6",
        title: "SubhanAllah wa Bihamdih (×100)",
        arabic: "سُبْحَانَ اللهِ وَبِحَمْدِهِ",
        transliteration: "SubhanAllahi wa bihamdih",
        translation: "Glory be to Allah and His is the praise.",
        reference: "Muslim 2692",
        repeat: "100×",
        virtue: "Sins are forgiven even if they are like the foam of the sea.",
      },
      {
        id: "fg7",
        title: "The Best Dua for Forgiveness",
        arabic: "اللَّهُمَّ إِنِّي ظَلَمْتُ نَفْسِي ظُلْمًا كَثِيرًا، وَلاَ يَغْفِرُ الذُّنُوبَ إِلاَّ أَنْتَ، فَاغْفِرْ لِي مَغْفِرَةً مِنْ عِنْدِكَ وَارْحَمْنِي، إِنَّكَ أَنْتَ الْغَفُورُ الرَّحِيمُ",
        transliteration: "Allahumma inni zalamtu nafsi zulman kathira, wa la yaghfirudh-dhunuba illa ant, faghfir li maghfiratan min 'indika warhamni, innaka antal-ghafurur-rahim",
        translation: "O Allah, I have greatly wronged myself and no one forgives sins but You. So grant me forgiveness from Yourself and have mercy on me. Surely, You are the Forgiving, the Merciful.",
        reference: "Al-Bukhari 834 — Abu Dawud 1485",
      },
      {
        id: "fg8",
        title: "Dua for a Pure Heart",
        arabic: "اللَّهُمَّ طَهِّرْ قَلْبِي مِنَ النِّفَاقِ، وَعَمَلِي مِنَ الرِّيَاءِ، وَلِسَانِي مِنَ الْكَذِبِ، وَعَيْنِي مِنَ الْخِيَانَةِ",
        transliteration: "Allahumma tahhir qalbi mina-nifaq, wa 'amali minar-riya', wa lisani minal-kadhib, wa 'ayni minal-khiyanah",
        translation: "O Allah, purify my heart from hypocrisy, my deeds from showing off, my tongue from lying, and my eyes from treachery.",
        reference: "Compiled from Sunnah",
      },
    ],
  },

  {
    id: "hardship",
    name: "Hardship & Anxiety",
    icon: "shield",
    accentColor: "#EF9A9A",
    duas: [
      {
        id: "h1",
        title: "Relief from Anxiety & Sorrow",
        arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ، وَالْعَجْزِ وَالْكَسَلِ، وَالْبُخْلِ وَالْجُبْنِ، وَضَلَعِ الدَّيْنِ وَغَلَبَةِ الرِّجَالِ",
        transliteration: "Allahumma inni a'udhu bika minal-hammi wal-hazani, wal-'ajzi wal-kasali, wal-bukhli wal-jubni, wa dhala'id-dayni wa ghalabatir-rijal",
        translation: "O Allah, I seek refuge in You from worry and grief, from helplessness and laziness, from miserliness and cowardice, and from the burden of debts and from being overpowered by men.",
        reference: "Al-Bukhari 7:158",
      },
      {
        id: "h2",
        title: "Dua of Prophet Yunus (Distress)",
        arabic: "لَّا إِلَٰهَ إِلَّا أَنتَ سُبْحَانَكَ إِنِّي كُنتُ مِنَ الظَّالِمِينَ",
        transliteration: "La ilaha illa anta subhanaka inni kuntu minaz-zalimin",
        translation: "There is no deity except You; exalted are You. Indeed, I have been of the wrongdoers.",
        reference: "Quran 21:87",
        virtue: "No Muslim who is in distress calls upon Allah with this dua except that Allah relieves his distress.",
      },
      {
        id: "h3",
        title: "Allah is Sufficient for Me",
        arabic: "حَسْبِيَ اللهُ لاَ إِلَهَ إِلاَّ هُوَ عَلَيْهِ تَوَكَّلْتُ وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ",
        transliteration: "Hasbiyallahu la ilaha illa huwa 'alayhi tawakkaltu wa huwa rabbul-'arshil-'azim",
        translation: "Allah is sufficient for me. There is no deity except Him. I have put my trust in Him, and He is the Lord of the Magnificent Throne.",
        reference: "At-Tawbah 9:129",
        repeat: "7×",
        virtue: "Whoever recites this 7 times in the morning and evening, Allah will be sufficient for him in his worries.",
      },
      {
        id: "h4",
        title: "Dua for Relief from Debt",
        arabic: "اللَّهُمَّ اكْفِنِي بِحَلاَلِكَ عَنْ حَرَامِكَ، وَأَغْنِنِي بِفَضْلِكَ عَمَّنْ سِوَاكَ",
        transliteration: "Allahumma-kfini bihalaalika 'an haramika, wa aghnini bifadlika 'amman siwak",
        translation: "O Allah, suffice me with what You have made lawful, so that I have no need of what You have made unlawful, and enrich me by Your bounty so that I need no one but You.",
        reference: "At-Tirmidhi 3563",
        virtue: "Dua to relieve debt and financial hardship.",
      },
      {
        id: "h5",
        title: "When Afflicted by Calamity",
        arabic: "إِنَّا لِلهِ وَإِنَّا إِلَيْهِ رَاجِعُونَ، اللَّهُمَّ أْجُرْنِي فِي مُصِيبَتِي وَأَخْلِفْ لِي خَيْرًا مِنْهَا",
        transliteration: "Inna lillahi wa inna ilayhi raji'un, Allahumma ajurni fi musibati wa akhlif li khayran minha",
        translation: "Indeed, we belong to Allah and to Him we shall return. O Allah, reward me for my affliction and replace it with something better.",
        reference: "Muslim 918",
        virtue: "Allah will reward him for his affliction and replace it with something better.",
      },
      {
        id: "h6",
        title: "La hawla wa la quwwata",
        arabic: "لاَ حَوْلَ وَلاَ قُوَّةَ إِلاَّ بِاللهِ",
        transliteration: "La hawla wa la quwwata illa billah",
        translation: "There is no power and no strength except with Allah.",
        reference: "Al-Bukhari 4205",
        virtue: "A treasure from the treasures of Paradise.",
      },
      {
        id: "h7",
        title: "Protection from the Evil Eye",
        arabic: "أَعُوذُ بِكَلِمَاتِ اللهِ التَّامَّةِ مِنْ كُلِّ شَيْطَانٍ وَهَامَّةٍ وَمِنْ كُلِّ عَيْنٍ لاَمَّةٍ",
        transliteration: "A'udhu bikalimatillahit-tammati min kulli shaytanin wa hammatin wa min kulli 'aynin lammah",
        translation: "I seek refuge in the perfect words of Allah from every devil and every poisonous pest, and from every evil eye.",
        reference: "Al-Bukhari 3371",
        virtue: "As said by the Prophet ﷺ as a ruqyah for Hasan and Husain.",
      },
      {
        id: "h8",
        title: "Protection when Travelling",
        arabic: "اللَّهُمَّ إِنَّا نَسْأَلُكَ فِي سَفَرِنَا هَذَا الْبِرَّ وَالتَّقْوَى، وَمِنَ الْعَمَلِ مَا تَرْضَى",
        transliteration: "Allahumma inna nas'aluka fi safarina hadhal-birra wat-taqwa, wa minal-'amali ma tarda",
        translation: "O Allah, we ask You on this journey for righteousness and piety, and for deeds that are pleasing to You.",
        reference: "Muslim 1342",
      },
      {
        id: "h9",
        title: "Dua of Anxiety & Grief",
        arabic: "اللَّهُمَّ إِنِّي عَبْدُكَ وَابْنُ عَبْدِكَ وَابْنُ أَمَتِكَ، نَاصِيَتِي بِيَدِكَ، مَاضٍ فِيَّ حُكْمُكَ، عَدْلٌ فِيَّ قَضَاؤُكَ، أَسْأَلُكَ بِكُلِّ اسْمٍ هُوَ لَكَ سَمَّيْتَ بِهِ نَفْسَكَ، أَوْ عَلَّمْتَهُ أَحَدًا مِنْ خَلْقِكَ، أَنْ تَجْعَلَ الْقُرْآنَ رَبِيعَ قَلْبِي وَنُورَ صَدْرِي وَجَلاَءَ حُزْنِي وَذَهَابَ هَمِّي",
        transliteration: "Allahumma inni 'abduka wabnu 'abdika wabnu amatika, nasiyati biyadika, madin fiyya hukmuka, 'adlun fiyya qada'uka, as'aluka bikulli ismin huwa laka sammayta bihi nafsaka, aw 'allamtahu ahadan min khalqika, an taj'alal-Qur'ana rabi'a qalbi wa nura sadri wa jala'a huzni wa dhahaba hammi",
        translation: "O Allah, I am Your servant, son of Your servant, son of Your maidservant. My forelock is in Your Hand. Your command over me is forever executed and Your decree over me is just. I ask You by every name belonging to You which You named Yourself, or revealed in Your Book, to make the Quran the life of my heart and the light of my breast, and a departure for my sorrow and a release for my anxiety.",
        reference: "Ahmad 3528",
        virtue: "No Muslim is afflicted with anxiety or grief who says this except that Allah removes his sorrow and replaces his grief with joy.",
      },
      {
        id: "h10",
        title: "Upon Waking from a Nightmare",
        arabic: "أَعُوذُ بِكَلِمَاتِ اللهِ التَّامَّاتِ مِنْ غَضَبِهِ وَعِقَابِهِ وَشَرِّ عِبَادِهِ وَمِنْ هَمَزَاتِ الشَّيَاطِينِ وَأَنْ يَحْضُرُونِ",
        transliteration: "A'udhu bikalimatillahit-tammati min ghadabihi wa 'iqabihi wa sharri 'ibadihi wa min hamazatish-shayatini wa an yahdurun",
        translation: "I seek refuge in the perfect words of Allah from His anger and punishment, from the evil of His servants, and from the whisperings of the Shayateen and from their presence.",
        reference: "Abu Dawud 3893",
      },
    ],
  },

  {
    id: "family",
    name: "Family & Loved Ones",
    icon: "users",
    accentColor: "#F48FB1",
    duas: [
      {
        id: "fa1",
        title: "Dua for Righteous Spouse & Children",
        arabic: "رَبَّنَا هَبْ لَنَا مِنْ أَزْوَاجِنَا وَذُرِّيَّاتِنَا قُرَّةَ أَعْيُنٍ وَاجْعَلْنَا لِلْمُتَّقِينَ إِمَامًا",
        transliteration: "Rabbana hab lana min azwajina wa dhurriyyatina qurrata a'yunin waj'alna lil-muttaqina imama",
        translation: "Our Lord, grant us from among our spouses and offspring comfort to our eyes, and make us an example for the righteous.",
        reference: "Quran 25:74",
      },
      {
        id: "fa2",
        title: "Dua for Parents",
        arabic: "رَّبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا",
        transliteration: "Rabbi irhamhuma kama rabbayani sagheera",
        translation: "My Lord, have mercy upon them as they raised me when I was small.",
        reference: "Quran 17:24",
      },
      {
        id: "fa3",
        title: "Dua for Newborn",
        arabic: "بَارَكَ اللهُ لَكَ فِي الْمَوْهُوبِ لَكَ، وَشَكَرْتَ الْوَاهِبَ، وَبَلَغَ أَشُدَّهُ وَرُزِقْتَ بِرَّهُ",
        transliteration: "Barakallahu laka fil-mawhubi lak, wa shakarta al-wahib, wa balagha ashuddahu wa ruziqta birrah",
        translation: "May Allah bless you in the gift given to you, may you give thanks to the Giver, may he reach maturity, and may you be granted his righteousness.",
        reference: "Hisnul Muslim — said to new parents",
      },
      {
        id: "fa4",
        title: "Dua Before Marriage (Wedding Night)",
        arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ خَيْرَهَا وَخَيْرَ مَا جَبَلْتَهَا عَلَيْهِ، وَأَعُوذُ بِكَ مِنْ شَرِّهَا وَمِنْ شَرِّ مَا جَبَلْتَهَا عَلَيْهِ",
        transliteration: "Allahumma inni as'aluka khayrahaa wa khayra ma jabaltaha 'alayh, wa a'udhu bika min sharrihaa wa min sharri ma jabaltaha 'alayh",
        translation: "O Allah, I ask You for the good within her and the good you have created in her nature. And I seek refuge in You from the evil within her and the evil You have created in her nature.",
        reference: "Abu Dawud 2160",
      },
      {
        id: "fa5",
        title: "Dua Before Marital Relations",
        arabic: "بِسْمِ اللهِ، اللَّهُمَّ جَنِّبْنَا الشَّيْطَانَ، وَجَنِّبِ الشَّيْطَانَ مَا رَزَقْتَنَا",
        transliteration: "Bismillah, Allahumma jannibna-sh-shaytana, wa jannibish-shaytana ma razaqtana",
        translation: "In the name of Allah. O Allah, keep the Shaytan away from us and keep the Shaytan away from what You have blessed us with.",
        reference: "Al-Bukhari 5165",
        virtue: "A child conceived after this dua will not be harmed by Shaytan.",
      },
      {
        id: "fa6",
        title: "Dua of Ibrahim for His Family",
        arabic: "رَبِّ اجْعَلْنِي مُقِيمَ الصَّلَاةِ وَمِن ذُرِّيَّتِي ۚ رَبَّنَا وَتَقَبَّلْ دُعَاءِ",
        transliteration: "Rabbij-'alni muqimas-salati wa min dhurriyyati, rabbana wa taqabbal du'a'",
        translation: "My Lord, make me an establisher of prayer, and [many] from my descendants. Our Lord, and accept my supplication.",
        reference: "Quran 14:40",
      },
      {
        id: "fa7",
        title: "For Righteous Offspring",
        arabic: "رَبِّ هَبْ لِي مِنَ الصَّالِحِينَ",
        transliteration: "Rabbi hab li minas-salihin",
        translation: "My Lord, grant me [a child] from among the righteous.",
        reference: "Quran 37:100 — Dua of Prophet Ibrahim alayhis salam",
      },
      {
        id: "fa8",
        title: "Dua for One's Children",
        arabic: "اللَّهُمَّ اجْعَلْهُمْ مِنَ الصَّالِحِينَ وَاجْعَلْهُمْ مِنَ الْمُتَّقِينَ",
        transliteration: "Allahumma-j'alhum minas-salihin waj-'alhum minal-muttaqin",
        translation: "O Allah, make them from among the righteous and make them from among the God-fearing.",
        reference: "Compiled from Sunnah",
      },
    ],
  },

  {
    id: "travel",
    name: "Travel & Journey",
    icon: "map-pin",
    accentColor: "#80CBC4",
    duas: [
      {
        id: "tr1",
        title: "When Boarding a Vehicle",
        arabic: "سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ وَإِنَّا إِلَى رَبِّنَا لَمُنقَلِبُونَ",
        transliteration: "Subhanal-ladhi sakhkhara lana hadha wa ma kunna lahu muqrinin, wa inna ila rabbina lamunqalibun",
        translation: "Glory be to He who has subjected this to us, and we were not capable of that. And indeed, to our Lord we will surely return.",
        reference: "Quran 43:13-14 — say when mounting any vehicle",
      },
      {
        id: "tr2",
        title: "Dua for the Journey",
        arabic: "اللَّهُمَّ إِنَّا نَسْأَلُكَ فِي سَفَرِنَا هَذَا الْبِرَّ وَالتَّقْوَى، وَمِنَ الْعَمَلِ مَا تَرْضَى، اللَّهُمَّ هَوِّنْ عَلَيْنَا سَفَرَنَا هَذَا وَاطْوِ عَنَّا بُعْدَهُ",
        transliteration: "Allahumma inna nas'aluka fi safarina hadhal-birra wat-taqwa, wa minal-'amali ma tarda, Allahumma hawwin 'alayna safarana hadha watwi 'anna bu'dah",
        translation: "O Allah, we ask You on this journey for righteousness and piety, and for deeds that are pleasing to You. O Allah, make this journey easy for us and shorten its distance for us.",
        reference: "Muslim 1342",
      },
      {
        id: "tr3",
        title: "Dua When Entering a New Town",
        arabic: "اللَّهُمَّ بَارِكْ لَنَا فِيهَا",
        transliteration: "Allahumma barik lana fiha",
        translation: "O Allah, bless us in it.",
        reference: "Hisnul Muslim — said upon entering a town",
      },
      {
        id: "tr4",
        title: "Dua When Stopping for Rest",
        arabic: "أَعُوذُ بِكَلِمَاتِ اللهِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ",
        transliteration: "A'udhu bikalimatillahit-tammati min sharri ma khalaq",
        translation: "I seek refuge in the perfect words of Allah from the evil of what He has created.",
        reference: "Muslim 2708 — say this when stopping at a resting place",
        virtue: "Nothing will harm the person who says this until he leaves that resting place.",
      },
      {
        id: "tr5",
        title: "When Returning from Travel",
        arabic: "آيِبُونَ تَائِبُونَ عَابِدُونَ لِرَبِّنَا حَامِدُونَ",
        transliteration: "Ayibuna ta'ibuna 'abiduna lirabbina hamidun",
        translation: "We are returning, repenting, worshipping, and praising our Lord.",
        reference: "Al-Bukhari 3085 — Muslim 1342",
      },
      {
        id: "tr6",
        title: "Dua at the Airport / Start of Journey",
        arabic: "اللَّهُمَّ أَنْتَ الصَّاحِبُ فِي السَّفَرِ وَالْخَلِيفَةُ فِي الأَهْلِ، اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ وَعْثَاءِ السَّفَرِ وَكَآبَةِ الْمَنْظَرِ وَسُوءِ الْمُنْقَلَبِ فِي الْمَالِ وَالأَهْلِ",
        transliteration: "Allahumma antas-sahibu fis-safar, wal-khalifatu fil-ahl, Allahumma inni a'udhu bika min wa'tha'is-safar, wa ka'abatil-manzar, wa su'il-munqalabi fil-mali wal-ahl",
        translation: "O Allah, You are the Companion on the journey and the Guardian of the family. O Allah, I seek refuge in You from the hardship of travel, from seeing something distressing, and from an ill return in matters of wealth and family.",
        reference: "Muslim 1342",
      },
      {
        id: "tr7",
        title: "Takbeer While Ascending",
        arabic: "اللهُ أَكْبَرُ",
        transliteration: "Allahu Akbar",
        translation: "Allah is the Greatest — say when going up a hill or ascending stairs.",
        reference: "Al-Bukhari 2993",
      },
      {
        id: "tr8",
        title: "SubhanAllah While Descending",
        arabic: "سُبْحَانَ اللهِ",
        transliteration: "SubhanAllah",
        translation: "Glory be to Allah — say when going down a slope or descending stairs.",
        reference: "Al-Bukhari 2993",
      },
    ],
  },

  {
    id: "healing",
    name: "Health & Healing",
    icon: "activity",
    accentColor: "#A5D6A7",
    duas: [
      {
        id: "hl1",
        title: "Dua for Healing the Sick",
        arabic: "اللَّهُمَّ رَبَّ النَّاسِ، أَذْهِبِ الْبَأْسَ، اشْفِ أَنْتَ الشَّافِي، لاَ شِفَاءَ إِلاَّ شِفَاؤُكَ، شِفَاءً لاَ يُغَادِرُ سَقَمًا",
        transliteration: "Allahumma rabban-nasi, adhhibil-ba's, ishfi antash-shafi, la shifa'a illa shifa'uk, shifa'an la yughadiru saqama",
        translation: "O Allah, Lord of mankind, remove the harm and heal. You are the Healer. There is no healing except Your healing — a healing that leaves no illness behind.",
        reference: "Al-Bukhari 5750",
      },
      {
        id: "hl2",
        title: "Placing Hand on Pain (×7)",
        arabic: "أَعُوذُ بِاللهِ وَقُدْرَتِهِ مِنْ شَرِّ مَا أَجِدُ وَأُحَاذِرُ",
        transliteration: "A'udhu billahi wa qudratihi min sharri ma ajidu wa uhadhir",
        translation: "I seek refuge in Allah and His power from the evil of what I am feeling and what I am afraid of.",
        reference: "Muslim 2202",
        repeat: "7× while placing hand on the pain",
        virtue: "The pain is relieved, by the permission of Allah.",
      },
      {
        id: "hl3",
        title: "Ruqyah — Al-Fatiha",
        arabic: "بِسْمِ اللهِ أَرْقِيكَ مِنْ كُلِّ شَيْءٍ يُؤْذِيكَ، وَمِنْ شَرِّ كُلِّ نَفْسٍ أَوْ عَيْنٍ حَاسِدٍ، اللهُ يَشْفِيكَ، بِسْمِ اللهِ أَرْقِيكَ",
        transliteration: "Bismillahi arqeeka, min kulli shay'in yu'dheeka, wa min sharri kulli nafsin aw 'aynin hasid, Allahu yashfeek, bismillahi arqeek",
        translation: "In the name of Allah I perform ruqyah for you, from everything that harms you, from the evil of every soul or envious eye. May Allah heal you. In the name of Allah I perform ruqyah for you.",
        reference: "Muslim 2186",
      },
      {
        id: "hl4",
        title: "Visiting the Sick — Wishing Recovery",
        arabic: "لاَ بَأْسَ طَهُورٌ إِنْ شَاءَ اللَّهُ",
        transliteration: "La ba'sa, tahurun in sha'Allah",
        translation: "No harm, it is a purification, if Allah wills.",
        reference: "Al-Bukhari 5656 — say when visiting the sick",
        virtue: "The Prophet ﷺ said this to those who were ill.",
      },
      {
        id: "hl5",
        title: "Dua for the Sick Person You Visit",
        arabic: "اللَّهُمَّ اشْفِ عَبْدَكَ يَنْكَأُ لَكَ عَدُوًّا أَوْ يَمْشِي لَكَ إِلَى صَلاَةٍ",
        transliteration: "Allahumma ashfi 'abdaka yankaa laka 'aduwwan aw yamshi laka ila salah",
        translation: "O Allah, heal Your servant so that he may wound the enemy for Your sake, or walk to prayer for Your sake.",
        reference: "Abu Dawud 3107",
      },
      {
        id: "hl6",
        title: "When in Pain — 3 times",
        arabic: "بِسْمِ اللهِ",
        transliteration: "Bismillah (3×) then: A'udhu billahi wa qudratihi...",
        translation: "Say Bismillah 3 times, then: I seek refuge in Allah and His power from the evil of what I am feeling and what I am afraid of — 7 times.",
        reference: "Muslim 2202",
        repeat: "3× Bismillah + 7× A'udhu...",
      },
      {
        id: "hl7",
        title: "When Sneezing — Full Sequence",
        arabic: "الْحَمْدُ لِلهِ ❋ يَرْحَمُكَ اللهُ ❋ يَهْدِيكُمُ اللهُ وَيُصْلِحُ بَالَكُمْ",
        transliteration: "Sneezer: Alhamdulillah · Hearer: Yarhamukallah · Reply: Yahdikumullahu wa yuslihu balakum",
        translation: "Sneezer says: Praise be to Allah. Hearer says: May Allah have mercy on you. Sneezer replies: May Allah guide you and set your affairs right.",
        reference: "Al-Bukhari 6224",
      },
      {
        id: "hl8",
        title: "Dua for Good Health",
        arabic: "اللَّهُمَّ عَافِنِي فِي بَدَنِي، اللَّهُمَّ عَافِنِي فِي سَمْعِي، اللَّهُمَّ عَافِنِي فِي بَصَرِي",
        transliteration: "Allahumma 'afini fi badani, Allahumma 'afini fi sam'i, Allahumma 'afini fi basari",
        translation: "O Allah, grant me health in my body. O Allah, grant me health in my hearing. O Allah, grant me health in my sight.",
        reference: "Abu Dawud 5090 — recite 3 times in the morning and evening",
        repeat: "3×",
      },
    ],
  },
];

export function searchDuas(query: string): Array<DuaItem & { categoryId: string; categoryName: string }> {
  if (!query.trim()) return [];
  const q = query.toLowerCase().trim();
  const results: Array<DuaItem & { categoryId: string; categoryName: string }> = [];
  for (const cat of ALL_DUA_CATEGORIES) {
    for (const dua of cat.duas) {
      if (
        dua.title.toLowerCase().includes(q) ||
        dua.translation.toLowerCase().includes(q) ||
        dua.transliteration.toLowerCase().includes(q) ||
        (dua.reference ?? "").toLowerCase().includes(q) ||
        (dua.virtue ?? "").toLowerCase().includes(q)
      ) {
        results.push({ ...dua, categoryId: cat.id, categoryName: cat.name });
      }
    }
  }
  return results;
}
