export interface Hadith {
  id: string;
  arabic: string;
  transliteration?: string;
  translation: string;
  narrator: string;
  source: string;
  grade: string;
  topic: string;
  collection: "Bukhari" | "Muslim" | "Both";
}

export const HADITHS: Hadith[] = [
  // ── Intentions ──────────────────────────────────────────────────────────────
  {
    id: "h001",
    topic: "Intentions",
    arabic: "إِنَّمَا الأَعْمَالُ بِالنِّيَّاتِ، وَإِنَّمَا لِكُلِّ امْرِئٍ مَا نَوَى",
    transliteration: "Innamal-a'mālu bin-niyyāt, wa innamā likulli-mri'in mā nawā",
    translation: "Actions are judged by their intentions, and every person will get the reward according to what they intended.",
    narrator: "Narrated by ʿUmar ibn al-Khaṭṭāb (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 1 · Ṣaḥīḥ Muslim 1907",
    grade: "Sahih",
    collection: "Both",
  },
  {
    id: "h002",
    topic: "Intentions",
    arabic: "إِنَّ اللَّهَ لاَ يَنْظُرُ إِلَى أَجْسَامِكُمْ وَلاَ إِلَى صُوَرِكُمْ وَلَكِنْ يَنْظُرُ إِلَى قُلُوبِكُمْ وَأَعْمَالِكُمْ",
    translation: "Indeed, Allah does not look at your bodies or your appearances, but He looks at your hearts and your deeds.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ Muslim 2564",
    grade: "Sahih",
    collection: "Muslim",
  },

  // ── Prayer ───────────────────────────────────────────────────────────────────
  {
    id: "h003",
    topic: "Prayer",
    arabic: "الصَّلَاةُ عِمَادُ الدِّينِ، مَنْ أَقَامَهَا فَقَدْ أَقَامَ الدِّينَ، وَمَنْ هَدَمَهَا فَقَدْ هَدَمَ الدِّينَ",
    translation: "Prayer is the pillar of the religion. Whoever establishes it has established the religion, and whoever abandons it has demolished it.",
    narrator: "Narrated by Muʿādh ibn Jabal (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī (via al-Bayhaqī, graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Bukhari",
  },
  {
    id: "h004",
    topic: "Prayer",
    arabic: "أَرَأَيْتُمْ لَوْ أَنَّ نَهْراً بِبَابِ أَحَدِكُمْ يَغْتَسِلُ مِنْهُ كُلَّ يَوْمٍ خَمْسَ مَرَّاتٍ هَلْ يَبْقَى مِنْ دَرَنِهِ شَيْءٌ",
    translation: "Tell me: if there were a river at one of your doors in which you bathed five times each day, would any dirt remain on you? That is the likeness of the five prayers — through them Allah wipes away sins.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 528 · Ṣaḥīḥ Muslim 667",
    grade: "Sahih",
    collection: "Both",
  },
  {
    id: "h005",
    topic: "Prayer",
    arabic: "أَوَّلُ مَا يُحَاسَبُ بِهِ الْعَبْدُ يَوْمَ الْقِيَامَةِ الصَّلاةُ",
    translation: "The first thing for which a person will be called to account on the Day of Judgement is the prayer.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Nasāʾī 465 (graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Bukhari",
  },
  {
    id: "h006",
    topic: "Prayer",
    arabic: "إِنَّ بَيْنَ الرَّجُلِ وَبَيْنَ الشِّرْكِ وَالْكُفْرِ تَرْكَ الصَّلاَةِ",
    translation: "Between a man and shirk (associating partners with Allah) and disbelief is the abandonment of prayer.",
    narrator: "Narrated by Jābir ibn ʿAbdullāh (رضي الله عنه)",
    source: "Ṣaḥīḥ Muslim 82",
    grade: "Sahih",
    collection: "Muslim",
  },
  {
    id: "h007",
    topic: "Prayer",
    arabic: "صَلُّوا كَمَا رَأَيْتُمُونِي أُصَلِّي",
    transliteration: "Ṣallū kamā ra'aytumūnī uṣallī",
    translation: "Pray as you have seen me pray.",
    narrator: "Narrated by Mālik ibn al-Ḥuwayrith (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 631",
    grade: "Sahih",
    collection: "Bukhari",
  },
  {
    id: "h008",
    topic: "Prayer",
    arabic: "أَحَبُّ الأَعْمَالِ إِلَى اللَّهِ الصَّلاةُ عَلَى وَقْتِهَا",
    translation: "The most beloved of deeds to Allah is prayer performed on time.",
    narrator: "Narrated by ʿAbdullāh ibn Masʿūd (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 527 · Ṣaḥīḥ Muslim 85",
    grade: "Sahih",
    collection: "Both",
  },
  {
    id: "h009",
    topic: "Prayer",
    arabic: "مَنْ صَلَّى الْبَرْدَيْنِ دَخَلَ الْجَنَّةَ",
    translation: "Whoever prays the two cool prayers (Fajr and ʿAsr) will enter Paradise.",
    narrator: "Narrated by Abū Mūsā al-Ashʿarī (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 574 · Ṣaḥīḥ Muslim 635",
    grade: "Sahih",
    collection: "Both",
  },
  {
    id: "h010",
    topic: "Prayer",
    arabic: "أَقْرَبُ مَا يَكُونُ الْعَبْدُ مِنْ رَبِّهِ وَهُوَ سَاجِدٌ فَأَكْثِرُوا الدُّعَاءَ",
    translation: "The closest a servant is to his Lord is when he is in prostration, so make many supplications in it.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ Muslim 482",
    grade: "Sahih",
    collection: "Muslim",
  },

  // ── Quran ────────────────────────────────────────────────────────────────────
  {
    id: "h011",
    topic: "Quran",
    arabic: "خَيْرُكُمْ مَنْ تَعَلَّمَ الْقُرْآنَ وَعَلَّمَهُ",
    transliteration: "Khayrukum man ta'allamal-Qur'āna wa 'allamah",
    translation: "The best of you are those who learn the Quran and teach it.",
    narrator: "Narrated by ʿUthmān ibn ʿAffān (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 5027",
    grade: "Sahih",
    collection: "Bukhari",
  },
  {
    id: "h012",
    topic: "Quran",
    arabic: "اقْرَءُوا الْقُرْآنَ فَإِنَّهُ يَأْتِي يَوْمَ الْقِيَامَةِ شَفِيعاً لأَصْحَابِهِ",
    translation: "Recite the Quran, for it will come on the Day of Resurrection as an intercessor for its companions.",
    narrator: "Narrated by Abū Umāmah (رضي الله عنه)",
    source: "Ṣaḥīḥ Muslim 804",
    grade: "Sahih",
    collection: "Muslim",
  },
  {
    id: "h013",
    topic: "Quran",
    arabic: "الَّذِي يَقْرَأُ الْقُرْآنَ وَهُوَ مَاهِرٌ بِهِ مَعَ السَّفَرَةِ الْكِرَامِ الْبَرَرَةِ",
    translation: "The one who recites the Quran proficiently will be with the noble, obedient scribes (the angels). The one who recites the Quran with difficulty, stammering through it, will have a double reward.",
    narrator: "Narrated by ʿĀʾishah (رضي الله عنها)",
    source: "Ṣaḥīḥ al-Bukhārī 4937 · Ṣaḥīḥ Muslim 798",
    grade: "Sahih",
    collection: "Both",
  },
  {
    id: "h014",
    topic: "Quran",
    arabic: "مَنْ قَرَأَ حَرْفاً مِنْ كِتَابِ اللَّهِ فَلَهُ بِهِ حَسَنَةٌ",
    translation: "Whoever recites a letter from the Book of Allah will have a good deed recorded for him, and a good deed is multiplied ten times.",
    narrator: "Narrated by ʿAbdullāh ibn Masʿūd (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Tirmidhī 2910 (graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Bukhari",
  },

  // ── Fasting ──────────────────────────────────────────────────────────────────
  {
    id: "h015",
    topic: "Fasting",
    arabic: "مَنْ صَامَ رَمَضَانَ إِيمَاناً وَاحْتِسَاباً غُفِرَ لَهُ مَا تَقَدَّمَ مِنْ ذَنْبِهِ",
    translation: "Whoever fasts Ramaḍān out of faith and seeking reward, his past sins will be forgiven.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 38 · Ṣaḥīḥ Muslim 760",
    grade: "Sahih",
    collection: "Both",
  },
  {
    id: "h016",
    topic: "Fasting",
    arabic: "الصِّيَامُ جُنَّةٌ",
    transliteration: "Aṣ-ṣiyāmu junnah",
    translation: "Fasting is a shield.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 1904 · Ṣaḥīḥ Muslim 1151",
    grade: "Sahih",
    collection: "Both",
  },
  {
    id: "h017",
    topic: "Fasting",
    arabic: "كُلُّ عَمَلِ ابْنِ آدَمَ يُضَاعَفُ، الْحَسَنَةُ بِعَشْرِ أَمْثَالِهَا إِلَى سَبْعمِائَةِ ضِعْفٍ، قَالَ اللَّهُ عَزَّ وَجَلَّ إِلاَّ الصَّوْمَ فَإِنَّهُ لِي وَأَنَا أَجْزِي بِهِ",
    translation: "Every deed of the son of Ādam is multiplied — a good deed by ten to seven hundred times. Allah the Mighty and Majestic says: 'Except for fasting — it is for Me and I shall reward for it.'",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ Muslim 1151",
    grade: "Sahih",
    collection: "Muslim",
  },
  {
    id: "h018",
    topic: "Fasting",
    arabic: "إِذَا جَاءَ رَمَضَانُ فُتِّحَتْ أَبْوَابُ الْجَنَّةِ وَغُلِّقَتْ أَبْوَابُ النَّارِ وَسُلْسِلَتِ الشَّيَاطِينُ",
    translation: "When Ramaḍān comes, the gates of Paradise are opened, the gates of Hellfire are closed, and the devils are chained.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 1899 · Ṣaḥīḥ Muslim 1079",
    grade: "Sahih",
    collection: "Both",
  },
  {
    id: "h019",
    topic: "Fasting",
    arabic: "مَنْ لَمْ يَدَعْ قَوْلَ الزُّورِ وَالْعَمَلَ بِهِ فَلَيْسَ لِلَّهِ حَاجَةٌ فِي أَنْ يَدَعَ طَعَامَهُ وَشَرَابَهُ",
    translation: "Whoever does not give up false speech and acting upon it, Allah has no need of his giving up food and drink.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 1903",
    grade: "Sahih",
    collection: "Bukhari",
  },
  {
    id: "h020",
    topic: "Fasting",
    arabic: "لِلصَّائِمِ فَرْحَتَانِ يَفْرَحُهُمَا إِذَا أَفْطَرَ فَرِحَ بِفِطْرِهِ وَإِذَا لَقِيَ رَبَّهُ فَرِحَ بِصَوْمِهِ",
    translation: "The fasting person has two moments of joy: when he breaks his fast he is joyful, and when he meets his Lord he will be joyful for his fasting.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 1904 · Ṣaḥīḥ Muslim 1151",
    grade: "Sahih",
    collection: "Both",
  },

  // ── Dhikr ────────────────────────────────────────────────────────────────────
  {
    id: "h021",
    topic: "Dhikr",
    arabic: "كَلِمَتَانِ خَفِيفَتَانِ عَلَى اللِّسَانِ، ثَقِيلَتَانِ فِي الْمِيزَانِ، حَبِيبَتَانِ إِلَى الرَّحْمَنِ: سُبْحَانَ اللَّهِ وَبِحَمْدِهِ، سُبْحَانَ اللَّهِ الْعَظِيمِ",
    transliteration: "SubḥānAllāhi wa biḥamdih, SubḥānAllāhil-ʿAẓīm",
    translation: "Two phrases are light on the tongue, heavy on the scales, and beloved to the Most Merciful: 'SubḥānAllāh wa biḥamdih' and 'SubḥānAllāhil-ʿAẓīm'.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 6682 · Ṣaḥīḥ Muslim 2694",
    grade: "Sahih",
    collection: "Both",
  },
  {
    id: "h022",
    topic: "Dhikr",
    arabic: "مَثَلُ الَّذِي يَذْكُرُ رَبَّهُ وَالَّذِي لاَ يَذْكُرُ رَبَّهُ مَثَلُ الْحَيِّ وَالْمَيِّتِ",
    translation: "The likeness of the one who remembers his Lord and the one who does not is like the living and the dead.",
    narrator: "Narrated by Abū Mūsā (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 6407",
    grade: "Sahih",
    collection: "Bukhari",
  },
  {
    id: "h023",
    topic: "Dhikr",
    arabic: "أَلاَ أُخْبِرُكُمْ بِخَيْرِ أَعْمَالِكُمْ وَأَزْكَاهَا عِنْدَ مَلِيكِكُمْ وَأَرْفَعِهَا فِي دَرَجَاتِكُمْ وَخَيْرٍ لَكُمْ مِنْ إِنْفَاقِ الذَّهَبِ وَالْوَرِقِ ذِكْرُ اللَّهِ",
    translation: "Shall I not inform you of the best of your deeds, the purest of them before your Sovereign, the highest of them in your ranks, and that which is better for you than spending gold and silver? Remembrance of Allah.",
    narrator: "Narrated by Abū al-Dardāʾ (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Tirmidhī 3377 (graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Bukhari",
  },
  {
    id: "h024",
    topic: "Dhikr",
    arabic: "مَنْ قَالَ سُبْحَانَ اللَّهِ وَبِحَمْدِهِ فِي يَوْمٍ مِائَةَ مَرَّةٍ حُطَّتْ خَطَايَاهُ وَإِنْ كَانَتْ مِثْلَ زَبَدِ الْبَحْرِ",
    translation: "Whoever says 'SubḥānAllāhi wa biḥamdih' one hundred times a day, his sins will be wiped away even if they are like the foam of the sea.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 6405 · Ṣaḥīḥ Muslim 2691",
    grade: "Sahih",
    collection: "Both",
  },
  {
    id: "h025",
    topic: "Dhikr",
    arabic: "مَنْ قَالَ لاَ إِلَهَ إِلاَّ اللَّهُ وَحْدَهُ لاَ شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَىْءٍ قَدِيرٌ فِي يَوْمٍ مِائَةَ مَرَّةٍ كَانَتْ لَهُ عَدْلَ عَشْرِ رِقَابٍ",
    translation: "Whoever says 'Lā ilāha illAllāh waḥdahu lā sharīka lah, lahul-mulku wa lahul-ḥamdu wa huwa ʿalā kulli shay'in qadīr' one hundred times a day, it is equivalent to freeing ten slaves.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 3293 · Ṣaḥīḥ Muslim 2691",
    grade: "Sahih",
    collection: "Both",
  },

  // ── Dua ──────────────────────────────────────────────────────────────────────
  {
    id: "h026",
    topic: "Dua",
    arabic: "الدُّعَاءُ هُوَ الْعِبَادَةُ",
    transliteration: "Ad-duʿāʾu huwal-ʿibādah",
    translation: "Supplication is worship.",
    narrator: "Narrated by al-Nuʿmān ibn Bashīr (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Tirmidhī 2969 (graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Bukhari",
  },
  {
    id: "h027",
    topic: "Dua",
    arabic: "إِنَّ رَبَّكُمْ تَبَارَكَ وَتَعَالَى حَيِيٌّ كَرِيمٌ يَسْتَحِيي مِنْ عَبْدِهِ إِذَا رَفَعَ إِلَيْهِ يَدَيْهِ أَنْ يَرُدَّهُمَا صِفْراً خَائِبَتَيْنِ",
    translation: "Your Lord, Blessed and Exalted, is Forbearing and Generous. He is too modest to let His servant raise his hands to Him and then return them empty.",
    narrator: "Narrated by Salmān al-Fārisī (رضي الله عنه)",
    source: "Ṣaḥīḥ Abū Dāwūd 1488 (graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Bukhari",
  },
  {
    id: "h028",
    topic: "Dua",
    arabic: "مَا مِنْ مُسْلِمٍ يَدْعُو بِدَعْوَةٍ لَيْسَ فِيهَا إِثْمٌ وَلاَ قَطِيعَةُ رَحِمٍ إِلاَّ أَعْطَاهُ اللَّهُ بِهَا إِحْدَى ثَلاَثٍ",
    translation: "There is no Muslim who makes a supplication that contains no sin and no severing of family ties except that Allah will give him one of three things: either He will answer his supplication, or He will store it up for him in the Hereafter, or He will divert an equivalent evil from him.",
    narrator: "Narrated by Abū Saʿīd al-Khudrī (رضي الله عنه)",
    source: "Musnad Aḥmad 11133 (graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Muslim",
  },
  {
    id: "h029",
    topic: "Dua",
    arabic: "ادْعُوا اللَّهَ وَأَنْتُمْ مُوقِنُونَ بِالإِجَابَةِ",
    translation: "Call upon Allah while being certain of being answered.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Tirmidhī 3479 (graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Bukhari",
  },
  {
    id: "h030",
    topic: "Dua",
    arabic: "ثَلاثَةٌ لاَ تُرَدُّ دَعْوَتُهُمُ الإِمَامُ الْعَادِلُ وَالصَّائِمُ حَتَّى يُفْطِرَ وَدَعْوَةُ الْمَظْلُومِ",
    translation: "Three people whose supplication is not rejected: the just imam, the fasting person until he breaks his fast, and the supplication of the one who is wronged.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Tirmidhī 2526 (graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Bukhari",
  },

  // ── Kindness ─────────────────────────────────────────────────────────────────
  {
    id: "h031",
    topic: "Kindness",
    arabic: "الرَّاحِمُونَ يَرْحَمُهُمُ الرَّحْمَنُ، ارْحَمُوا مَنْ فِي الأَرْضِ يَرْحَمْكُمْ مَنْ فِي السَّمَاءِ",
    transliteration: "Ar-rāḥimūna yarḥamuhum ar-Raḥmān",
    translation: "The merciful are shown mercy by the Most Merciful. Be merciful to those on the earth and the One in the heavens will have mercy upon you.",
    narrator: "Narrated by ʿAbdullāh ibn ʿAmr (رضي الله عنه)",
    source: "Ṣaḥīḥ Muslim 2922 · Ṣaḥīḥ al-Tirmidhī 1924",
    grade: "Sahih",
    collection: "Muslim",
  },
  {
    id: "h032",
    topic: "Kindness",
    arabic: "لا تَحْقِرَنَّ مِنَ الْمَعْرُوفِ شَيْئاً وَلَوْ أَنْ تَلْقَى أَخَاكَ بِوَجْهٍ طَلْقٍ",
    translation: "Do not consider any good deed insignificant, even if it is just meeting your brother with a cheerful face.",
    narrator: "Narrated by Abū Dharr (رضي الله عنه)",
    source: "Ṣaḥīḥ Muslim 2626",
    grade: "Sahih",
    collection: "Muslim",
  },
  {
    id: "h033",
    topic: "Kindness",
    arabic: "إِنَّ اللَّهَ رَفِيقٌ يُحِبُّ الرِّفْقَ فِي الأَمْرِ كُلِّهِ",
    translation: "Indeed, Allah is Gentle and loves gentleness in all matters.",
    narrator: "Narrated by ʿĀʾishah (رضي الله عنها)",
    source: "Ṣaḥīḥ al-Bukhārī 6927 · Ṣaḥīḥ Muslim 2165",
    grade: "Sahih",
    collection: "Both",
  },
  {
    id: "h034",
    topic: "Kindness",
    arabic: "مَنْ لَا يَرْحَمُ لَا يُرْحَمُ",
    translation: "He who does not show mercy will not be shown mercy.",
    narrator: "Narrated by Jarīr ibn ʿAbdullāh (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 5997 · Ṣaḥīḥ Muslim 2319",
    grade: "Sahih",
    collection: "Both",
  },
  {
    id: "h035",
    topic: "Kindness",
    arabic: "مَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الآخِرِ فَلْيُكْرِمْ جَارَهُ",
    translation: "Whoever believes in Allah and the Last Day, let him honour his neighbour.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 6018 · Ṣaḥīḥ Muslim 47",
    grade: "Sahih",
    collection: "Both",
  },
  {
    id: "h036",
    topic: "Kindness",
    arabic: "إِنَّ اللَّهَ يُحِبُّ الرِّفْقَ وَيُعْطِي عَلَى الرِّفْقِ مَا لَا يُعْطِي عَلَى الْعُنْفِ",
    translation: "Allah loves gentleness and gives for gentleness what He does not give for harshness.",
    narrator: "Narrated by ʿĀʾishah (رضي الله عنها)",
    source: "Ṣaḥīḥ Muslim 2593",
    grade: "Sahih",
    collection: "Muslim",
  },

  // ── Family ───────────────────────────────────────────────────────────────────
  {
    id: "h037",
    topic: "Family",
    arabic: "خَيْرُكُمْ خَيْرُكُمْ لأَهْلِهِ وَأَنَا خَيْرُكُمْ لأَهْلِي",
    translation: "The best of you is the best to his family, and I am the best of you to my family.",
    narrator: "Narrated by ʿĀʾishah (رضي الله عنها)",
    source: "Ṣaḥīḥ al-Tirmidhī 3895 (graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Bukhari",
  },
  {
    id: "h038",
    topic: "Family",
    arabic: "أَطْعِمُوا الطَّعَامَ، وَصِلُوا الأَرْحَامَ، وَصَلُّوا بِاللَّيْلِ وَالنَّاسُ نِيَامٌ، تَدْخُلُوا الْجَنَّةَ بِسَلاَمٍ",
    translation: "Feed people, maintain ties of kinship, pray at night while people sleep, and you will enter Paradise in peace.",
    narrator: "Narrated by ʿAbdullāh ibn Salām (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 3798",
    grade: "Sahih",
    collection: "Bukhari",
  },
  {
    id: "h039",
    topic: "Family",
    arabic: "لاَ يَدْخُلُ الْجَنَّةَ قَاطِعٌ",
    translation: "The one who severs ties of kinship will not enter Paradise.",
    narrator: "Narrated by Jubayr ibn Muṭʿim (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 5984 · Ṣaḥīḥ Muslim 2556",
    grade: "Sahih",
    collection: "Both",
  },
  {
    id: "h040",
    topic: "Family",
    arabic: "الرَّحِمُ شُجْنَةٌ مِنَ الرَّحْمَنِ فَقَالَ اللَّهُ مَنْ وَصَلَكِ وَصَلْتُهُ وَمَنْ قَطَعَكِ قَطَعْتُهُ",
    translation: "The womb is a branch of the Most Merciful. Allah says: 'Whoever maintains ties with it, I will maintain ties with him; whoever severs ties with it, I will sever ties with him.'",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 5988 · Ṣaḥīḥ Muslim 2555",
    grade: "Sahih",
    collection: "Both",
  },
  {
    id: "h041",
    topic: "Family",
    arabic: "الْجَنَّةُ تَحْتَ أَقْدَامِ الأُمَّهَاتِ",
    translation: "Paradise lies at the feet of mothers.",
    narrator: "Narrated by Muʿāwiyah ibn Jāhimah (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Nasāʾī 3104 (graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Muslim",
  },
  {
    id: "h042",
    topic: "Family",
    arabic: "جَاءَ رَجُلٌ إِلَى رَسُولِ اللَّهِ فَقَالَ مَنْ أَحَقُّ النَّاسِ بِحُسْنِ صَحَابَتِي قَالَ أُمُّكَ",
    translation: "A man came to the Messenger of Allah and said: 'Who is most deserving of my good companionship?' He said: 'Your mother.' The man said: 'Then who?' He said: 'Your mother.' The man said: 'Then who?' He said: 'Your mother.' The man said: 'Then who?' He said: 'Your father.'",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 5971 · Ṣaḥīḥ Muslim 2548",
    grade: "Sahih",
    collection: "Both",
  },

  // ── Brotherhood ───────────────────────────────────────────────────────────────
  {
    id: "h043",
    topic: "Brotherhood",
    arabic: "الْمُسْلِمُ أَخُو الْمُسْلِمِ، لاَ يَظْلِمُهُ، وَلاَ يُسْلِمُهُ",
    translation: "A Muslim is the brother of another Muslim. He does not oppress him, nor does he hand him over.",
    narrator: "Narrated by ʿAbdullāh ibn ʿUmar (رضي الله عنهما)",
    source: "Ṣaḥīḥ al-Bukhārī 2442 · Ṣaḥīḥ Muslim 2580",
    grade: "Sahih",
    collection: "Both",
  },
  {
    id: "h044",
    topic: "Brotherhood",
    arabic: "مَثَلُ الْمُؤْمِنِينَ فِي تَوَادِّهِمْ وَتَرَاحُمِهِمْ وَتَعَاطُفِهِمْ مَثَلُ الْجَسَدِ إِذَا اشْتَكَى مِنْهُ عُضْوٌ تَدَاعَى لَهُ سَائِرُ الْجَسَدِ بِالسَّهَرِ وَالْحُمَّى",
    translation: "The example of the believers in their mutual love, mercy, and sympathy is like the body: when one limb suffers, the whole body responds with sleeplessness and fever.",
    narrator: "Narrated by al-Nuʿmān ibn Bashīr (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 6011 · Ṣaḥīḥ Muslim 2586",
    grade: "Sahih",
    collection: "Both",
  },
  {
    id: "h045",
    topic: "Brotherhood",
    arabic: "لاَ يُؤْمِنُ أَحَدُكُمْ حَتَّى يُحِبَّ لأَخِيهِ مَا يُحِبُّ لِنَفْسِهِ",
    translation: "None of you truly believes until he loves for his brother what he loves for himself.",
    narrator: "Narrated by Anas ibn Mālik (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 13 · Ṣaḥīḥ Muslim 45",
    grade: "Sahih",
    collection: "Both",
  },
  {
    id: "h046",
    topic: "Brotherhood",
    arabic: "الْمُسْلِمُ مَنْ سَلِمَ الْمُسْلِمُونَ مِنْ لِسَانِهِ وَيَدِهِ",
    translation: "A Muslim is one from whose tongue and hand other Muslims are safe.",
    narrator: "Narrated by ʿAbdullāh ibn ʿAmr (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 10 · Ṣaḥīḥ Muslim 41",
    grade: "Sahih",
    collection: "Both",
  },
  {
    id: "h047",
    topic: "Brotherhood",
    arabic: "لاَ تَحَاسَدُوا وَلاَ تَنَاجَشُوا وَلاَ تَبَاغَضُوا وَلاَ تَدَابَرُوا وَكُونُوا عِبَادَ اللَّهِ إِخْوَاناً",
    translation: "Do not envy one another, do not outbid one another, do not hate one another, do not shun one another, and be servants of Allah as brothers.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ Muslim 2563",
    grade: "Sahih",
    collection: "Muslim",
  },

  // ── Knowledge ─────────────────────────────────────────────────────────────────
  {
    id: "h048",
    topic: "Knowledge",
    arabic: "مَنْ سَلَكَ طَرِيقاً يَلْتَمِسُ فِيهِ عِلْماً سَهَّلَ اللَّهُ لَهُ بِهِ طَرِيقاً إِلَى الْجَنَّةِ",
    translation: "Whoever travels a path in search of knowledge, Allah will make easy for him a path to Paradise.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ Muslim 2699",
    grade: "Sahih",
    collection: "Muslim",
  },
  {
    id: "h049",
    topic: "Knowledge",
    arabic: "طَلَبُ الْعِلْمِ فَرِيضَةٌ عَلَى كُلِّ مُسْلِمٍ",
    translation: "Seeking knowledge is an obligation upon every Muslim.",
    narrator: "Narrated by Anas ibn Mālik (رضي الله عنه)",
    source: "Ṣaḥīḥ Ibn Mājah 224 (graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Bukhari",
  },
  {
    id: "h050",
    topic: "Knowledge",
    arabic: "إِنَّ اللَّهَ لاَ يَقْبِضُ الْعِلْمَ انْتِزَاعاً يَنْتَزِعُهُ مِنَ الْعِبَادِ وَلَكِنْ يَقْبِضُ الْعِلْمَ بِقَبْضِ الْعُلَمَاءِ",
    translation: "Allah does not take away knowledge by extracting it from people, but He takes away knowledge by taking away the scholars.",
    narrator: "Narrated by ʿAbdullāh ibn ʿAmr (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 100 · Ṣaḥīḥ Muslim 2673",
    grade: "Sahih",
    collection: "Both",
  },
  {
    id: "h051",
    topic: "Knowledge",
    arabic: "مَنْ يُرِدِ اللَّهُ بِهِ خَيْرًا يُفَقِّهْهُ فِي الدِّينِ",
    translation: "Whomsoever Allah intends good for, He gives him understanding of the religion.",
    narrator: "Narrated by Muʿāwiyah (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 71 · Ṣaḥīḥ Muslim 1037",
    grade: "Sahih",
    collection: "Both",
  },
  {
    id: "h052",
    topic: "Knowledge",
    arabic: "إِذَا مَاتَ ابْنُ آدَمَ انْقَطَعَ عَمَلُهُ إِلاَّ مِنْ ثَلاثٍ صَدَقَةٍ جَارِيَةٍ أَوْ عِلْمٍ يُنْتَفَعُ بِهِ أَوْ وَلَدٍ صَالِحٍ يَدْعُو لَهُ",
    translation: "When a person dies, his deeds come to an end except for three: ongoing charity, beneficial knowledge, or a righteous child who prays for him.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ Muslim 1631",
    grade: "Sahih",
    collection: "Muslim",
  },

  // ── Patience ──────────────────────────────────────────────────────────────────
  {
    id: "h053",
    topic: "Patience",
    arabic: "وَمَا أُعْطِيَ أَحَدٌ عَطَاءً خَيْراً وَأَوْسَعَ مِنَ الصَّبْرِ",
    translation: "No one is given a gift better and more comprehensive than patience.",
    narrator: "Narrated by Abū Saʿīd al-Khudrī (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 1469 · Ṣaḥīḥ Muslim 1053",
    grade: "Sahih",
    collection: "Both",
  },
  {
    id: "h054",
    topic: "Patience",
    arabic: "عَجَباً لأَمْرِ الْمُؤْمِنِ إِنَّ أَمْرَهُ كُلَّهُ خَيْرٌ وَلَيْسَ ذَاكَ لأَحَدٍ إِلاَّ لِلْمُؤْمِنِ إِنْ أَصَابَتْهُ سَرَّاءُ شَكَرَ فَكَانَ خَيْراً لَهُ وَإِنْ أَصَابَتْهُ ضَرَّاءُ صَبَرَ فَكَانَ خَيْراً لَهُ",
    translation: "How wonderful is the affair of the believer! Everything in it is good, and this belongs only to the believer. If good befalls him, he gives thanks, and that is good for him. If adversity befalls him, he bears it with patience, and that is good for him.",
    narrator: "Narrated by Ṣuhayb (رضي الله عنه)",
    source: "Ṣaḥīḥ Muslim 2999",
    grade: "Sahih",
    collection: "Muslim",
  },
  {
    id: "h055",
    topic: "Patience",
    arabic: "مَا يُصِيبُ الْمُسْلِمَ مِنْ نَصَبٍ وَلاَ وَصَبٍ وَلاَ هَمٍّ وَلاَ حُزْنٍ وَلاَ أَذًى وَلاَ غَمٍّ حَتَّى الشَّوْكَةِ يُشَاكُهَا إِلاَّ كَفَّرَ اللَّهُ بِهَا مِنْ خَطَايَاهُ",
    translation: "No fatigue, illness, anxiety, sorrow, harm, or sadness afflicts a Muslim — not even the prick of a thorn — without Allah expiating some of his sins through it.",
    narrator: "Narrated by Abū Saʿīd and Abū Hurayrah (رضي الله عنهما)",
    source: "Ṣaḥīḥ al-Bukhārī 5641 · Ṣaḥīḥ Muslim 2573",
    grade: "Sahih",
    collection: "Both",
  },
  {
    id: "h056",
    topic: "Patience",
    arabic: "الصَّبْرُ ضِيَاءٌ",
    translation: "Patience is light.",
    narrator: "Narrated by Abū Mālik al-Ashʿarī (رضي الله عنه)",
    source: "Ṣaḥīḥ Muslim 223",
    grade: "Sahih",
    collection: "Muslim",
  },

  // ── Gratitude ─────────────────────────────────────────────────────────────────
  {
    id: "h057",
    topic: "Gratitude",
    arabic: "مَنْ لَا يَشْكُرُ النَّاسَ لَا يَشْكُرُ اللَّهَ",
    translation: "Whoever does not thank people has not thanked Allah.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ Abū Dāwūd 4811 (graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Bukhari",
  },
  {
    id: "h058",
    topic: "Gratitude",
    arabic: "انْظُرُوا إِلَى مَنْ هُوَ أَسْفَلَ مِنْكُمْ وَلاَ تَنْظُرُوا إِلَى مَنْ هُوَ فَوْقَكُمْ فَهُوَ أَجْدَرُ أَنْ لاَ تَزْدَرُوا نِعْمَةَ اللَّهِ عَلَيْكُمْ",
    translation: "Look at those below you and do not look at those above you, for it is more likely that you will not underestimate the blessing of Allah upon you.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 6490 · Ṣaḥīḥ Muslim 2963",
    grade: "Sahih",
    collection: "Both",
  },

  // ── Repentance ────────────────────────────────────────────────────────────────
  {
    id: "h059",
    topic: "Repentance",
    arabic: "التَّائِبُ مِنَ الذَّنْبِ كَمَنْ لاَ ذَنْبَ لَهُ",
    translation: "The one who repents from sin is like one who has no sin.",
    narrator: "Narrated by ʿAbdullāh ibn Masʿūd (رضي الله عنه)",
    source: "Ṣaḥīḥ Ibn Mājah 4250 (graded Ṣaḥīḥ by al-Albānī)",
    grade: "Sahih",
    collection: "Bukhari",
  },
  {
    id: "h060",
    topic: "Repentance",
    arabic: "إِنَّ اللَّهَ يَقْبَلُ تَوْبَةَ الْعَبْدِ مَا لَمْ يُغَرْغِرْ",
    translation: "Indeed, Allah accepts the repentance of His servant as long as the death-rattle has not reached his throat.",
    narrator: "Narrated by ʿAbdullāh ibn ʿUmar (رضي الله عنهما)",
    source: "Ṣaḥīḥ al-Tirmidhī 3537 (graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Bukhari",
  },
  {
    id: "h061",
    topic: "Repentance",
    arabic: "كُلُّ بَنِي آدَمَ خَطَّاءٌ وَخَيْرُ الْخَطَّائِينَ التَّوَّابُونَ",
    translation: "Every son of Ādam makes mistakes, and the best of those who make mistakes are those who repent.",
    narrator: "Narrated by Anas ibn Mālik (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Tirmidhī 2499 (graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Muslim",
  },
  {
    id: "h062",
    topic: "Repentance",
    arabic: "لَوْ أَخْطَأْتُمْ حَتَّى تَبْلُغَ خَطَايَاكُمُ السَّمَاءَ ثُمَّ تُبْتُمْ لَتَابَ اللَّهُ عَلَيْكُمْ",
    translation: "If you were to sin until your sins reached the sky, then you repented, Allah would accept your repentance.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ Ibn Mājah 4248 (graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Muslim",
  },

  // ── Trust in Allah ────────────────────────────────────────────────────────────
  {
    id: "h063",
    topic: "Trust in Allah",
    arabic: "لَوْ أَنَّكُمْ كُنْتُمْ تَوَكَّلُونَ عَلَى اللَّهِ حَقَّ تَوَكُّلِهِ لَرَزَقَكُمْ كَمَا يَرْزُقُ الطَّيْرَ، تَغْدُو خِمَاصاً وَتَرُوحُ بِطَاناً",
    translation: "If you were to rely upon Allah with true reliance, He would provide for you as He provides for the birds — they go out hungry in the morning and return full in the evening.",
    narrator: "Narrated by ʿUmar ibn al-Khaṭṭāb (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Tirmidhī 2344 (graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Bukhari",
  },
  {
    id: "h064",
    topic: "Trust in Allah",
    arabic: "احْفَظِ اللَّهَ يَحْفَظْكَ، احْفَظِ اللَّهَ تَجِدْهُ تُجَاهَكَ",
    translation: "Preserve (the rights of) Allah and He will preserve you. Preserve (the rights of) Allah and you will find Him before you.",
    narrator: "Narrated by ʿAbdullāh ibn ʿAbbās (رضي الله عنهما)",
    source: "Ṣaḥīḥ al-Tirmidhī 2516 (graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Bukhari",
  },
  {
    id: "h065",
    topic: "Trust in Allah",
    arabic: "اعْلَمْ أَنَّ الأُمَّةَ لَوِ اجْتَمَعَتْ عَلَى أَنْ يَنْفَعُوكَ بِشَيْءٍ لَمْ يَنْفَعُوكَ إِلاَّ بِشَيْءٍ قَدْ كَتَبَهُ اللَّهُ لَكَ",
    translation: "Know that if the entire nation gathered together to benefit you, they would not be able to benefit you except with that which Allah has already recorded for you.",
    narrator: "Narrated by ʿAbdullāh ibn ʿAbbās (رضي الله عنهما)",
    source: "Ṣaḥīḥ al-Tirmidhī 2516 (graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Bukhari",
  },

  // ── The Heart ─────────────────────────────────────────────────────────────────
  {
    id: "h066",
    topic: "The Heart",
    arabic: "أَلاَ وَإِنَّ فِي الْجَسَدِ مُضْغَةً، إِذَا صَلَحَتْ صَلَحَ الْجَسَدُ كُلُّهُ، وَإِذَا فَسَدَتْ فَسَدَ الْجَسَدُ كُلُّهُ، أَلاَ وَهِيَ الْقَلْبُ",
    translation: "Indeed, in the body there is a piece of flesh. If it is sound, the whole body is sound, and if it is corrupt, the whole body is corrupt — it is the heart.",
    narrator: "Narrated by al-Nuʿmān ibn Bashīr (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 52 · Ṣaḥīḥ Muslim 1599",
    grade: "Sahih",
    collection: "Both",
  },
  {
    id: "h067",
    topic: "The Heart",
    arabic: "اتَّقِ اللَّهَ حَيْثُمَا كُنْتَ وَأَتْبِعِ السَّيِّئَةَ الْحَسَنَةَ تَمْحُهَا وَخَالِقِ النَّاسَ بِخُلُقٍ حَسَنٍ",
    translation: "Fear Allah wherever you are, follow a bad deed with a good one to erase it, and treat people with good character.",
    narrator: "Narrated by Abū Dharr and Muʿādh ibn Jabal (رضي الله عنهما)",
    source: "Ṣaḥīḥ al-Tirmidhī 1987 (graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Bukhari",
  },
  {
    id: "h068",
    topic: "The Heart",
    arabic: "أَلاَ إِنَّ الْبِرَّ حُسْنُ الْخُلُقِ، وَالإِثْمُ مَا حَاكَ فِي نَفْسِكَ وَكَرِهْتَ أَنْ يَطَّلِعَ عَلَيْهِ النَّاسُ",
    translation: "Righteousness is good character. Sin is whatever disturbs your conscience and you dislike that people would find out about it.",
    narrator: "Narrated by al-Nawwās ibn Samʿān (رضي الله عنه)",
    source: "Ṣaḥīḥ Muslim 2553",
    grade: "Sahih",
    collection: "Muslim",
  },

  // ── Modesty ───────────────────────────────────────────────────────────────────
  {
    id: "h069",
    topic: "Modesty",
    arabic: "الْحَيَاءُ لاَ يَأْتِي إِلاَّ بِخَيْرٍ",
    translation: "Modesty (hayāʾ) brings nothing except good.",
    narrator: "Narrated by ʿImrān ibn Ḥuṣayn (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 6117 · Ṣaḥīḥ Muslim 37",
    grade: "Sahih",
    collection: "Both",
  },
  {
    id: "h070",
    topic: "Modesty",
    arabic: "الْحَيَاءُ مِنَ الإِيمَانِ",
    translation: "Modesty is part of faith.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 24 · Ṣaḥīḥ Muslim 35",
    grade: "Sahih",
    collection: "Both",
  },
  {
    id: "h071",
    topic: "Modesty",
    arabic: "اسْتَحِيُوا مِنَ اللَّهِ حَقَّ الْحَيَاءِ",
    translation: "Be modest before Allah as He deserves.",
    narrator: "Narrated by ʿAbdullāh ibn Masʿūd (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Tirmidhī 2458 (graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Bukhari",
  },

  // ── Anger ─────────────────────────────────────────────────────────────────────
  {
    id: "h072",
    topic: "Anger",
    arabic: "لَا تَغْضَبْ",
    translation: "Do not get angry.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 6116",
    grade: "Sahih",
    collection: "Bukhari",
  },
  {
    id: "h073",
    topic: "Anger",
    arabic: "لَيْسَ الشَّدِيدُ بِالصُّرَعَةِ، إِنَّمَا الشَّدِيدُ الَّذِي يَمْلِكُ نَفْسَهُ عِنْدَ الْغَضَبِ",
    translation: "The strong person is not the one who can wrestle others down. The strong person is the one who controls himself when he is angry.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 6114 · Ṣaḥīḥ Muslim 2609",
    grade: "Sahih",
    collection: "Both",
  },
  {
    id: "h074",
    topic: "Anger",
    arabic: "إِذَا غَضِبَ أَحَدُكُمْ وَهُوَ قَائِمٌ فَلْيَجْلِسْ فَإِنْ ذَهَبَ عَنْهُ الْغَضَبُ وَإِلاَّ فَلْيَضْطَجِعْ",
    translation: "If one of you gets angry while standing, let him sit down. If the anger leaves, good; otherwise let him lie down.",
    narrator: "Narrated by Abū Dharr (رضي الله عنه)",
    source: "Ṣaḥīḥ Abū Dāwūd 4782 (graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Bukhari",
  },

  // ── Wealth ────────────────────────────────────────────────────────────────────
  {
    id: "h075",
    topic: "Wealth",
    arabic: "لَيْسَ الْغِنَى عَنْ كَثْرَةِ الْعَرَضِ، وَلَكِنَّ الْغِنَى غِنَى النَّفْسِ",
    translation: "Richness is not having many possessions. Rather, true richness is the richness of the soul.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 6446 · Ṣaḥīḥ Muslim 1051",
    grade: "Sahih",
    collection: "Both",
  },
  {
    id: "h076",
    topic: "Wealth",
    arabic: "مَا نَقَصَتْ صَدَقَةٌ مِنْ مَالٍ",
    translation: "Charity does not decrease wealth.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ Muslim 2588",
    grade: "Sahih",
    collection: "Muslim",
  },
  {
    id: "h077",
    topic: "Wealth",
    arabic: "أَيُّهَا النَّاسُ لاَ يَحِلُّ لاِمْرِئٍ مُسْلِمٍ مَالُ أَخِيهِ إِلاَّ بِطِيبِ نَفْسِهِ",
    translation: "O people! The wealth of a Muslim is not lawful for another except with his willing consent.",
    narrator: "Narrated by Abū Ḥumayd al-Sāʿidī (رضي الله عنه)",
    source: "Musnad Aḥmad (graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Muslim",
  },
  {
    id: "h078",
    topic: "Wealth",
    arabic: "وَاللَّهِ مَا الْفَقْرَ أَخْشَى عَلَيْكُمْ وَلَكِنِّي أَخْشَى أَنْ تُبْسَطَ عَلَيْكُمُ الدُّنْيَا",
    translation: "By Allah, it is not poverty that I fear for you, but I fear that the world will be opened up for you as it was for those before you, and you will compete with one another as they competed, and it will destroy you as it destroyed them.",
    narrator: "Narrated by ʿAmr ibn ʿAwf (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 3158 · Ṣaḥīḥ Muslim 2961",
    grade: "Sahih",
    collection: "Both",
  },

  // ── Paradise ──────────────────────────────────────────────────────────────────
  {
    id: "h079",
    topic: "Paradise",
    arabic: "حُفَّتِ الْجَنَّةُ بِالْمَكَارِهِ وَحُفَّتِ النَّارُ بِالشَّهَوَاتِ",
    translation: "Paradise is surrounded by hardships, and the Fire is surrounded by desires.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 6487 · Ṣaḥīḥ Muslim 2822",
    grade: "Sahih",
    collection: "Both",
  },
  {
    id: "h080",
    topic: "Paradise",
    arabic: "لَوْ أَنَّ رَجُلاً يُجَرُّ عَلَى وَجْهِهِ مِنْ يَوْمِ وُلِدَ إِلَى يَوْمِ يَمُوتُ هَرَماً فِي مَرْضَاةِ اللَّهِ لَحَقَّرَهُ يَوْمَ الْقِيَامَةِ",
    translation: "If a man were dragged on his face from birth until death in old age in seeking the pleasure of Allah, he would consider it insignificant on the Day of Resurrection.",
    narrator: "Narrated by Anas ibn Mālik (رضي الله عنه)",
    source: "Musnad Aḥmad (graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Muslim",
  },
  {
    id: "h081",
    topic: "Paradise",
    arabic: "قَالَ اللَّهُ أَعْدَدْتُ لِعِبَادِيَ الصَّالِحِينَ مَا لاَ عَيْنٌ رَأَتْ وَلاَ أُذُنٌ سَمِعَتْ وَلاَ خَطَرَ عَلَى قَلْبِ بَشَرٍ",
    translation: "Allah says: 'I have prepared for My righteous servants what no eye has seen, no ear has heard, and no human heart has conceived.'",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 3244 · Ṣaḥīḥ Muslim 2824",
    grade: "Sahih",
    collection: "Both",
  },
  {
    id: "h082",
    topic: "Paradise",
    arabic: "أَوَّلُ زُمْرَةٍ تَدْخُلُ الْجَنَّةَ عَلَى صُورَةِ الْقَمَرِ لَيْلَةَ الْبَدْرِ",
    translation: "The first group to enter Paradise will be like the full moon — radiant.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 3246 · Ṣaḥīḥ Muslim 2834",
    grade: "Sahih",
    collection: "Both",
  },

  // ── Good Character ────────────────────────────────────────────────────────────
  {
    id: "h083",
    topic: "Good Character",
    arabic: "أَكْمَلُ الْمُؤْمِنِينَ إِيمَاناً أَحْسَنُهُمْ خُلُقاً",
    translation: "The most perfect of the believers in faith is the best of them in character.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ Abū Dāwūd 4682 (graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Muslim",
  },
  {
    id: "h084",
    topic: "Good Character",
    arabic: "إِنَّمَا بُعِثْتُ لأُتَمِّمَ صَالِحَ الأَخْلاَقِ",
    translation: "I was sent only to perfect noble character.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Musnad Aḥmad 8952 (graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Bukhari",
  },
  {
    id: "h085",
    topic: "Good Character",
    arabic: "إِنَّ أَثْقَلَ شَيْءٍ فِي مِيزَانِ الْمُؤْمِنِ يَوْمَ الْقِيَامَةِ خُلُقٌ حَسَنٌ",
    translation: "The heaviest thing on the scale of the believer on the Day of Resurrection will be good character.",
    narrator: "Narrated by Abū al-Dardāʾ (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Tirmidhī 2002 (graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Bukhari",
  },
  {
    id: "h086",
    topic: "Good Character",
    arabic: "إِنَّ مِنْ أَحَبِّكُمْ إِلَيَّ وَأَقْرَبِكُمْ مِنِّي مَجْلِساً يَوْمَ الْقِيَامَةِ أَحَاسِنَكُمْ أَخْلاَقاً",
    translation: "Among those dearest to me and closest to me in position on the Day of Resurrection are those of you who are best in character.",
    narrator: "Narrated by Jābir ibn ʿAbdullāh (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Tirmidhī 2018 (graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Bukhari",
  },

  // ── Truthfulness ──────────────────────────────────────────────────────────────
  {
    id: "h087",
    topic: "Truthfulness",
    arabic: "عَلَيْكُمْ بِالصِّدْقِ فَإِنَّ الصِّدْقَ يَهْدِي إِلَى الْبِرِّ وَإِنَّ الْبِرَّ يَهْدِي إِلَى الْجَنَّةِ",
    translation: "Hold fast to truthfulness, for truthfulness leads to righteousness, and righteousness leads to Paradise.",
    narrator: "Narrated by ʿAbdullāh ibn Masʿūd (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 6094 · Ṣaḥīḥ Muslim 2607",
    grade: "Sahih",
    collection: "Both",
  },
  {
    id: "h088",
    topic: "Truthfulness",
    arabic: "آيَةُ الْمُنَافِقِ ثَلاثٌ إِذَا حَدَّثَ كَذَبَ وَإِذَا وَعَدَ أَخْلَفَ وَإِذَا اؤْتُمِنَ خَانَ",
    translation: "The signs of the hypocrite are three: when he speaks, he lies; when he makes a promise, he breaks it; and when he is entrusted with something, he betrays that trust.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 33 · Ṣaḥīḥ Muslim 59",
    grade: "Sahih",
    collection: "Both",
  },

  // ── Charity ───────────────────────────────────────────────────────────────────
  {
    id: "h089",
    topic: "Charity",
    arabic: "اتَّقُوا النَّارَ وَلَوْ بِشِقِّ تَمْرَةٍ",
    translation: "Protect yourselves from the Fire, even if it is with half a date.",
    narrator: "Narrated by ʿAdī ibn Ḥātim (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 1417 · Ṣaḥīḥ Muslim 1016",
    grade: "Sahih",
    collection: "Both",
  },
  {
    id: "h090",
    topic: "Charity",
    arabic: "الْيَدُ الْعُلْيَا خَيْرٌ مِنَ الْيَدِ السُّفْلَى",
    translation: "The upper hand is better than the lower hand (the giving hand is better than the taking hand).",
    narrator: "Narrated by ʿAbdullāh ibn ʿUmar (رضي الله عنهما)",
    source: "Ṣaḥīḥ al-Bukhārī 1427 · Ṣaḥīḥ Muslim 1033",
    grade: "Sahih",
    collection: "Both",
  },
  {
    id: "h091",
    topic: "Charity",
    arabic: "كُلُّ مَعْرُوفٍ صَدَقَةٌ",
    translation: "Every act of goodness is charity.",
    narrator: "Narrated by Jābir ibn ʿAbdullāh (رضي الله عنه)",
    source: "Ṣaḥīḥ Muslim 1005",
    grade: "Sahih",
    collection: "Muslim",
  },
  {
    id: "h092",
    topic: "Charity",
    arabic: "مَا مِنْ يَوْمٍ يُصْبِحُ الْعِبَادُ فِيهِ إِلاَّ مَلَكَانِ يَنْزِلاَنِ فَيَقُولُ أَحَدُهُمَا اللَّهُمَّ أَعْطِ مُنْفِقاً خَلَفاً وَيَقُولُ الآخَرُ اللَّهُمَّ أَعْطِ مُمْسِكاً تَلَفاً",
    translation: "Every day two angels descend. One says: 'O Allah, compensate the one who spends in charity.' The other says: 'O Allah, destroy the wealth of the one who withholds.'",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 1442 · Ṣaḥīḥ Muslim 1010",
    grade: "Sahih",
    collection: "Both",
  },

  // ── Night Prayer ──────────────────────────────────────────────────────────────
  {
    id: "h093",
    topic: "Night Prayer",
    arabic: "أَفْضَلُ الصَّلاةِ بَعْدَ الْفَرِيضَةِ صَلاةُ اللَّيْلِ",
    translation: "The best prayer after the obligatory prayers is the night prayer.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ Muslim 1163",
    grade: "Sahih",
    collection: "Muslim",
  },
  {
    id: "h094",
    topic: "Night Prayer",
    arabic: "يَنْزِلُ رَبُّنَا تَبَارَكَ وَتَعَالَى كُلَّ لَيْلَةٍ إِلَى السَّمَاءِ الدُّنْيَا حِينَ يَبْقَى ثُلُثُ اللَّيْلِ الآخِرُ يَقُولُ مَنْ يَدْعُونِي فَأَسْتَجِيبَ لَهُ",
    translation: "Our Lord, Blessed and Exalted, descends every night to the lowest heaven in the last third of the night and says: 'Who calls upon Me so that I may answer? Who asks of Me so that I may give? Who seeks My forgiveness so that I may forgive?'",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 1145 · Ṣaḥīḥ Muslim 758",
    grade: "Sahih",
    collection: "Both",
  },

  // ── Cleanliness ───────────────────────────────────────────────────────────────
  {
    id: "h095",
    topic: "Cleanliness",
    arabic: "الطُّهُورُ شَطْرُ الإِيمَانِ",
    translation: "Purity is half of faith.",
    narrator: "Narrated by Abū Mālik al-Ashʿarī (رضي الله عنه)",
    source: "Ṣaḥīḥ Muslim 223",
    grade: "Sahih",
    collection: "Muslim",
  },

  // ── Neighbours ────────────────────────────────────────────────────────────────
  {
    id: "h096",
    topic: "Neighbours",
    arabic: "لاَ يُؤْمِنُ مَنْ لاَ يَأْمَنُ جَارُهُ بَوَائِقَهُ",
    translation: "He is not a true believer whose neighbour is not safe from his harmful conduct.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 6016",
    grade: "Sahih",
    collection: "Bukhari",
  },
  {
    id: "h097",
    topic: "Neighbours",
    arabic: "مَا زَالَ جِبْرِيلُ يُوصِينِي بِالْجَارِ حَتَّى ظَنَنْتُ أَنَّهُ سَيُوَرِّثُهُ",
    translation: "Jibrīl kept urging me to treat neighbours well until I thought that he would make them heirs.",
    narrator: "Narrated by ʿĀʾishah (رضي الله عنها)",
    source: "Ṣaḥīḥ al-Bukhārī 6014 · Ṣaḥīḥ Muslim 2624",
    grade: "Sahih",
    collection: "Both",
  },

  // ── Feeding Others ────────────────────────────────────────────────────────────
  {
    id: "h098",
    topic: "Feeding Others",
    arabic: "أَطْعِمُوا الْجَائِعَ وَعُودُوا الْمَرِيضَ وَفُكُّوا الْعَانِيَ",
    translation: "Feed the hungry, visit the sick, and free those in captivity.",
    narrator: "Narrated by Abū Mūsā al-Ashʿarī (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 3046",
    grade: "Sahih",
    collection: "Bukhari",
  },

  // ── Smiling / Good Deeds ──────────────────────────────────────────────────────
  {
    id: "h099",
    topic: "Good Character",
    arabic: "تَبَسُّمُكَ فِي وَجْهِ أَخِيكَ لَكَ صَدَقَةٌ",
    translation: "Your smile in the face of your brother is charity.",
    narrator: "Narrated by Abū Dharr (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Tirmidhī 1956 (graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Bukhari",
  },

  // ── Moderation ────────────────────────────────────────────────────────────────
  {
    id: "h100",
    topic: "Moderation",
    arabic: "إِنَّ الدِّينَ يُسْرٌ، وَلَنْ يُشَادَّ الدِّينَ أَحَدٌ إِلاَّ غَلَبَهُ",
    translation: "Indeed, the religion is ease, and no one makes the religion difficult without being overwhelmed by it.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 39",
    grade: "Sahih",
    collection: "Bukhari",
  },
  {
    id: "h101",
    topic: "Moderation",
    arabic: "خُذُوا مِنَ الأَعْمَالِ مَا تُطِيقُونَ فَإِنَّ اللَّهَ لاَ يَمَلُّ حَتَّى تَمَلُّوا",
    translation: "Take up only those deeds that you are able to do, for Allah does not tire of rewarding, but you will tire (of doing good deeds).",
    narrator: "Narrated by ʿĀʾishah (رضي الله عنها)",
    source: "Ṣaḥīḥ al-Bukhārī 43 · Ṣaḥīḥ Muslim 785",
    grade: "Sahih",
    collection: "Both",
  },

  // ── Hajj ──────────────────────────────────────────────────────────────────────
  {
    id: "h102",
    topic: "Hajj",
    arabic: "مَنْ حَجَّ لِلَّهِ فَلَمْ يَرْفُثْ وَلَمْ يَفْسُقْ رَجَعَ كَيَوْمِ وَلَدَتْهُ أُمُّهُ",
    translation: "Whoever performs Ḥajj for the sake of Allah and refrains from indecency and wickedness returns as if he were the day his mother gave birth to him.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 1521 · Ṣaḥīḥ Muslim 1350",
    grade: "Sahih",
    collection: "Both",
  },
  {
    id: "h103",
    topic: "Hajj",
    arabic: "الْعُمْرَةُ إِلَى الْعُمْرَةِ كَفَّارَةٌ لِمَا بَيْنَهُمَا وَالْحَجُّ الْمَبْرُورُ لَيْسَ لَهُ جَزَاءٌ إِلاَّ الْجَنَّةُ",
    translation: "'Umrah to 'Umrah is expiation for what is between them, and an accepted Ḥajj has no reward except Paradise.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 1773 · Ṣaḥīḥ Muslim 1349",
    grade: "Sahih",
    collection: "Both",
  },

  // ── Zakat ─────────────────────────────────────────────────────────────────────
  {
    id: "h104",
    topic: "Zakat",
    arabic: "مَا مِنْ صَاحِبِ ذَهَبٍ وَلاَ فِضَّةٍ لاَ يُؤَدِّي مِنْهَا حَقَّهَا إِلاَّ إِذَا كَانَ يَوْمُ الْقِيَامَةِ صُفِّحَتْ لَهُ صَفَائِحُ مِنْ نَارٍ",
    translation: "There is no owner of gold or silver who does not pay what is due on it except that on the Day of Resurrection plates of fire will be made for him.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ Muslim 987",
    grade: "Sahih",
    collection: "Muslim",
  },

  // ── The World / Dunya ─────────────────────────────────────────────────────────
  {
    id: "h105",
    topic: "Wealth",
    arabic: "كُنْ فِي الدُّنْيَا كَأَنَّكَ غَرِيبٌ أَوْ عَابِرُ سَبِيلٍ",
    translation: "Be in the world as if you were a stranger or a traveller passing through.",
    narrator: "Narrated by ʿAbdullāh ibn ʿUmar (رضي الله عنهما)",
    source: "Ṣaḥīḥ al-Bukhārī 6416",
    grade: "Sahih",
    collection: "Bukhari",
  },
  {
    id: "h106",
    topic: "Wealth",
    arabic: "الدُّنْيَا سِجْنُ الْمُؤْمِنِ وَجَنَّةُ الْكَافِرِ",
    translation: "The world is a prison for the believer and a paradise for the unbeliever.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ Muslim 2956",
    grade: "Sahih",
    collection: "Muslim",
  },

  // ── Death / Afterlife ─────────────────────────────────────────────────────────
  {
    id: "h107",
    topic: "Afterlife",
    arabic: "أَكْثِرُوا ذِكْرَ هَاذِمِ اللَّذَّاتِ يَعْنِي الْمَوْتَ",
    translation: "Frequently remember the destroyer of pleasures — meaning death.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Tirmidhī 2307 (graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Bukhari",
  },
  {
    id: "h108",
    topic: "Afterlife",
    arabic: "مَنْ أَحَبَّ لِقَاءَ اللَّهِ أَحَبَّ اللَّهُ لِقَاءَهُ",
    translation: "Whoever loves to meet Allah, Allah loves to meet him.",
    narrator: "Narrated by ʿĀʾishah (رضي الله عنها)",
    source: "Ṣaḥīḥ al-Bukhārī 6507 · Ṣaḥīḥ Muslim 2683",
    grade: "Sahih",
    collection: "Both",
  },

  // ── Mercy of Allah ────────────────────────────────────────────────────────────
  {
    id: "h109",
    topic: "Trust in Allah",
    arabic: "إِنَّ لِلَّهِ مِائَةَ رَحْمَةٍ أَنْزَلَ مِنْهَا رَحْمَةً وَاحِدَةً بَيْنَ الْجِنِّ وَالإِنْسِ وَالْبَهَائِمِ وَالْهَوَامِّ",
    translation: "Allah has one hundred parts of mercy, and He sent down one part between jinn, humans, animals, and insects. Through this they show compassion to one another. He has kept ninety-nine parts for the Day of Resurrection.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 6469 · Ṣaḥīḥ Muslim 2752",
    grade: "Sahih",
    collection: "Both",
  },
  {
    id: "h110",
    topic: "Trust in Allah",
    arabic: "أَنَا عِنْدَ ظَنِّ عَبْدِي بِي",
    translation: "I am to My servant as he thinks of Me.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 7405 · Ṣaḥīḥ Muslim 2675",
    grade: "Sahih",
    collection: "Both",
  },

  // ── Backbiting ────────────────────────────────────────────────────────────────
  {
    id: "h111",
    topic: "Good Character",
    arabic: "أَتَدْرُونَ مَا الْغِيبَةُ قَالُوا اللَّهُ وَرَسُولُهُ أَعْلَمُ قَالَ ذِكْرُكَ أَخَاكَ بِمَا يَكْرَهُ",
    translation: "Do you know what backbiting is? They said: Allah and His Messenger know best. He said: It is to mention your brother in a way he would dislike.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ Muslim 2589",
    grade: "Sahih",
    collection: "Muslim",
  },

  // ── Rights ────────────────────────────────────────────────────────────────────
  {
    id: "h112",
    topic: "Brotherhood",
    arabic: "حَقُّ الْمُسْلِمِ عَلَى الْمُسْلِمِ سِتٌّ قِيلَ مَا هُنَّ يَا رَسُولَ اللَّهِ قَالَ إِذَا لَقِيتَهُ فَسَلِّمْ عَلَيْهِ",
    translation: "The rights of a Muslim upon a Muslim are six: greeting him when you meet him, accepting his invitation, responding when he sneezes, visiting him when he is ill, following his funeral when he dies, and wishing for him what you wish for yourself.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ Muslim 2162",
    grade: "Sahih",
    collection: "Muslim",
  },

  // ── Worship ───────────────────────────────────────────────────────────────────
  {
    id: "h113",
    topic: "Prayer",
    arabic: "إِنَّ اللَّهَ كَتَبَ الإِحْسَانَ عَلَى كُلِّ شَيْءٍ",
    translation: "Indeed, Allah has prescribed excellence in all things.",
    narrator: "Narrated by Shaddād ibn Aws (رضي الله عنه)",
    source: "Ṣaḥīḥ Muslim 1955",
    grade: "Sahih",
    collection: "Muslim",
  },
  {
    id: "h114",
    topic: "Intentions",
    arabic: "الإِيمَانُ بِضْعٌ وَسَبْعُونَ شُعْبَةً أَعْلاَهَا قَوْلُ لاَ إِلَهَ إِلاَّ اللَّهُ وَأَدْنَاهَا إِمَاطَةُ الأَذَى عَنِ الطَّرِيقِ",
    translation: "Faith has over seventy branches. The highest is saying 'Lā ilāha illAllāh' and the lowest is removing something harmful from the road.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 9 · Ṣaḥīḥ Muslim 35",
    grade: "Sahih",
    collection: "Both",
  },
  {
    id: "h115",
    topic: "Good Character",
    arabic: "مَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الآخِرِ فَلْيَقُلْ خَيْراً أَوْ لِيَصْمُتْ",
    translation: "Whoever believes in Allah and the Last Day, let him speak good or remain silent.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 6018 · Ṣaḥīḥ Muslim 47",
    grade: "Sahih",
    collection: "Both",
  },

  // ── Tawbah / Dhikr more ───────────────────────────────────────────────────────
  {
    id: "h116",
    topic: "Repentance",
    arabic: "وَاللَّهِ إِنِّي لأَسْتَغْفِرُ اللَّهَ وَأَتُوبُ إِلَيْهِ فِي الْيَوْمِ أَكْثَرَ مِنْ سَبْعِينَ مَرَّةً",
    translation: "By Allah! I seek forgiveness from Allah and turn to Him in repentance more than seventy times each day.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 6307",
    grade: "Sahih",
    collection: "Bukhari",
  },
  {
    id: "h117",
    topic: "Dhikr",
    arabic: "أَحَبُّ الأَعْمَالِ إِلَى اللَّهِ أَدْوَمُهَا وَإِنْ قَلَّ",
    translation: "The most beloved of deeds to Allah are those that are done consistently, even if they are small.",
    narrator: "Narrated by ʿĀʾishah (رضي الله عنها)",
    source: "Ṣaḥīḥ al-Bukhārī 6464 · Ṣaḥīḥ Muslim 783",
    grade: "Sahih",
    collection: "Both",
  },
  {
    id: "h118",
    topic: "Dhikr",
    arabic: "مَنْ قَالَ رَضِيتُ بِاللَّهِ رَبًّا وَبِالإِسْلاَمِ دِيناً وَبِمُحَمَّدٍ نَبِيًّا وَجَبَتْ لَهُ الْجَنَّةُ",
    translation: "Whoever says 'I am pleased with Allah as my Lord, Islam as my religion, and Muḥammad as my prophet' — Paradise is guaranteed for him.",
    narrator: "Narrated by Abū Saʿīd al-Khudrī (رضي الله عنه)",
    source: "Ṣaḥīḥ Abū Dāwūd 1529 (graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Bukhari",
  },

  // ── Enjoining Good ────────────────────────────────────────────────────────────
  {
    id: "h119",
    topic: "Brotherhood",
    arabic: "مَنْ رَأَى مِنْكُمْ مُنْكَراً فَلْيُغَيِّرْهُ بِيَدِهِ فَإِنْ لَمْ يَسْتَطِعْ فَبِلِسَانِهِ فَإِنْ لَمْ يَسْتَطِعْ فَبِقَلْبِهِ وَذَلِكَ أَضْعَفُ الإِيمَانِ",
    translation: "Whoever among you sees evil, let him change it with his hand; if he cannot, then with his tongue; if he cannot, then with his heart — and that is the weakest of faith.",
    narrator: "Narrated by Abū Saʿīd al-Khudrī (رضي الله عنه)",
    source: "Ṣaḥīḥ Muslim 49",
    grade: "Sahih",
    collection: "Muslim",
  },

  // ── Envy ─────────────────────────────────────────────────────────────────────
  {
    id: "h120",
    topic: "Good Character",
    arabic: "إِيَّاكُمْ وَالْحَسَدَ فَإِنَّ الْحَسَدَ يَأْكُلُ الْحَسَنَاتِ كَمَا تَأْكُلُ النَّارُ الْحَطَبَ",
    translation: "Beware of envy, for envy consumes good deeds just as fire consumes wood.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ Abū Dāwūd 4903 (graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Bukhari",
  },

  // ── Visiting the Sick ──────────────────────────────────────────────────────────
  {
    id: "h121",
    topic: "Brotherhood",
    arabic: "إِنَّ اللَّهَ عَزَّ وَجَلَّ يَقُولُ يَوْمَ الْقِيَامَةِ يَا ابْنَ آدَمَ مَرِضْتُ فَلَمْ تَعُدْنِي",
    translation: "Allah will say on the Day of Resurrection: 'O son of Ādam! I was sick and you did not visit Me.' The servant will say: 'Lord, how could I visit You when You are the Lord of the worlds?' He will say: 'Did you not know that My servant so-and-so was sick and you did not visit him?'",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ Muslim 2569",
    grade: "Sahih",
    collection: "Muslim",
  },

  // ── Gratitude More ────────────────────────────────────────────────────────────
  {
    id: "h122",
    topic: "Gratitude",
    arabic: "مَنْ لَمْ يَشْكُرِ الْقَلِيلَ لَمْ يَشْكُرِ الْكَثِيرَ",
    translation: "Whoever is not grateful for a little will not be grateful for much.",
    narrator: "Narrated by Abū Saʿīd al-Khudrī (رضي الله عنه)",
    source: "Musnad Aḥmad 11756 (graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Bukhari",
  },

  // ── Lying ────────────────────────────────────────────────────────────────────
  {
    id: "h123",
    topic: "Truthfulness",
    arabic: "وَإِيَّاكُمْ وَالْكَذِبَ فَإِنَّ الْكَذِبَ يَهْدِي إِلَى الْفُجُورِ وَإِنَّ الْفُجُورَ يَهْدِي إِلَى النَّارِ",
    translation: "Beware of lying, for lying leads to wickedness and wickedness leads to the Fire.",
    narrator: "Narrated by ʿAbdullāh ibn Masʿūd (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 6094 · Ṣaḥīḥ Muslim 2607",
    grade: "Sahih",
    collection: "Both",
  },

  // ── Hospitality ───────────────────────────────────────────────────────────────
  {
    id: "h124",
    topic: "Kindness",
    arabic: "مَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الآخِرِ فَلْيُكْرِمْ ضَيْفَهُ",
    translation: "Whoever believes in Allah and the Last Day, let him honour his guest.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 6018 · Ṣaḥīḥ Muslim 47",
    grade: "Sahih",
    collection: "Both",
  },

  // ── Sleep & Morning Adhkar ─────────────────────────────────────────────────────
  {
    id: "h125",
    topic: "Dhikr",
    arabic: "مَنْ قَالَ حِينَ يَأْوِي إِلَى فِرَاشِهِ لاَ إِلَهَ إِلاَّ اللَّهُ وَحْدَهُ لاَ شَرِيكَ لَهُ لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ غَفَرَ اللَّهُ لَهُ ذُنُوبَهُ",
    translation: "Whoever says when he goes to bed 'Lā ilāha illAllāh waḥdahu lā sharīka lah, lahul-mulku wa lahul-ḥamdu wa huwa ʿalā kulli shay'in qadīr,' Allah will forgive his sins.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 6327",
    grade: "Sahih",
    collection: "Bukhari",
  },

  // ── Bismillah ─────────────────────────────────────────────────────────────────
  {
    id: "h126",
    topic: "Dhikr",
    arabic: "كُلُّ أَمْرٍ ذِي بَالٍ لاَ يُبْدَأُ فِيهِ بِبِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ فَهُوَ أَبْتَرُ",
    translation: "Every matter of importance that does not begin with 'Bismillāh al-Raḥmān al-Raḥīm' is deficient.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ Ibn Ḥibbān 1 (graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Bukhari",
  },

  // ── Salah on the Prophet ──────────────────────────────────────────────────────
  {
    id: "h127",
    topic: "Dhikr",
    arabic: "مَنْ صَلَّى عَلَيَّ وَاحِدَةً صَلَّى اللَّهُ عَلَيْهِ عَشْراً",
    translation: "Whoever sends one blessing upon me, Allah will send ten blessings upon him.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ Muslim 408",
    grade: "Sahih",
    collection: "Muslim",
  },

  // ── Orphans ───────────────────────────────────────────────────────────────────
  {
    id: "h128",
    topic: "Kindness",
    arabic: "أَنَا وَكَافِلُ الْيَتِيمِ فِي الْجَنَّةِ هَكَذَا وَأَشَارَ بِالسَّبَّابَةِ وَالْوُسْطَى",
    translation: "I and the one who sponsors an orphan will be like this in Paradise — and he indicated with his index and middle fingers.",
    narrator: "Narrated by Sahl ibn Saʿd (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 5304",
    grade: "Sahih",
    collection: "Bukhari",
  },

  // ── Women ─────────────────────────────────────────────────────────────────────
  {
    id: "h129",
    topic: "Family",
    arabic: "اسْتَوْصُوا بِالنِّسَاءِ خَيْراً",
    translation: "Treat women kindly.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 3331 · Ṣaḥīḥ Muslim 1468",
    grade: "Sahih",
    collection: "Both",
  },

  // ── Sincerity ─────────────────────────────────────────────────────────────────
  {
    id: "h130",
    topic: "Intentions",
    arabic: "إِنَّ اللَّهَ لاَ يَقْبَلُ مِنَ الْعَمَلِ إِلاَّ مَا كَانَ لَهُ خَالِصاً وَابْتُغِيَ بِهِ وَجْهُهُ",
    translation: "Allah only accepts deeds that are done purely for Him and to seek His pleasure.",
    narrator: "Narrated by Abū Umāmah (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Nasāʾī 3140 (graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Bukhari",
  },

  // ── Trials ────────────────────────────────────────────────────────────────────
  {
    id: "h131",
    topic: "Patience",
    arabic: "أَشَدُّ النَّاسِ بَلاَءً الأَنْبِيَاءُ ثُمَّ الأَمْثَلُ فَالأَمْثَلُ",
    translation: "The people most severely tested are the prophets, then those closest to them in righteousness, then those after them.",
    narrator: "Narrated by Saʿd ibn Abī Waqqāṣ (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Tirmidhī 2398 (graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Bukhari",
  },
  {
    id: "h132",
    topic: "Patience",
    arabic: "إِنَّ عِظَمَ الْجَزَاءِ مَعَ عِظَمِ الْبَلاَءِ وَإِنَّ اللَّهَ إِذَا أَحَبَّ قَوْماً ابْتَلاَهُمْ",
    translation: "The greatness of the reward is in proportion to the greatness of the trial. When Allah loves a people He tests them.",
    narrator: "Narrated by Anas ibn Mālik (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Tirmidhī 2396 (graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Bukhari",
  },

  // ── Halal & Haram ─────────────────────────────────────────────────────────────
  {
    id: "h133",
    topic: "Truthfulness",
    arabic: "إِنَّ الْحَلاَلَ بَيِّنٌ وَإِنَّ الْحَرَامَ بَيِّنٌ وَبَيْنَهُمَا مُشْتَبِهَاتٌ",
    translation: "The lawful is clear and the unlawful is clear, and between them are ambiguous matters. Whoever avoids doubtful matters has protected his religion and his honour.",
    narrator: "Narrated by al-Nuʿmān ibn Bashīr (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 52 · Ṣaḥīḥ Muslim 1599",
    grade: "Sahih",
    collection: "Both",
  },

  // ── Du'a at Iftar ─────────────────────────────────────────────────────────────
  {
    id: "h134",
    topic: "Fasting",
    arabic: "لِلصَّائِمِ عِنْدَ فِطْرِهِ دَعْوَةٌ لاَ تُرَدُّ",
    translation: "The fasting person has, at the time of breaking his fast, a supplication that is not rejected.",
    narrator: "Narrated by ʿAbdullāh ibn ʿAmr (رضي الله عنه)",
    source: "Ṣaḥīḥ Ibn Mājah 1753 (graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Muslim",
  },

  // ── Suhur ─────────────────────────────────────────────────────────────────────
  {
    id: "h135",
    topic: "Fasting",
    arabic: "تَسَحَّرُوا فَإِنَّ فِي السَّحُورِ بَرَكَةً",
    translation: "Eat the pre-dawn meal (suḥūr), for in it there is blessing.",
    narrator: "Narrated by Anas ibn Mālik (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 1923 · Ṣaḥīḥ Muslim 1095",
    grade: "Sahih",
    collection: "Both",
  },

  // ── Laylatul Qadr ─────────────────────────────────────────────────────────────
  {
    id: "h136",
    topic: "Fasting",
    arabic: "مَنْ قَامَ لَيْلَةَ الْقَدْرِ إِيمَاناً وَاحْتِسَاباً غُفِرَ لَهُ مَا تَقَدَّمَ مِنْ ذَنْبِهِ",
    translation: "Whoever stands (in prayer) during the Night of Decree out of faith and seeking reward, his past sins will be forgiven.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 1901 · Ṣaḥīḥ Muslim 760",
    grade: "Sahih",
    collection: "Both",
  },

  // ── Dhikr & Quran more ────────────────────────────────────────────────────────
  {
    id: "h137",
    topic: "Quran",
    arabic: "تَعَلَّمُوا سُورَةَ الْبَقَرَةِ فَإِنَّ أَخْذَهَا بَرَكَةٌ وَتَرْكَهَا حَسْرَةٌ وَلاَ تَسْتَطِيعُهَا الْبَطَلَةُ",
    translation: "Learn Sūrat al-Baqarah, for taking it is a blessing, leaving it is a loss, and the sorcerers cannot overpower it.",
    narrator: "Narrated by Abū Umāmah (رضي الله عنه)",
    source: "Ṣaḥīḥ Muslim 804",
    grade: "Sahih",
    collection: "Muslim",
  },
  {
    id: "h138",
    topic: "Quran",
    arabic: "اقْرَءُوا الزَّهْرَاوَيْنِ الْبَقَرَةَ وَسُورَةَ آلِ عِمْرَانَ فَإِنَّهُمَا تَأْتِيَانِ يَوْمَ الْقِيَامَةِ كَأَنَّهُمَا غَمَامَتَانِ",
    translation: "Recite the two brilliant ones — al-Baqarah and Āl ʿImrān — for they will come on the Day of Resurrection as if they were two clouds or two shades.",
    narrator: "Narrated by Abū Umāmah (رضي الله عنه)",
    source: "Ṣaḥīḥ Muslim 804",
    grade: "Sahih",
    collection: "Muslim",
  },

  // ── Following the Prophet ──────────────────────────────────────────────────────
  {
    id: "h139",
    topic: "Intentions",
    arabic: "تَرَكْتُ فِيكُمْ مَا إِنْ تَمَسَّكْتُمْ بِهِ لَنْ تَضِلُّوا بَعْدِي أَبَداً كِتَابَ اللَّهِ",
    translation: "I have left among you something by which if you hold fast, you will never be led astray — the Book of Allah.",
    narrator: "Narrated by Jābir ibn ʿAbdullāh (رضي الله عنه)",
    source: "Ṣaḥīḥ Muslim 1218",
    grade: "Sahih",
    collection: "Muslim",
  },
  {
    id: "h140",
    topic: "Knowledge",
    arabic: "بَلِّغُوا عَنِّي وَلَوْ آيَةً",
    translation: "Convey from me, even if it is one verse.",
    narrator: "Narrated by ʿAbdullāh ibn ʿAmr (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 3461",
    grade: "Sahih",
    collection: "Bukhari",
  },

  // ── Steadfastness ─────────────────────────────────────────────────────────────
  {
    id: "h141",
    topic: "Trust in Allah",
    arabic: "قُلْ آمَنْتُ بِاللَّهِ ثُمَّ اسْتَقِمْ",
    translation: "Say: 'I believe in Allah,' and then be steadfast.",
    narrator: "Narrated by Sufyān ibn ʿAbdillāh al-Thaqafī (رضي الله عنه)",
    source: "Ṣaḥīḥ Muslim 38",
    grade: "Sahih",
    collection: "Muslim",
  },

  // ── Animals / Creation ────────────────────────────────────────────────────────
  {
    id: "h142",
    topic: "Kindness",
    arabic: "فِي كُلِّ كَبِدٍ رَطْبَةٍ أَجْرٌ",
    translation: "In every creature with a moist liver (i.e. every living being) there is a reward.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 2363 · Ṣaḥīḥ Muslim 2244",
    grade: "Sahih",
    collection: "Both",
  },
  {
    id: "h143",
    topic: "Kindness",
    arabic: "غُفِرَ لاِمْرَأَةٍ مُومِسَةٍ مَرَّتْ بِكَلْبٍ عَلَى رَأْسِ رَكِيٍّ يَلْهَثُ فَنَزَعَتْ خُفَّهَا فَاسْتَقَتْ لَهُ بِهِ فَسُقِيَ فَغُفِرَ لَهَا",
    translation: "A prostitute was forgiven because she passed by a dog panting at a well, and she drew water for it using her shoe — and she was forgiven.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 3467 · Ṣaḥīḥ Muslim 2245",
    grade: "Sahih",
    collection: "Both",
  },

  // ── Salah — Jumu'ah ───────────────────────────────────────────────────────────
  {
    id: "h144",
    topic: "Prayer",
    arabic: "مَنْ اغْتَسَلَ يَوْمَ الْجُمُعَةِ غُسْلَ الْجَنَابَةِ ثُمَّ رَاحَ فَكَأَنَّمَا قَرَّبَ بَدَنَةً",
    translation: "Whoever performs the ghusl on Friday like the ghusl for janābah, and then goes early to the prayer, it is as if he sacrificed a camel.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 881 · Ṣaḥīḥ Muslim 850",
    grade: "Sahih",
    collection: "Both",
  },
  {
    id: "h145",
    topic: "Prayer",
    arabic: "الْجُمُعَةُ إِلَى الْجُمُعَةِ كَفَّارَةٌ لِمَا بَيْنَهُنَّ",
    translation: "From Friday to Friday is an expiation for what comes between them.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ Muslim 233",
    grade: "Sahih",
    collection: "Muslim",
  },

  // ── Salah — Fajr & 'Isha ──────────────────────────────────────────────────────
  {
    id: "h146",
    topic: "Prayer",
    arabic: "مَنْ صَلَّى الْعِشَاءَ فِي جَمَاعَةٍ فَكَأَنَّمَا قَامَ نِصْفَ اللَّيْلِ وَمَنْ صَلَّى الصُّبْحَ فِي جَمَاعَةٍ فَكَأَنَّمَا صَلَّى اللَّيْلَ كُلَّهُ",
    translation: "Whoever prays ʿIshāʾ in congregation is as if he stood half the night in prayer. And whoever prays Fajr in congregation is as if he stood all night in prayer.",
    narrator: "Narrated by ʿUthmān ibn ʿAffān (رضي الله عنه)",
    source: "Ṣaḥīḥ Muslim 656",
    grade: "Sahih",
    collection: "Muslim",
  },

  // ── Sunnah Prayers ────────────────────────────────────────────────────────────
  {
    id: "h147",
    topic: "Prayer",
    arabic: "مَنْ حَافَظَ عَلَى أَرْبَعِ رَكَعَاتٍ قَبْلَ الظُّهْرِ وَأَرْبَعٍ بَعْدَهَا حَرَّمَهُ اللَّهُ عَلَى النَّارِ",
    translation: "Whoever maintains four rak'ahs before Dhuhr and four after it, Allah will forbid the Fire for him.",
    narrator: "Narrated by Umm Ḥabībah (رضي الله عنها)",
    source: "Ṣaḥīḥ al-Tirmidhī 428 (graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Bukhari",
  },

  // ── Greetings ─────────────────────────────────────────────────────────────────
  {
    id: "h148",
    topic: "Brotherhood",
    arabic: "لاَ تَدْخُلُوا الْجَنَّةَ حَتَّى تُؤْمِنُوا وَلاَ تُؤْمِنُوا حَتَّى تَحَابُّوا أَوَلاَ أَدُلُّكُمْ عَلَى شَيْءٍ إِذَا فَعَلْتُمُوهُ تَحَابَبْتُمْ أَفْشُوا السَّلاَمَ بَيْنَكُمْ",
    translation: "You will not enter Paradise until you believe, and you will not believe until you love one another. Shall I tell you something which, if you do it, you will love one another? Spread the greeting of salām amongst yourselves.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ Muslim 54",
    grade: "Sahih",
    collection: "Muslim",
  },

  // ── Children / Upbringing ─────────────────────────────────────────────────────
  {
    id: "h149",
    topic: "Family",
    arabic: "مَا نَحَلَ وَالِدٌ وَلَدَهُ مِنْ نَحْلٍ أَفْضَلَ مِنْ أَدَبٍ حَسَنٍ",
    translation: "No father has given his child a gift better than good manners.",
    narrator: "Narrated by Ayyūb ibn Mūsā (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Tirmidhī 1952 (graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Bukhari",
  },

  // ── Relying on Means + Tawakkul ───────────────────────────────────────────────
  {
    id: "h150",
    topic: "Trust in Allah",
    arabic: "اعْقِلْهَا وَتَوَكَّلْ",
    translation: "Tie it (your camel) and then put your trust in Allah.",
    narrator: "Narrated by Anas ibn Mālik (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Tirmidhī 2517 (graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Bukhari",
  },

  // ── Sunnah of Speech ──────────────────────────────────────────────────────────
  {
    id: "h151",
    topic: "Good Character",
    arabic: "إِنَّ الرَّجُلَ لَيَتَكَلَّمُ بِالْكَلِمَةِ مِنْ رِضْوَانِ اللَّهِ مَا يُلْقِي لَهَا بَالاً يَرْفَعُهُ اللَّهُ بِهَا دَرَجَاتٍ",
    translation: "A man may utter a word pleasing to Allah, thinking nothing of it, but Allah will raise him many degrees because of it.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 6478",
    grade: "Sahih",
    collection: "Bukhari",
  },
  {
    id: "h152",
    topic: "Good Character",
    arabic: "وَإِنَّ الرَّجُلَ لَيَتَكَلَّمُ بِالْكَلِمَةِ مِنْ سَخَطِ اللَّهِ لاَ يُلْقِي لَهَا بَالاً يَهْوِي بِهَا فِي جَهَنَّمَ",
    translation: "A man may utter a word displeasing to Allah, thinking nothing of it, but it will cause him to plunge into Hellfire.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 6478",
    grade: "Sahih",
    collection: "Bukhari",
  },

  // ── Justice ───────────────────────────────────────────────────────────────────
  {
    id: "h153",
    topic: "Brotherhood",
    arabic: "اتَّقُوا الظُّلْمَ فَإِنَّ الظُّلْمَ ظُلُمَاتٌ يَوْمَ الْقِيَامَةِ",
    translation: "Beware of oppression, for oppression will be darkness on the Day of Resurrection.",
    narrator: "Narrated by Jābir ibn ʿAbdillāh (رضي الله عنه)",
    source: "Ṣaḥīḥ Muslim 2578",
    grade: "Sahih",
    collection: "Muslim",
  },
  {
    id: "h154",
    topic: "Brotherhood",
    arabic: "الْمُقْسِطُونَ عِنْدَ اللَّهِ عَلَى مَنَابِرَ مِنْ نُورٍ",
    translation: "Those who are just will be on pulpits of light before Allah.",
    narrator: "Narrated by ʿAbdullāh ibn ʿAmr (رضي الله عنه)",
    source: "Ṣaḥīḥ Muslim 1827",
    grade: "Sahih",
    collection: "Muslim",
  },

  // ── Rizq / Provision ──────────────────────────────────────────────────────────
  {
    id: "h155",
    topic: "Trust in Allah",
    arabic: "إِنَّ رُوحَ الْقُدُسِ نَفَثَ فِي رُوعِي أَنَّ نَفْساً لَنْ تَمُوتَ حَتَّى تَسْتَكْمِلَ أَجَلَهَا وَتَسْتَوْعِبَ رِزْقَهَا",
    translation: "The Holy Spirit has whispered to my heart that no soul will die until it has completed its appointed term and received its provision in full, so fear Allah and seek provision in a good way.",
    narrator: "Narrated by Jābir ibn ʿAbdillāh (رضي الله عنه)",
    source: "Ṣaḥīḥ Ibn Ḥibbān 3239 (graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Muslim",
  },

  // ── Congregational Prayer ─────────────────────────────────────────────────────
  {
    id: "h156",
    topic: "Prayer",
    arabic: "صَلاةُ الْجَمَاعَةِ تَفْضُلُ صَلاةَ الْفَذِّ بِسَبْعٍ وَعِشْرِينَ دَرَجَةً",
    translation: "The congregational prayer is superior to the prayer of an individual by twenty-seven degrees.",
    narrator: "Narrated by ʿAbdullāh ibn ʿUmar (رضي الله عنهما)",
    source: "Ṣaḥīḥ al-Bukhārī 645 · Ṣaḥīḥ Muslim 650",
    grade: "Sahih",
    collection: "Both",
  },

  // ── Being Fair to Oneself ─────────────────────────────────────────────────────
  {
    id: "h157",
    topic: "Good Character",
    arabic: "لاَ ضَرَرَ وَلاَ ضِرَارَ",
    translation: "There should be no harm and no reciprocating harm.",
    narrator: "Narrated by ʿUbādah ibn al-Ṣāmit (رضي الله عنه)",
    source: "Ṣaḥīḥ Ibn Mājah 2340 (graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Muslim",
  },

  // ── Health ────────────────────────────────────────────────────────────────────
  {
    id: "h158",
    topic: "Gratitude",
    arabic: "نِعْمَتَانِ مَغْبُونٌ فِيهِمَا كَثِيرٌ مِنَ النَّاسِ الصِّحَّةُ وَالْفَرَاغُ",
    translation: "Two blessings that many people squander: health and free time.",
    narrator: "Narrated by ʿAbdullāh ibn ʿAbbās (رضي الله عنهما)",
    source: "Ṣaḥīḥ al-Bukhārī 6412",
    grade: "Sahih",
    collection: "Bukhari",
  },

  // ── Kindness to animals ───────────────────────────────────────────────────────
  {
    id: "h159",
    topic: "Kindness",
    arabic: "دَخَلَتِ امْرَأَةٌ النَّارَ فِي هِرَّةٍ رَبَطَتْهَا فَلَمْ تُطْعِمْهَا وَلَمْ تَدَعْهَا تَأْكُلُ مِنْ خَشَاشِ الأَرْضِ",
    translation: "A woman entered Hellfire because of a cat — she tied it up, neither feeding it nor letting it eat of the creatures of the earth.",
    narrator: "Narrated by ʿAbdullāh ibn ʿUmar (رضي الله عنهما)",
    source: "Ṣaḥīḥ al-Bukhārī 3318 · Ṣaḥīḥ Muslim 2619",
    grade: "Sahih",
    collection: "Both",
  },

  // ── Seeking Refuge ────────────────────────────────────────────────────────────
  {
    id: "h160",
    topic: "Dua",
    arabic: "تَعَوَّذُوا بِاللَّهِ مِنَ الْفِتَنِ مَا ظَهَرَ مِنْهَا وَمَا بَطَنَ",
    translation: "Seek refuge in Allah from trials, both those that are apparent and those that are hidden.",
    narrator: "Narrated by Zayd ibn Thābit (رضي الله عنه)",
    source: "Ṣaḥīḥ Muslim 2867",
    grade: "Sahih",
    collection: "Muslim",
  },

  // ── Speaking Well ─────────────────────────────────────────────────────────────
  {
    id: "h161",
    topic: "Good Character",
    arabic: "مَنْ صَمَتَ نَجَا",
    translation: "Whoever keeps silent is saved.",
    narrator: "Narrated by ʿAbdullāh ibn ʿAmr (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Tirmidhī 2501 (graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Bukhari",
  },

  // ── Aqeedah ───────────────────────────────────────────────────────────────────
  {
    id: "h162",
    topic: "Intentions",
    arabic: "بُنِيَ الإِسْلاَمُ عَلَى خَمْسٍ شَهَادَةِ أَنْ لاَ إِلَهَ إِلاَّ اللَّهُ وَأَنَّ مُحَمَّداً رَسُولُ اللَّهِ وَإِقَامِ الصَّلاَةِ وَإِيتَاءِ الزَّكَاةِ وَالْحَجِّ وَصَوْمِ رَمَضَانَ",
    translation: "Islam is built upon five: the testimony that there is no god but Allah and that Muḥammad is the Messenger of Allah, establishing prayer, giving zakāh, ḥajj, and fasting Ramaḍān.",
    narrator: "Narrated by ʿAbdullāh ibn ʿUmar (رضي الله عنهما)",
    source: "Ṣaḥīḥ al-Bukhārī 8 · Ṣaḥīḥ Muslim 16",
    grade: "Sahih",
    collection: "Both",
  },

  // ── More Dua ──────────────────────────────────────────────────────────────────
  {
    id: "h163",
    topic: "Dua",
    arabic: "أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ وَأَعُوذُ بِكَ مِنَ الْعَجْزِ وَالْكَسَلِ",
    translation: "I seek refuge in You from anxiety and sorrow, I seek refuge in You from weakness and laziness.",
    narrator: "Narrated by Anas ibn Mālik (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 2893",
    grade: "Sahih",
    collection: "Bukhari",
  },

  // ── Virtues of Friday ──────────────────────────────────────────────────────────
  {
    id: "h164",
    topic: "Prayer",
    arabic: "مَنْ صَلَّى عَلَيَّ حِينَ يُصْبِحُ عَشْراً وَحِينَ يُمْسِي عَشْراً أَدْرَكَتْهُ شَفَاعَتِي يَوْمَ الْقِيَامَةِ",
    translation: "Whoever sends ten blessings upon me in the morning and ten in the evening will receive my intercession on the Day of Resurrection.",
    narrator: "Narrated by Abū al-Dardāʾ (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Tirmidhī 484 (graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Bukhari",
  },

  // ── More Brotherhood ──────────────────────────────────────────────────────────
  {
    id: "h165",
    topic: "Brotherhood",
    arabic: "انْصُرْ أَخَاكَ ظَالِماً أَوْ مَظْلُوماً قَالَ رَجُلٌ يَا رَسُولَ اللَّهِ أَنْصُرُهُ إِذَا كَانَ مَظْلُوماً أَرَأَيْتَ إِنْ كَانَ ظَالِماً قَالَ تَحْجُزُهُ وَتَمْنَعُهُ مِنَ الظُّلْمِ فَإِنَّ ذَلِكَ نَصْرُهُ",
    translation: "Help your brother whether he is the oppressor or the oppressed. A man said: 'I help him when he is oppressed, but how do I help him when he is the oppressor?' He said: 'Restrain him from oppression — that is helping him.'",
    narrator: "Narrated by Anas ibn Mālik (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 2444",
    grade: "Sahih",
    collection: "Bukhari",
  },
  {
    id: "h166",
    topic: "Brotherhood",
    arabic: "لاَ يَحِلُّ لِمُسْلِمٍ أَنْ يَهْجُرَ أَخَاهُ فَوْقَ ثَلاَثٍ",
    translation: "It is not permissible for a Muslim to shun his brother for more than three days.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 6077 · Ṣaḥīḥ Muslim 2560",
    grade: "Sahih",
    collection: "Both",
  },

  // ── Du'a for Protection ───────────────────────────────────────────────────────
  {
    id: "h167",
    topic: "Dua",
    arabic: "اللَّهُمَّ عَافِنِي فِي بَدَنِي اللَّهُمَّ عَافِنِي فِي سَمْعِي اللَّهُمَّ عَافِنِي فِي بَصَرِي",
    translation: "O Allah, grant me health in my body. O Allah, grant me health in my hearing. O Allah, grant me health in my sight.",
    narrator: "Narrated by Abū Bakrah (رضي الله عنه)",
    source: "Ṣaḥīḥ Abū Dāwūd 5090 (graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Bukhari",
  },

  // ── Signs of a Believer ───────────────────────────────────────────────────────
  {
    id: "h168",
    topic: "Intentions",
    arabic: "مَنْ أَحَبَّ أَنْ يُزَحْزَحَ عَنِ النَّارِ وَيَدْخُلَ الْجَنَّةَ فَلْتَأْتِهِ مَنِيَّتُهُ وَهُوَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الآخِرِ",
    translation: "Whoever loves to be kept away from the Fire and to enter Paradise — let him die with faith in Allah and the Last Day.",
    narrator: "Narrated by ʿAbdullāh ibn ʿAmr (رضي الله عنه)",
    source: "Ṣaḥīḥ Muslim 1844",
    grade: "Sahih",
    collection: "Muslim",
  },

  // ── Asking Forgiveness ────────────────────────────────────────────────────────
  {
    id: "h169",
    topic: "Repentance",
    arabic: "مَنْ قَالَ سَيِّدُ الاِسْتِغْفَارِ اللَّهُمَّ أَنْتَ رَبِّي لاَ إِلَهَ إِلاَّ أَنْتَ خَلَقْتَنِي وَأَنَا عَبْدُكَ",
    translation: "Whoever says the Master of Forgiveness — 'Allāhumma anta Rabbī lā ilāha illā ant...' — with conviction in it in the morning, and dies that day before evening, he will be from the people of Paradise.",
    narrator: "Narrated by Shaddād ibn Aws (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 6306",
    grade: "Sahih",
    collection: "Bukhari",
  },

  // ── More Charity ──────────────────────────────────────────────────────────────
  {
    id: "h170",
    topic: "Charity",
    arabic: "السَّاعِي عَلَى الأَرْمَلَةِ وَالْمِسْكِينِ كَالْمُجَاهِدِ فِي سَبِيلِ اللَّهِ",
    translation: "The one who strives to support widows and the poor is like the one who strives in the path of Allah.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 5353 · Ṣaḥīḥ Muslim 2982",
    grade: "Sahih",
    collection: "Both",
  },
  {
    id: "h171",
    topic: "Charity",
    arabic: "أَفْضَلُ الصَّدَقَةِ أَنْ تَصَدَّقَ وَأَنْتَ صَحِيحٌ شَحِيحٌ تَأْمُلُ الْغِنَى وَتَخْشَى الْفَقْرَ",
    translation: "The best charity is to give while you are healthy and miserly, hoping for wealth and fearing poverty.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 1419 · Ṣaḥīḥ Muslim 1032",
    grade: "Sahih",
    collection: "Both",
  },

  // ── More Knowledge ────────────────────────────────────────────────────────────
  {
    id: "h172",
    topic: "Knowledge",
    arabic: "الْعُلَمَاءُ وَرَثَةُ الأَنْبِيَاءِ",
    translation: "The scholars are the inheritors of the prophets.",
    narrator: "Narrated by Abū al-Dardāʾ (رضي الله عنه)",
    source: "Ṣaḥīḥ Abū Dāwūd 3641 (graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Bukhari",
  },
  {
    id: "h173",
    topic: "Knowledge",
    arabic: "إِنَّمَا الْعِلْمُ بِالتَّعَلُّمِ",
    translation: "Verily, knowledge is attained only by learning.",
    narrator: "Narrated by Abū al-Dardāʾ (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī (al-Adab al-Mufrad, graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Bukhari",
  },

  // ── Honesty in Trade ──────────────────────────────────────────────────────────
  {
    id: "h174",
    topic: "Truthfulness",
    arabic: "الْبَيِّعَانِ بِالْخِيَارِ مَا لَمْ يَتَفَرَّقَا فَإِنْ صَدَقَا وَبَيَّنَا بُورِكَ لَهُمَا فِي بَيْعِهِمَا",
    translation: "The two parties to a transaction have the option to cancel until they part. If they are honest and transparent, their transaction will be blessed.",
    narrator: "Narrated by Ḥakīm ibn Ḥizām (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 2079 · Ṣaḥīḥ Muslim 1532",
    grade: "Sahih",
    collection: "Both",
  },

  // ── Modesty More ──────────────────────────────────────────────────────────────
  {
    id: "h175",
    topic: "Modesty",
    arabic: "إِنَّ مِمَّا أَدْرَكَ النَّاسُ مِنْ كَلاَمِ النُّبُوَّةِ الأُولَى إِذَا لَمْ تَسْتَحِ فَاصْنَعْ مَا شِئْتَ",
    translation: "Among the things that people have inherited from the words of the earlier prophethood is: 'If you have no shame, do whatever you wish.'",
    narrator: "Narrated by Abū Masʿūd (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 3484",
    grade: "Sahih",
    collection: "Bukhari",
  },

  // ── Graves & Death Reminder ───────────────────────────────────────────────────
  {
    id: "h176",
    topic: "Afterlife",
    arabic: "زُورُوا الْقُبُورَ فَإِنَّهَا تُذَكِّرُكُمُ الآخِرَةَ",
    translation: "Visit graves, for they remind you of the Hereafter.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ Muslim 976",
    grade: "Sahih",
    collection: "Muslim",
  },

  // ── Contentment ───────────────────────────────────────────────────────────────
  {
    id: "h177",
    topic: "Wealth",
    arabic: "قَدْ أَفْلَحَ مَنْ أَسْلَمَ وَرُزِقَ كَفَافاً وَقَنَّعَهُ اللَّهُ بِمَا آتَاهُ",
    translation: "He has succeeded who has accepted Islam, been given sufficient provision, and been made content by Allah with what He has given him.",
    narrator: "Narrated by ʿAbdullāh ibn ʿAmr (رضي الله عنه)",
    source: "Ṣaḥīḥ Muslim 1054",
    grade: "Sahih",
    collection: "Muslim",
  },

  // ── Dhikr at Morning and Evening ──────────────────────────────────────────────
  {
    id: "h178",
    topic: "Dhikr",
    arabic: "مَنْ قَالَ إِذَا أَصْبَحَ وَإِذَا أَمْسَى سُبْحَانَ اللَّهِ وَبِحَمْدِهِ مِائَةَ مَرَّةٍ لَمْ يَأْتِ أَحَدٌ يَوْمَ الْقِيَامَةِ بِأَفْضَلَ مِمَّا جَاءَ بِهِ",
    translation: "Whoever says 'SubḥānAllāhi wa biḥamdih' one hundred times in the morning and one hundred times in the evening — no one on the Day of Resurrection will come with anything better.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ Muslim 2692",
    grade: "Sahih",
    collection: "Muslim",
  },

  // ── Qiyāmah ───────────────────────────────────────────────────────────────────
  {
    id: "h179",
    topic: "Afterlife",
    arabic: "لاَ تَزُولُ قَدَمَا عَبْدٍ يَوْمَ الْقِيَامَةِ حَتَّى يُسْأَلَ عَنْ أَرْبَعٍ عَنْ عُمُرِهِ فِيمَا أَفْنَاهُ",
    translation: "The feet of a servant will not move on the Day of Resurrection until he is asked about four things: his life and how he spent it, his knowledge and what he did with it, his wealth — how he earned and spent it, and his body — how he wore it out.",
    narrator: "Narrated by Muʿādh ibn Jabal (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Tirmidhī 2417 (graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Bukhari",
  },

  // ── Community / Jama'ah ───────────────────────────────────────────────────────
  {
    id: "h180",
    topic: "Brotherhood",
    arabic: "يَدُ اللَّهِ مَعَ الْجَمَاعَةِ",
    translation: "The hand of Allah is with the group.",
    narrator: "Narrated by Ibn ʿAbbās (رضي الله عنهما)",
    source: "Ṣaḥīḥ al-Tirmidhī 2166 (graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Bukhari",
  },

  // ── Love for the Sake of Allah ────────────────────────────────────────────────
  {
    id: "h181",
    topic: "Brotherhood",
    arabic: "ثَلاثٌ مَنْ كُنَّ فِيهِ وَجَدَ بِهِنَّ حَلاوَةَ الإِيمَانِ أَنْ يَكُونَ اللَّهُ وَرَسُولُهُ أَحَبَّ إِلَيْهِ مِمَّا سِوَاهُمَا",
    translation: "Three qualities, whoever has them will taste the sweetness of faith: that Allah and His Messenger are more beloved to him than anything else; that he loves another person only for the sake of Allah; and that he would hate to return to disbelief as he would hate to be thrown into fire.",
    narrator: "Narrated by Anas ibn Mālik (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 16 · Ṣaḥīḥ Muslim 43",
    grade: "Sahih",
    collection: "Both",
  },

  // ── Sunnah on Waking ──────────────────────────────────────────────────────────
  {
    id: "h182",
    topic: "Dhikr",
    arabic: "إِذَا أَيْقَظَ أَحَدُكُمْ مِنْ نَوْمِهِ فَلاَ يُدْخِلْ يَدَهُ فِي الإِنَاءِ حَتَّى يَغْسِلَهَا ثَلاثاً",
    translation: "When one of you wakes from sleep, let him not put his hand in a vessel until he has washed it three times.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 162 · Ṣaḥīḥ Muslim 278",
    grade: "Sahih",
    collection: "Both",
  },

  // ── Piety ─────────────────────────────────────────────────────────────────────
  {
    id: "h183",
    topic: "The Heart",
    arabic: "إِنَّ اللَّهَ لاَ يَنْظُرُ إِلَى صُوَرِكُمْ وَأَمْوَالِكُمْ وَلَكِنْ يَنْظُرُ إِلَى قُلُوبِكُمْ وَأَعْمَالِكُمْ",
    translation: "Allah does not look at your forms or your wealth, but He looks at your hearts and your deeds.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ Muslim 2564",
    grade: "Sahih",
    collection: "Muslim",
  },

  // ── Food / Eating ─────────────────────────────────────────────────────────────
  {
    id: "h184",
    topic: "Moderation",
    arabic: "مَا مَلأَ آدَمِيٌّ وِعَاءً شَرًّا مِنْ بَطْنٍ، بِحَسْبِ ابْنِ آدَمَ أُكُلاتٌ يُقِمْنَ صُلْبَهُ",
    translation: "No human being has filled any vessel worse than his stomach. A few mouthfuls are sufficient for a person to keep his back straight.",
    narrator: "Narrated by al-Miqdām ibn Maʿdī Karib (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Tirmidhī 2380 (graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Bukhari",
  },

  // ── Hoping for Reward ──────────────────────────────────────────────────────────
  {
    id: "h185",
    topic: "Trust in Allah",
    arabic: "قَالَ اللَّهُ تَعَالَى أَنَا عِنْدَ ظَنِّ عَبْدِي بِي فَلْيَظُنَّ بِي مَا شَاءَ",
    translation: "Allah the Exalted says: 'I am as My servant thinks of Me, so let him think of Me as he wishes.'",
    narrator: "Narrated by Wāthilah ibn al-Asqaʿ (رضي الله عنه)",
    source: "Musnad Aḥmad (graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Muslim",
  },

  // ── Witr Prayer ───────────────────────────────────────────────────────────────
  {
    id: "h186",
    topic: "Prayer",
    arabic: "اللَّهَ وِتْرٌ يُحِبُّ الْوِتْرَ فَأَوْتِرُوا يَا أَهْلَ الْقُرْآنِ",
    translation: "Allah is Odd (Witr) and loves the odd number, so observe Witr, O people of the Quran.",
    narrator: "Narrated by ʿAlī ibn Abī Ṭālib (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 6410 · Ṣaḥīḥ Muslim 2677",
    grade: "Sahih",
    collection: "Both",
  },

  // ── Du'a for Knowledge ────────────────────────────────────────────────────────
  {
    id: "h187",
    topic: "Dua",
    arabic: "اللَّهُمَّ انْفَعْنِي بِمَا عَلَّمْتَنِي وَعَلِّمْنِي مَا يَنْفَعُنِي وَزِدْنِي عِلْماً",
    translation: "O Allah, benefit me with what You have taught me, teach me what will benefit me, and increase me in knowledge.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Tirmidhī 3599 (graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Bukhari",
  },

  // ── Ittiba / Following the Sunnah ─────────────────────────────────────────────
  {
    id: "h188",
    topic: "Intentions",
    arabic: "عَلَيْكُمْ بِسُنَّتِي وَسُنَّةِ الْخُلَفَاءِ الرَّاشِدِينَ الْمَهْدِيِّينَ",
    translation: "Hold fast to my Sunnah and the Sunnah of the rightly-guided caliphs.",
    narrator: "Narrated by ʿIrbāḍ ibn Sāriyah (رضي الله عنه)",
    source: "Ṣaḥīḥ Abū Dāwūd 4607 (graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Bukhari",
  },

  // ── Shukr / Praise ────────────────────────────────────────────────────────────
  {
    id: "h189",
    topic: "Gratitude",
    arabic: "الْحَمْدُ لِلَّهِ تَمْلأُ الْمِيزَانَ",
    translation: "'Al-ḥamdu lillāh' fills the scale.",
    narrator: "Narrated by Abū Mālik al-Ashʿarī (رضي الله عنه)",
    source: "Ṣaḥīḥ Muslim 223",
    grade: "Sahih",
    collection: "Muslim",
  },

  // ── Serving Others ────────────────────────────────────────────────────────────
  {
    id: "h190",
    topic: "Kindness",
    arabic: "خَيْرُ النَّاسِ أَنْفَعُهُمْ لِلنَّاسِ",
    translation: "The best of people are those who are most beneficial to others.",
    narrator: "Narrated by Jābir ibn ʿAbdillāh (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Jāmiʿ 3289 (graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Bukhari",
  },

  // ── Tests of Faith ────────────────────────────────────────────────────────────
  {
    id: "h191",
    topic: "Patience",
    arabic: "لاَ يَزَالُ الْبَلاَءُ بِالْمُؤْمِنِ وَالْمُؤْمِنَةِ فِي نَفْسِهِ وَوَلَدِهِ وَمَالِهِ حَتَّى يَلْقَى اللَّهَ وَمَا عَلَيْهِ خَطِيئَةٌ",
    translation: "Trials continue to befall the believing man and the believing woman in themselves, their children, and their wealth until they meet Allah with no sin upon them.",
    narrator: "Narrated by Abū Saʿīd and Abū Hurayrah (رضي الله عنهما)",
    source: "Ṣaḥīḥ al-Tirmidhī 2399 (graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Bukhari",
  },

  // ── Heaven's width ────────────────────────────────────────────────────────────
  {
    id: "h192",
    topic: "Paradise",
    arabic: "فِي الْجَنَّةِ مَا لاَ عَيْنٌ رَأَتْ وَلاَ أُذُنٌ سَمِعَتْ وَلاَ خَطَرَ عَلَى قَلْبِ بَشَرٍ",
    translation: "In Paradise there are things that no eye has seen, no ear has heard, and no human heart has ever conceived.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 3244",
    grade: "Sahih",
    collection: "Bukhari",
  },

  // ── Tawbah Nasūḥ ─────────────────────────────────────────────────────────────
  {
    id: "h193",
    topic: "Repentance",
    arabic: "إِنَّ اللَّهَ يَبْسُطُ يَدَهُ بِاللَّيْلِ لِيَتُوبَ مُسِيءُ النَّهَارِ وَيَبْسُطُ يَدَهُ بِالنَّهَارِ لِيَتُوبَ مُسِيءُ اللَّيْلِ",
    translation: "Allah extends His hand by night to accept the repentance of those who sinned by day, and extends His hand by day to accept the repentance of those who sinned by night.",
    narrator: "Narrated by Abū Mūsā al-Ashʿarī (رضي الله عنه)",
    source: "Ṣaḥīḥ Muslim 2759",
    grade: "Sahih",
    collection: "Muslim",
  },

  // ── Seeking Forgiveness ───────────────────────────────────────────────────────
  {
    id: "h194",
    topic: "Repentance",
    arabic: "إِنَّهُ لَيُغَانُ عَلَى قَلْبِي وَإِنِّي لأَسْتَغْفِرُ اللَّهَ فِي الْيَوْمِ مِائَةَ مَرَّةٍ",
    translation: "There is sometimes a covering over my heart, and I seek forgiveness from Allah one hundred times a day.",
    narrator: "Narrated by al-Agharr al-Muzanī (رضي الله عنه)",
    source: "Ṣaḥīḥ Muslim 2702",
    grade: "Sahih",
    collection: "Muslim",
  },

  // ── Tawhid ───────────────────────────────────────────────────────────────────
  {
    id: "h195",
    topic: "Intentions",
    arabic: "مَنْ مَاتَ وَهُوَ يَعْلَمُ أَنَّهُ لاَ إِلَهَ إِلاَّ اللَّهُ دَخَلَ الْجَنَّةَ",
    translation: "Whoever dies knowing that there is no god but Allah will enter Paradise.",
    narrator: "Narrated by ʿUthmān ibn ʿAffān (رضي الله عنه)",
    source: "Ṣaḥīḥ Muslim 26",
    grade: "Sahih",
    collection: "Muslim",
  },

  // ── Completing Good Deeds ──────────────────────────────────────────────────────
  {
    id: "h196",
    topic: "Intentions",
    arabic: "إِنَّ اللَّهَ كَتَبَ الْحَسَنَاتِ وَالسَّيِّئَاتِ ثُمَّ بَيَّنَ ذَلِكَ فَمَنْ هَمَّ بِحَسَنَةٍ فَلَمْ يَعْمَلْهَا كَتَبَهَا اللَّهُ لَهُ حَسَنَةً كَامِلَةً",
    translation: "Allah has decreed good deeds and bad deeds. Whoever intends a good deed and does not do it, Allah records it as a complete good deed.",
    narrator: "Narrated by Ibn ʿAbbās (رضي الله عنهما)",
    source: "Ṣaḥīḥ al-Bukhārī 6491 · Ṣaḥīḥ Muslim 131",
    grade: "Sahih",
    collection: "Both",
  },

  // ── Hope ─────────────────────────────────────────────────────────────────────
  {
    id: "h197",
    topic: "Trust in Allah",
    arabic: "لاَ يَمُوتَنَّ أَحَدُكُمْ إِلاَّ وَهُوَ يُحْسِنُ الظَّنَّ بِاللَّهِ",
    translation: "Let none of you die except while having good thoughts of Allah.",
    narrator: "Narrated by Jābir ibn ʿAbdillāh (رضي الله عنه)",
    source: "Ṣaḥīḥ Muslim 2877",
    grade: "Sahih",
    collection: "Muslim",
  },

  // ── Feeding the Family ────────────────────────────────────────────────────────
  {
    id: "h198",
    topic: "Family",
    arabic: "دِينَارٌ أَنْفَقْتَهُ فِي سَبِيلِ اللَّهِ وَدِينَارٌ أَنْفَقْتَهُ فِي رَقَبَةٍ وَدِينَارٌ تَصَدَّقْتَ بِهِ عَلَى مِسْكِينٍ وَدِينَارٌ أَنْفَقْتَهُ عَلَى أَهْلِكَ أَعْظَمُهَا أَجْراً الَّذِي أَنْفَقْتَهُ عَلَى أَهْلِكَ",
    translation: "Among all the dinars you spend — one in the path of Allah, one to free a slave, one in charity to a poor person, and one on your family — the greatest in reward is the one you spend on your family.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ Muslim 995",
    grade: "Sahih",
    collection: "Muslim",
  },

  // ── Greeting with Salaam ─────────────────────────────────────────────────────
  {
    id: "h199",
    topic: "Brotherhood",
    arabic: "أَيُّهَا النَّاسُ أَفْشُوا السَّلاَمَ وَأَطْعِمُوا الطَّعَامَ وَصِلُوا الأَرْحَامَ وَصَلُّوا بِاللَّيْلِ وَالنَّاسُ نِيَامٌ تَدْخُلُوا الْجَنَّةَ بِسَلاَمٍ",
    translation: "O people! Spread the salām, feed others, maintain ties of kinship, and pray at night while people are sleeping — and you will enter Paradise in peace.",
    narrator: "Narrated by ʿAbdullāh ibn Salām (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Tirmidhī 2485 (graded Ṣaḥīḥ)",
    grade: "Sahih",
    collection: "Bukhari",
  },

  // ── Imam and Leadership ───────────────────────────────────────────────────────
  {
    id: "h200",
    topic: "Brotherhood",
    arabic: "سَبْعَةٌ يُظِلُّهُمُ اللَّهُ فِي ظِلِّهِ يَوْمَ لاَ ظِلَّ إِلاَّ ظِلُّهُ إِمَامٌ عَادِلٌ",
    translation: "Seven will be shaded by Allah on the Day when there is no shade but His: a just leader; a young person who grew up worshipping Allah; a person whose heart is attached to the mosque; two people who love each other for Allah's sake; a man who is called to sin by a beautiful woman and says 'I fear Allah'; one who gives charity so secretly that his left hand does not know what his right hand gives; and one who remembers Allah in private and his eyes fill with tears.",
    narrator: "Narrated by Abū Hurayrah (رضي الله عنه)",
    source: "Ṣaḥīḥ al-Bukhārī 660 · Ṣaḥīḥ Muslim 1031",
    grade: "Sahih",
    collection: "Both",
  },
];

export const HADITH_TOPICS = [
  "All", "Intentions", "Prayer", "Quran", "Fasting", "Dhikr", "Dua",
  "Good Character", "Kindness", "Family", "Brotherhood", "Knowledge",
  "Patience", "Gratitude", "Repentance", "Trust in Allah", "The Heart",
  "Modesty", "Anger", "Wealth", "Paradise", "Truthfulness", "Charity",
  "Night Prayer", "Cleanliness", "Neighbours", "Feeding Others",
  "Hajj", "Zakat", "Moderation", "Afterlife",
];

export function getDailyHadith(): Hadith {
  return getDailyHadithForDate(new Date());
}

export function getDailyHadithForDate(date: Date): Hadith {
  const dayOfYear = Math.floor(
    (date.getTime() - new Date(date.getFullYear(), 0, 0).getTime()) / 86400000
  );
  return HADITHS[dayOfYear % HADITHS.length];
}
