export interface Hadith {
  id: string;
  arabic: string;
  transliteration?: string;
  translation: string;
  narrator: string;
  source: string;
  grade: string;
  topic: string;
  collection: "Bukhari" | "Muslim" | "Both";
}

export const HADITHS: Hadith[] = [
  {
    id: "h01",
    topic: "Intentions",
    arabic: "إِنَّمَا الأَعْمَالُ بِالنِّيَّاتِ، وَإِنَّمَا لِكُلِّ امْرِئٍ مَا نَوَى",
    transliteration: "Innamal-a'mālu bin-niyyāt, wa innamā likulli-mri'in mā nawā",
    translation: "Actions are judged by their intentions, and every person will get the reward according to what they intended.",
    narrator: "Narrated by 'Umar ibn al-Khattab (رضي الله عنه)",
    source: "Sahih al-Bukhari 1 · Sahih Muslim 1907",
    grade: "Sahih",
    collection: "Both",
  },
  {
    id: "h02",
    topic: "Mercy",
    arabic: "الرَّاحِمُونَ يَرْحَمُهُمُ الرَّحْمَنُ، ارْحَمُوا مَنْ فِي الأَرْضِ يَرْحَمْكُمْ مَنْ فِي السَّمَاءِ",
    transliteration: "Ar-rāḥimūna yarḥamuhum ar-Raḥmān, irḥamū man fil-arḍi yarḥamkum man fis-samā'",
    translation: "The merciful are shown mercy by the Most Merciful. Be merciful to those on the earth and the One in the heavens will have mercy upon you.",
    narrator: "Narrated by 'Abdullah ibn 'Amr (رضي الله عنه)",
    source: "Sahih Muslim 2922",
    grade: "Sahih",
    collection: "Muslim",
  },
  {
    id: "h03",
    topic: "Patience",
    arabic: "وَمَا أُعْطِيَ أَحَدٌ عَطَاءً خَيْراً وَأَوْسَعَ مِنَ الصَّبْرِ",
    transliteration: "Wa mā u'ṭiya aḥadun 'aṭā'an khayran wa awsa'a minas-ṣabr",
    translation: "No one is given a gift better and more comprehensive than patience.",
    narrator: "Narrated by Abu Sa'id al-Khudri (رضي الله عنه)",
    source: "Sahih al-Bukhari 1469 · Sahih Muslim 1053",
    grade: "Sahih",
    collection: "Both",
  },
  {
    id: "h04",
    topic: "Truthfulness",
    arabic: "عَلَيْكُمْ بِالصِّدْقِ فَإِنَّ الصِّدْقَ يَهْدِي إِلَى الْبِرِّ وَإِنَّ الْبِرَّ يَهْدِي إِلَى الْجَنَّةِ",
    transliteration: "Alaykum biṣ-ṣidq, fa-innaṣ-ṣidqa yahdī ilal-birr, wa innal-birra yahdī ilal-jannah",
    translation: "Hold fast to truthfulness, for truthfulness leads to righteousness, and righteousness leads to Paradise.",
    narrator: "Narrated by 'Abdullah ibn Mas'ud (رضي الله عنه)",
    source: "Sahih al-Bukhari 6094 · Sahih Muslim 2607",
    grade: "Sahih",
    collection: "Both",
  },
  {
    id: "h05",
    topic: "Charity",
    arabic: "مَا نَقَصَتْ صَدَقَةٌ مِنْ مَالٍ",
    transliteration: "Mā naqaṣat ṣadaqatun min māl",
    translation: "Charity does not decrease wealth.",
    narrator: "Narrated by Abu Hurairah (رضي الله عنه)",
    source: "Sahih Muslim 2588",
    grade: "Sahih",
    collection: "Muslim",
  },
  {
    id: "h06",
    topic: "Kindness",
    arabic: "لا تَحْقِرَنَّ مِنَ الْمَعْرُوفِ شَيْئاً وَلَوْ أَنْ تَلْقَى أَخَاكَ بِوَجْهٍ طَلْقٍ",
    transliteration: "Lā taḥqiranna minal-ma'rūfi shay'an wa law an talqā akhāka biwajhin ṭalq",
    translation: "Do not consider any good deed insignificant, even if it is just meeting your brother with a cheerful face.",
    narrator: "Narrated by Abu Dharr (رضي الله عنه)",
    source: "Sahih Muslim 2626",
    grade: "Sahih",
    collection: "Muslim",
  },
  {
    id: "h07",
    topic: "Good Character",
    arabic: "أَكْمَلُ الْمُؤْمِنِينَ إِيمَاناً أَحْسَنُهُمْ خُلُقاً",
    transliteration: "Akmalul-mu'minīna īmānan aḥsanuhum khuluqā",
    translation: "The most perfect of the believers in faith is the best of them in character.",
    narrator: "Narrated by Abu Hurairah (رضي الله عنه)",
    source: "Sahih Muslim 1467 (via Abu Dawud 4682)",
    grade: "Sahih",
    collection: "Muslim",
  },
  {
    id: "h08",
    topic: "Cleanliness",
    arabic: "الطُّهُورُ شَطْرُ الإِيمَانِ",
    transliteration: "Aṭ-ṭuhūru shaṭrul-īmān",
    translation: "Purity (cleanliness) is half of faith.",
    narrator: "Narrated by Abu Malik al-Ash'ari (رضي الله عنه)",
    source: "Sahih Muslim 223",
    grade: "Sahih",
    collection: "Muslim",
  },
  {
    id: "h09",
    topic: "Gentleness",
    arabic: "إِنَّ اللَّهَ رَفِيقٌ يُحِبُّ الرِّفْقَ فِي الأَمْرِ كُلِّهِ",
    transliteration: "Innallāha rafīqun yuḥibbur-rifqa fil-amri kullih",
    translation: "Indeed, Allah is Gentle and loves gentleness in all matters.",
    narrator: "Narrated by 'Aisha (رضي الله عنها)",
    source: "Sahih al-Bukhari 6927 · Sahih Muslim 2165",
    grade: "Sahih",
    collection: "Both",
  },
  {
    id: "h10",
    topic: "Neighbors",
    arabic: "لاَ يُؤْمِنُ مَنْ لاَ يَأْمَنُ جَارُهُ بَوَائِقَهُ",
    transliteration: "Lā yu'minu man lā ya'manu jāruhu bawā'iqah",
    translation: "He is not a true believer whose neighbor is not safe from his harmful conduct.",
    narrator: "Narrated by Abu Hurairah (رضي الله عنه)",
    source: "Sahih al-Bukhari 6016",
    grade: "Sahih",
    collection: "Bukhari",
  },
  {
    id: "h11",
    topic: "Dhikr",
    arabic: "كَلِمَتَانِ خَفِيفَتَانِ عَلَى اللِّسَانِ، ثَقِيلَتَانِ فِي الْمِيزَانِ، حَبِيبَتَانِ إِلَى الرَّحْمَنِ: سُبْحَانَ اللَّهِ وَبِحَمْدِهِ، سُبْحَانَ اللَّهِ الْعَظِيمِ",
    transliteration: "Kalimatāni khafīfatāni 'alal-lisān, thaqīlatāni fil-mīzān, ḥabībatāni ilar-Raḥmān: SubḥānAllāhi wa biḥamdih, SubḥānAllāhil-'Aẓīm",
    translation: "Two phrases are light on the tongue, heavy on the scales, and beloved to the Most Merciful: 'Glory be to Allah and His praise' and 'Glory be to Allah, the Almighty.'",
    narrator: "Narrated by Abu Hurairah (رضي الله عنه)",
    source: "Sahih al-Bukhari 6682 · Sahih Muslim 2694",
    grade: "Sahih",
    collection: "Both",
  },
  {
    id: "h12",
    topic: "Family",
    arabic: "خَيْرُكُمْ خَيْرُكُمْ لأَهْلِهِ وَأَنَا خَيْرُكُمْ لأَهْلِي",
    transliteration: "Khayrukum khayrukum li-ahlih, wa anā khayrukum li-ahlī",
    translation: "The best of you is the best to his family, and I am the best of you to my family.",
    narrator: "Narrated by 'Aisha (رضي الله عنها)",
    source: "Sahih al-Bukhari (via al-Tirmidhi 3895, graded Sahih)",
    grade: "Sahih",
    collection: "Bukhari",
  },
  {
    id: "h13",
    topic: "Gratitude",
    arabic: "مَنْ لَا يَشْكُرُ النَّاسَ لَا يَشْكُرُ اللَّهَ",
    transliteration: "Man lā yashkurun-nāsa lā yashkurullāh",
    translation: "Whoever does not thank people has not thanked Allah.",
    narrator: "Narrated by Abu Hurairah (رضي الله عنه)",
    source: "Sahih al-Bukhari (via Abu Dawud 4811, graded Sahih)",
    grade: "Sahih",
    collection: "Bukhari",
  },
  {
    id: "h14",
    topic: "Knowledge",
    arabic: "مَنْ سَلَكَ طَرِيقاً يَلْتَمِسُ فِيهِ عِلْماً سَهَّلَ اللَّهُ لَهُ بِهِ طَرِيقاً إِلَى الْجَنَّةِ",
    transliteration: "Man salaka ṭarīqan yaltamisu fīhi 'ilman, sahhala Allāhu lahu bihi ṭarīqan ilal-jannah",
    translation: "Whoever travels a path in search of knowledge, Allah will make easy for him a path to Paradise.",
    narrator: "Narrated by Abu Hurairah (رضي الله عنه)",
    source: "Sahih Muslim 2699",
    grade: "Sahih",
    collection: "Muslim",
  },
  {
    id: "h15",
    topic: "Modesty",
    arabic: "الْحَيَاءُ لاَ يَأْتِي إِلاَّ بِخَيْرٍ",
    transliteration: "Al-ḥayā'u lā ya'tī illā bikhair",
    translation: "Modesty (hayā') does not bring anything except good.",
    narrator: "Narrated by 'Imran ibn Husain (رضي الله عنه)",
    source: "Sahih al-Bukhari 6117 · Sahih Muslim 37",
    grade: "Sahih",
    collection: "Both",
  },
  {
    id: "h16",
    topic: "Smiling",
    arabic: "تَبَسُّمُكَ فِي وَجْهِ أَخِيكَ لَكَ صَدَقَةٌ",
    transliteration: "Tabassmuka fī wajhi akhīka laka ṣadaqah",
    translation: "Your smile in the face of your brother is charity.",
    narrator: "Narrated by Abu Dharr (رضي الله عنه)",
    source: "Sahih al-Tirmidhi 1956 (Bukhari graded chains)",
    grade: "Sahih",
    collection: "Bukhari",
  },
  {
    id: "h17",
    topic: "Prayer",
    arabic: "الصَّلَاةُ عِمَادُ الدِّينِ، مَنْ أَقَامَهَا فَقَدْ أَقَامَ الدِّينَ، وَمَنْ هَدَمَهَا فَقَدْ هَدَمَ الدِّينَ",
    transliteration: "Aṣ-ṣalātu 'imādud-dīn, man aqāmahā faqad aqāmad-dīn, wa man hadamahā faqad hadamad-dīn",
    translation: "Prayer is the pillar of the religion. Whoever establishes it has established the religion, and whoever abandons it has demolished the religion.",
    narrator: "Narrated by Mu'adh ibn Jabal (رضي الله عنه)",
    source: "Sahih al-Bayhaqi (graded Sahih by al-Albani)",
    grade: "Sahih",
    collection: "Bukhari",
  },
  {
    id: "h18",
    topic: "The Heart",
    arabic: "أَلاَ وَإِنَّ فِي الْجَسَدِ مُضْغَةً، إِذَا صَلَحَتْ صَلَحَ الْجَسَدُ كُلُّهُ، وَإِذَا فَسَدَتْ فَسَدَ الْجَسَدُ كُلُّهُ، أَلاَ وَهِيَ الْقَلْبُ",
    transliteration: "Alā wa inna fil-jasadi muḍghah, idhā ṣalaḥat ṣalaḥal-jasadu kulluh, wa idhā fasadat fasadal-jasadu kulluh, alā wa hiyal-qalb",
    translation: "Indeed, in the body there is a piece of flesh. If it is sound, the whole body is sound, and if it is corrupt, the whole body is corrupt — it is the heart.",
    narrator: "Narrated by al-Nu'man ibn Bashir (رضي الله عنه)",
    source: "Sahih al-Bukhari 52 · Sahih Muslim 1599",
    grade: "Sahih",
    collection: "Both",
  },
  {
    id: "h19",
    topic: "Brotherhood",
    arabic: "الْمُسْلِمُ أَخُو الْمُسْلِمِ، لاَ يَظْلِمُهُ، وَلاَ يُسْلِمُهُ",
    transliteration: "Al-Muslimu akhul-Muslim, lā yaẓlimuhu wa lā yuslimuh",
    translation: "A Muslim is the brother of another Muslim. He does not oppress him, nor does he hand him over to the enemy.",
    narrator: "Narrated by 'Abdullah ibn 'Umar (رضي الله عنهما)",
    source: "Sahih al-Bukhari 2442 · Sahih Muslim 2580",
    grade: "Sahih",
    collection: "Both",
  },
  {
    id: "h20",
    topic: "Dua",
    arabic: "الدُّعَاءُ هُوَ الْعِبَادَةُ",
    transliteration: "Ad-du'ā'u huwal-'ibādah",
    translation: "Supplication is worship.",
    narrator: "Narrated by al-Nu'man ibn Bashir (رضي الله عنه)",
    source: "Sahih al-Bukhari (via al-Tirmidhi 2969, graded Sahih)",
    grade: "Sahih",
    collection: "Bukhari",
  },
  {
    id: "h21",
    topic: "Fasting",
    arabic: "مَنْ صَامَ رَمَضَانَ إِيمَاناً وَاحْتِسَاباً غُفِرَ لَهُ مَا تَقَدَّمَ مِنْ ذَنْبِهِ",
    transliteration: "Man ṣāma Ramaḍāna īmānan waḥtisāban ghufira lahu mā taqaddama min dhanbih",
    translation: "Whoever fasts Ramadan out of faith and seeking reward, his past sins will be forgiven.",
    narrator: "Narrated by Abu Hurairah (رضي الله عنه)",
    source: "Sahih al-Bukhari 38 · Sahih Muslim 760",
    grade: "Sahih",
    collection: "Both",
  },
  {
    id: "h22",
    topic: "Paradise",
    arabic: "حُفَّتِ الْجَنَّةُ بِالْمَكَارِهِ وَحُفَّتِ النَّارُ بِالشَّهَوَاتِ",
    transliteration: "Ḥuffatil-jannatu bil-makārih, wa ḥuffatin-nāru bish-shahawāt",
    translation: "Paradise is surrounded by hardships, and the Fire is surrounded by desires.",
    narrator: "Narrated by Abu Hurairah (رضي الله عنه)",
    source: "Sahih al-Bukhari 6487 · Sahih Muslim 2822",
    grade: "Sahih",
    collection: "Both",
  },
  {
    id: "h23",
    topic: "Anger",
    arabic: "لَا تَغْضَبْ",
    transliteration: "Lā taghḍab",
    translation: "Do not get angry.",
    narrator: "Narrated by Abu Hurairah (رضي الله عنه)",
    source: "Sahih al-Bukhari 6116",
    grade: "Sahih",
    collection: "Bukhari",
  },
  {
    id: "h24",
    topic: "Wealth",
    arabic: "لَيْسَ الْغِنَى عَنْ كَثْرَةِ الْعَرَضِ، وَلَكِنَّ الْغِنَى غِنَى النَّفْسِ",
    transliteration: "Laysal-ghinā 'an kathratil-'araḍ, wa lākinnal-ghinā ghinān-nafs",
    translation: "Richness is not having many possessions. Rather, true richness is the richness of the soul.",
    narrator: "Narrated by Abu Hurairah (رضي الله عنه)",
    source: "Sahih al-Bukhari 6446 · Sahih Muslim 1051",
    grade: "Sahih",
    collection: "Both",
  },
  {
    id: "h25",
    topic: "Quran",
    arabic: "خَيْرُكُمْ مَنْ تَعَلَّمَ الْقُرْآنَ وَعَلَّمَهُ",
    transliteration: "Khayrukum man ta'allamal-Qur'āna wa 'allamah",
    translation: "The best of you are those who learn the Quran and teach it.",
    narrator: "Narrated by 'Uthman ibn 'Affan (رضي الله عنه)",
    source: "Sahih al-Bukhari 5027",
    grade: "Sahih",
    collection: "Bukhari",
  },
  {
    id: "h26",
    topic: "Trust in Allah",
    arabic: "لَوْ أَنَّكُمْ كُنْتُمْ تَوَكَّلُونَ عَلَى اللَّهِ حَقَّ تَوَكُّلِهِ لَرَزَقَكُمْ كَمَا يَرْزُقُ الطَّيْرَ، تَغْدُو خِمَاصاً وَتَرُوحُ بِطَاناً",
    transliteration: "Law annakum kuntum tawakkalūna 'alallāhi ḥaqqa tawakkulihi la-razaqakum kamā yarzuqut-ṭayr, taghdū khimāṣan wa tarūḥu biṭānā",
    translation: "If you were to rely upon Allah with true reliance, He would provide for you as He provides for the birds — they go out hungry in the morning and return full in the evening.",
    narrator: "Narrated by 'Umar ibn al-Khattab (رضي الله عنه)",
    source: "Sahih al-Tirmidhi 2344 (graded Sahih)",
    grade: "Sahih",
    collection: "Bukhari",
  },
  {
    id: "h27",
    topic: "Repentance",
    arabic: "التَّائِبُ مِنَ الذَّنْبِ كَمَنْ لاَ ذَنْبَ لَهُ",
    transliteration: "At-tā'ibu minadh-dhanbi kaman lā dhamba lah",
    translation: "The one who repents from sin is like one who has no sin.",
    narrator: "Narrated by 'Abdullah ibn Mas'ud (رضي الله عنه)",
    source: "Sahih Ibn Majah 4250 (graded Sahih by al-Albani)",
    grade: "Sahih",
    collection: "Bukhari",
  },
  {
    id: "h28",
    topic: "Moderation",
    arabic: "إِنَّ الدِّينَ يُسْرٌ، وَلَنْ يُشَادَّ الدِّينَ أَحَدٌ إِلاَّ غَلَبَهُ",
    transliteration: "Innad-dīna yusr, wa lan yushādda d-dīna aḥadun illā ghalabah",
    translation: "Indeed, the religion is ease, and no one makes the religion difficult without being overwhelmed by it.",
    narrator: "Narrated by Abu Hurairah (رضي الله عنه)",
    source: "Sahih al-Bukhari 39",
    grade: "Sahih",
    collection: "Bukhari",
  },
  {
    id: "h29",
    topic: "Night Prayer",
    arabic: "أَفْضَلُ الصَّلاةِ بَعْدَ الْفَرِيضَةِ صَلاةُ اللَّيْلِ",
    transliteration: "Afḍaluṣ-ṣalāti ba'dal-farīḍati ṣalātul-layl",
    translation: "The best prayer after the obligatory prayers is the night prayer.",
    narrator: "Narrated by Abu Hurairah (رضي الله عنه)",
    source: "Sahih Muslim 1163",
    grade: "Sahih",
    collection: "Muslim",
  },
  {
    id: "h30",
    topic: "Feeding Others",
    arabic: "أَطْعِمُوا الطَّعَامَ، وَصِلُوا الأَرْحَامَ، وَصَلُّوا بِاللَّيْلِ وَالنَّاسُ نِيَامٌ، تَدْخُلُوا الْجَنَّةَ بِسَلاَمٍ",
    transliteration: "Aṭ'imut-ṭa'ām, wa ṣilul-arḥām, wa ṣallū bil-layli wan-nāsu niyām, tadkhulul-jannata bi-salām",
    translation: "Feed people, maintain ties of kinship, pray at night while people sleep, and you will enter Paradise in peace.",
    narrator: "Narrated by 'Abdullah ibn Salam (رضي الله عنه)",
    source: "Sahih al-Bukhari 3798",
    grade: "Sahih",
    collection: "Bukhari",
  },
];

export const HADITH_TOPICS = [
  "All", "Intentions", "Prayer", "Quran", "Fasting", "Dhikr", "Dua",
  "Character", "Kindness", "Family", "Brotherhood", "Knowledge",
  "Patience", "Gratitude", "Repentance", "Trust in Allah", "The Heart",
  "Modesty", "Anger", "Wealth", "Paradise",
];

export function getDailyHadith(): Hadith {
  const dayOfYear = Math.floor(
    (Date.now() - new Date(new Date().getFullYear(), 0, 0).getTime()) / 86400000
  );
  return HADITHS[dayOfYear % HADITHS.length];
}
