uploads = []
generated = []

[[outputs]]
id = "7TUHSGXs-Ags9m_n5lXzg"
uri = "file://nuur-islamic-prayer.zip"
type = "unspecified"
title = "Nuur – Islamic Prayer App Source Code"

[[outputs]]
id = "AkRhP8pZt6VklvKhvS6YL"
uri = "file://nuur-islamic-prayer.tar.gz"
type = "unspecified"
title = "Nuur – Islamic Prayer App (source code)"
