// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/qada-ledger/EstimateWizard.tsx": () => import("../components/mockups/qada-ledger/EstimateWizard.tsx"),
  "./components/mockups/qada-ledger/Ledger.tsx": () => import("../components/mockups/qada-ledger/Ledger.tsx"),
  "./components/mockups/qada-ledger/MarkMakeUp.tsx": () => import("../components/mockups/qada-ledger/MarkMakeUp.tsx"),
  "./components/mockups/qada-ledger/Setup.tsx": () => import("../components/mockups/qada-ledger/Setup.tsx"),
  "./components/mockups/qada-ledger/WizardResult.tsx": () => import("../components/mockups/qada-ledger/WizardResult.tsx"),
  "./components/mockups/khushu-mode/Active.tsx": () => import("../components/mockups/khushu-mode/Active.tsx"),
  "./components/mockups/khushu-mode/AfterSalam.tsx": () => import("../components/mockups/khushu-mode/AfterSalam.tsx"),
  "./components/mockups/khushu-mode/PrePrayer.tsx": () => import("../components/mockups/khushu-mode/PrePrayer.tsx")
};
