// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/khushu-mode/Active.tsx": () => import("../components/mockups/khushu-mode/Active.tsx"),
  "./components/mockups/khushu-mode/AfterSalam.tsx": () => import("../components/mockups/khushu-mode/AfterSalam.tsx"),
  "./components/mockups/khushu-mode/PrePrayer.tsx": () => import("../components/mockups/khushu-mode/PrePrayer.tsx")
};
