// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/hadith-scholar/ScholarsLeaf.tsx": () => import("../components/mockups/hadith-scholar/ScholarsLeaf.tsx"),
  "./components/mockups/qada-ledger/EstimateWizard.tsx": () => import("../components/mockups/qada-ledger/EstimateWizard.tsx"),
  "./components/mockups/qada-ledger/Ledger.tsx": () => import("../components/mockups/qada-ledger/Ledger.tsx"),
  "./components/mockups/qada-ledger/MarkMakeUp.tsx": () => import("../components/mockups/qada-ledger/MarkMakeUp.tsx"),
  "./components/mockups/qada-ledger/Setup.tsx": () => import("../components/mockups/qada-ledger/Setup.tsx"),
  "./components/mockups/qada-ledger/WizardResult.tsx": () => import("../components/mockups/qada-ledger/WizardResult.tsx"),
  "./components/mockups/tasbeeh-hero/CountAsHero.tsx": () => import("../components/mockups/tasbeeh-hero/CountAsHero.tsx"),
  "./components/mockups/votd-mushaf/MushafLeaf.tsx": () => import("../components/mockups/votd-mushaf/MushafLeaf.tsx"),
  "./components/mockups/celestial-arc/Asr.tsx": () => import("../components/mockups/celestial-arc/Asr.tsx"),
  "./components/mockups/celestial-arc/CelestialArc.tsx": () => import("../components/mockups/celestial-arc/CelestialArc.tsx"),
  "./components/mockups/celestial-arc/Dhuhr.tsx": () => import("../components/mockups/celestial-arc/Dhuhr.tsx"),
  "./components/mockups/celestial-arc/Fajr.tsx": () => import("../components/mockups/celestial-arc/Fajr.tsx"),
  "./components/mockups/celestial-arc/Isha.tsx": () => import("../components/mockups/celestial-arc/Isha.tsx"),
  "./components/mockups/offline-audio/AudioSheet.tsx": () => import("../components/mockups/offline-audio/AudioSheet.tsx"),
  "./components/mockups/offline-audio/Storage.tsx": () => import("../components/mockups/offline-audio/Storage.tsx"),
  "./components/mockups/khushu-mode/Active.tsx": () => import("../components/mockups/khushu-mode/Active.tsx"),
  "./components/mockups/khushu-mode/AfterSalam.tsx": () => import("../components/mockups/khushu-mode/AfterSalam.tsx"),
  "./components/mockups/khushu-mode/PrePrayer.tsx": () => import("../components/mockups/khushu-mode/PrePrayer.tsx")
};
